export const RECENT_EVENT_RETENTION_MS = 30 * 60 * 1000;
export const HIDDEN_LEAVE_GRACE_MS = RECENT_EVENT_RETENTION_MS;
export const RECENT_EVENT_QUERY_SCAN_LIMIT = 20_000;
export const ACTIVE_NOW_WINDOW_MS = 5 * 60 * 1000;
export const VISIT_TIMEOUT_MS = 12 * 60 * 60 * 1000;
export const ORPHAN_CUSTOM_EVENT_TIMEOUT_MS = VISIT_TIMEOUT_MS;
export const WS_PRESENCE_LEAVE_EVENT = "__presence_leave";
export const WRITE_BUDGET_PER_INVOCATION = 200;
export const D1_FLUSH_INTERVAL_MS = 60 * 1000;
export const D1_FLUSH_BATCH_SIZE = 100;
export const D1_FLUSH_MAX_BATCHES_PER_ALARM = Math.max(
  1,
  Math.floor(WRITE_BUDGET_PER_INVOCATION / D1_FLUSH_BATCH_SIZE),
);
export const TIMEOUT_FINALIZE_BATCH_SIZE = WRITE_BUDGET_PER_INVOCATION;
export const FLUSHED_BUFFER_RETENTION_MS = RECENT_EVENT_RETENTION_MS;
export const DIAGNOSTIC_STALE_MS = 30 * 60 * 1000;
export const DIAGNOSTIC_HARD_AGE_MS = 36 * 60 * 60 * 1000;
export const DIAGNOSTIC_STUCK_FLUSH_ATTEMPTS = 5;
export const D1_FLUSH_CUSTOM_EVENT_BATCH_SIZE = 10;
