DROP TABLE IF EXISTS pageviews_new;

CREATE TABLE pageviews_new (
  id TEXT PRIMARY KEY,
  team_id TEXT NOT NULL,
  site_id TEXT NOT NULL,
  event_type TEXT NOT NULL,
  event_at INTEGER NOT NULL,
  received_at INTEGER NOT NULL,
  hour_bucket INTEGER NOT NULL,
  pathname TEXT NOT NULL,
  query_string TEXT,
  hash_fragment TEXT,
  title TEXT,
  hostname TEXT,
  referer TEXT,
  referer_host TEXT,
  utm_source TEXT,
  utm_medium TEXT,
  utm_campaign TEXT,
  utm_term TEXT,
  utm_content TEXT,
  visitor_id TEXT NOT NULL,
  session_id TEXT NOT NULL,
  duration_ms INTEGER NOT NULL DEFAULT 0,
  is_eu INTEGER NOT NULL DEFAULT 0,
  country TEXT,
  region TEXT,
  region_code TEXT,
  city TEXT,
  continent TEXT,
  latitude REAL,
  longitude REAL,
  postal_code TEXT,
  metro_code TEXT,
  timezone TEXT,
  colo TEXT,
  as_organization TEXT,
  ua_raw TEXT,
  browser TEXT,
  browser_version TEXT,
  os TEXT,
  os_version TEXT,
  device_type TEXT,
  screen_width INTEGER,
  screen_height INTEGER,
  language TEXT,
  created_at INTEGER NOT NULL DEFAULT (unixepoch())
);

INSERT INTO pageviews_new (
  id,
  team_id,
  site_id,
  event_type,
  event_at,
  received_at,
  hour_bucket,
  pathname,
  query_string,
  hash_fragment,
  title,
  hostname,
  referer,
  referer_host,
  utm_source,
  utm_medium,
  utm_campaign,
  utm_term,
  utm_content,
  visitor_id,
  session_id,
  duration_ms,
  is_eu,
  country,
  region,
  region_code,
  city,
  continent,
  latitude,
  longitude,
  postal_code,
  metro_code,
  timezone,
  colo,
  as_organization,
  ua_raw,
  browser,
  browser_version,
  os,
  os_version,
  device_type,
  screen_width,
  screen_height,
  language,
  created_at
)
SELECT
  id,
  team_id,
  site_id,
  event_type,
  event_at,
  received_at,
  hour_bucket,
  pathname,
  query_string,
  hash_fragment,
  title,
  hostname,
  referer,
  referer_host,
  utm_source,
  utm_medium,
  utm_campaign,
  utm_term,
  utm_content,
  visitor_id,
  session_id,
  duration_ms,
  is_eu,
  country,
  region,
  region_code,
  city,
  continent,
  latitude,
  longitude,
  postal_code,
  metro_code,
  timezone,
  colo,
  as_organization,
  ua_raw,
  browser,
  browser_version,
  os,
  os_version,
  device_type,
  screen_width,
  screen_height,
  language,
  created_at
FROM pageviews;

DROP TABLE pageviews;
ALTER TABLE pageviews_new RENAME TO pageviews;

CREATE INDEX IF NOT EXISTS idx_pageviews_site_event_at ON pageviews(site_id, event_at);
CREATE INDEX IF NOT EXISTS idx_pageviews_site_session_event_at ON pageviews(site_id, session_id, event_at);
CREATE INDEX IF NOT EXISTS idx_pageviews_site_visitor_event_at ON pageviews(site_id, visitor_id, event_at);
CREATE INDEX IF NOT EXISTS idx_pageviews_site_path_event_at ON pageviews(site_id, pathname, event_at);
CREATE INDEX IF NOT EXISTS idx_pageviews_event_at ON pageviews(event_at);
CREATE INDEX IF NOT EXISTS idx_pageviews_hour_bucket ON pageviews(hour_bucket);
