// Static route descriptors stay together for API schema generation and policy review.
// Lookup behavior is kept in route-lookups.ts.
// Static route descriptors stay together for API schema generation and policy review.
// Lookup behavior is kept in route-lookups.ts.
import { z } from "zod";

import { apiV1CoreRouteRegistry } from "@/lib/api-v1/application/core-registry";
import {
  SiteBreakdownQueryDtoSchema,
  SiteChannelsQueryDtoSchema,
  SiteComparisonBreakdownV2QueryDtoSchema,
  SiteComparisonQueryDtoSchema,
  SiteCrossBreakdownQueryDtoSchema,
  SiteEventDetailQueryDtoSchema,
  SiteEventFieldsQueryDtoSchema,
  SiteEventFieldValuesQueryDtoSchema,
  SiteEventsSearchQueryDtoSchema,
  SiteEventsSummaryQueryDtoSchema,
  SiteEventsTimeseriesQueryDtoSchema,
  SiteEventTypeDetailQueryDtoSchema,
  SiteEventTypesQueryDtoSchema,
  SiteFilterValuesQueryDtoSchema,
  SiteFunnelAnalysisQueryDtoSchema,
  SiteGoalSummaryQueryDtoSchema,
  SiteGoalTimeseriesQueryDtoSchema,
  SiteJourneyEventDetailQueryDtoSchema,
  SiteOverviewQueryDtoSchema,
  SitePagesQueryDtoSchema,
  SitePerformanceBreakdownDimensionSchema,
  SitePerformanceBreakdownQueryDtoSchema,
  SitePerformanceSummaryQueryDtoSchema,
  SitePerformanceTimeseriesQueryDtoSchema,
  SiteRealtimeActiveVisitorsQueryDtoSchema,
  SiteRealtimeEventsQueryDtoSchema,
  SiteRealtimeSessionsQueryDtoSchema,
  SiteRealtimeSnapshotQueryDtoSchema,
  SiteReferrersQueryDtoSchema,
  SiteRetentionCohortsQueryDtoSchema,
  SiteSessionDetailQueryDtoSchema,
  SiteSessionEventsQueryDtoSchema,
  SiteSessionsSearchQueryDtoSchema,
  SiteTimeseriesQueryDtoSchema,
  SiteVisitorDetailQueryDtoSchema,
  SiteVisitorEventsQueryDtoSchema,
  SiteVisitorSessionsQueryDtoSchema,
  SiteVisitorsSearchQueryDtoSchema,
  TeamBreakdownQueryDtoSchema,
  TeamComparisonBreakdownV2QueryDtoSchema,
  TeamComparisonQueryDtoSchema,
  TeamOverviewQueryDtoSchema,
  TeamSitesQueryDtoSchema,
  TeamTimeseriesQueryDtoSchema,
} from "@/lib/api-v1/contract/dto/analytics";
import { TypedBatchRequestSchema } from "@/lib/api-v1/contract/dto/batch";
import {
  CreateFunnelInputSchema,
  CreateGoalInputSchema,
  CreateSiteInputSchema,
  DeleteSiteInputSchema,
  FunnelResourcePageSchema,
  FunnelResourceSchema,
  GetFunnelInputSchema,
  GetGoalInputSchema,
  GetSiteInputSchema,
  GetTeamVisibleSavedFilterInputSchema,
  GoalResourcePageSchema,
  GoalResourceSchema,
  ListFunnelsInputSchema,
  ListGoalsInputSchema,
  ListSitesInputSchema,
  ListTeamVisibleSavedFiltersInputSchema,
  PrivacySettingsSchema,
  SavedFilterDefinitionSchema,
  SavedFilterPageSchema,
  SharingSettingsSchema,
  SiteResourcePageSchema,
  SiteResourceSchema,
  SiteSettingsInputSchema,
  TrackingScriptSchema,
  TrackingSettingsSchema,
  UpdateFunnelInputSchema,
  UpdateGoalInputSchema,
  UpdatePrivacySettingsInputSchema,
  UpdateSharingSettingsInputSchema,
  UpdateSiteInputSchema,
  UpdateTrackingSettingsInputSchema,
} from "@/lib/api-v1/contract/resources";
import {
  AnalyticsBreakdownResponseSchema,
  AnalyticsChannelsResponseSchema,
  AnalyticsComparisonBreakdownV2ResponseSchema,
  AnalyticsComparisonResponseSchema,
  AnalyticsCrossBreakdownResponseSchema,
  AnalyticsEventDetailResponseSchema,
  AnalyticsEventFieldsResponseSchema,
  AnalyticsEventFieldValuesResponseSchema,
  AnalyticsEventsSearchResponseSchema,
  AnalyticsEventsSummaryResponseSchema,
  AnalyticsEventsTimeseriesResponseSchema,
  AnalyticsEventTypeDetailResponseSchema,
  AnalyticsEventTypesResponseSchema,
  AnalyticsFilterValuesResponseSchema,
  AnalyticsFunnelAnalysisResponseSchema,
  AnalyticsGoalSummaryResponseSchema,
  AnalyticsGoalTimeseriesResponseSchema,
  AnalyticsJourneyEventDetailResponseSchema,
  AnalyticsJourneyEventsResponseSchema,
  AnalyticsJourneySessionsResponseSchema,
  AnalyticsOverviewResponseSchema,
  AnalyticsPagesResponseSchema,
  AnalyticsPerformanceBreakdownResponseSchema,
  AnalyticsPerformanceSummaryResponseSchema,
  AnalyticsPerformanceTimeseriesResponseSchema,
  AnalyticsRealtimeActiveVisitorsResponseSchema,
  AnalyticsRealtimeEventsResponseSchema,
  AnalyticsRealtimeSessionsResponseSchema,
  AnalyticsRealtimeSnapshotResponseSchema,
  AnalyticsReferrersResponseSchema,
  AnalyticsRetentionCohortsResponseSchema,
  AnalyticsSchemaResponseSchema,
  AnalyticsSessionDetailResponseSchema,
  AnalyticsSessionsSearchResponseSchema,
  AnalyticsTimeseriesResponseSchema,
  AnalyticsVisitorDetailResponseSchema,
  AnalyticsVisitorsSearchResponseSchema,
  TeamAnalyticsSitesResponseSchema,
  TypedBatchResponseSchema,
} from "@/lib/api-v1/contract/wire";

/**
 * Target API v1 routes. Planned entries are not Hono registrations until the
 * consumer and rollout gates recorded in the migration matrix are satisfied.
 */
/**
 * Target API v1 routes. Planned entries are not Hono registrations until the
 * consumer and rollout gates recorded in the migration matrix are satisfied.
 */
import type {
  ApiV1AnalyticsBreakdownRouteDescriptor,
  ApiV1AnalyticsComparisonRouteDescriptor,
  ApiV1AnalyticsCrossBreakdownRouteDescriptor,
  ApiV1AnalyticsEventRecordsRouteDescriptor,
  ApiV1AnalyticsEventsRouteDescriptor,
  ApiV1AnalyticsEventTypesRouteDescriptor,
  ApiV1AnalyticsFilterValuesRouteDescriptor,
  ApiV1AnalyticsFunnelAnalysisRouteDescriptor,
  ApiV1AnalyticsGoalRouteDescriptor,
  ApiV1AnalyticsJourneyDetailsRouteDescriptor,
  ApiV1AnalyticsJourneySearchRouteDescriptor,
  ApiV1AnalyticsJourneyTrajectoryRouteDescriptor,
  ApiV1AnalyticsListRouteDescriptor,
  ApiV1AnalyticsPerformanceRouteDescriptor,
  ApiV1AnalyticsRealtimeRouteDescriptor,
  ApiV1AnalyticsRetentionRouteDescriptor,
  ApiV1AnalyticsSchemaRouteDescriptor,
  ApiV1AnalyticsTeamBreakdownRouteDescriptor,
  ApiV1AnalyticsTeamSitesRouteDescriptor,
  ApiV1AnalyticsTimeseriesRouteDescriptor,
  ApiV1BatchRouteDescriptor,
} from "./route-registry/types";
export type * from "./route-registry/types";
import { analyticsRoute, applicationRoute } from "./route-registry/builders";
export const apiV1AnalyticsRouteRegistry = [
  analyticsRoute({
    id: "site.analytics.overview",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/overview",
    operationId: "site.analytics.overview",
    scopes: ["analytics:read"],
    conditionalScopes: [
      {
        when: "filter.type=saved",
        scopes: ["analytics:read", "analysis:read"],
      },
    ],
    requestSchema: SiteOverviewQueryDtoSchema,
    responseSchema: AnalyticsOverviewResponseSchema,
    declaredErrors: [
      "validation_failed",
      "invalid_cursor",
      "missing_scope",
      "resource_not_found",
      "data_unavailable",
      "deadline_exceeded",
      "internal_error",
    ],
  }),
  analyticsRoute({
    id: "team.analytics.overview",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/team/analytics/overview",
    operationId: "team.analytics.overview",
    scopes: ["analytics:read"],
    requestSchema: TeamOverviewQueryDtoSchema,
    responseSchema: AnalyticsOverviewResponseSchema,
    declaredErrors: [
      "validation_failed",
      "invalid_cursor",
      "missing_scope",
      "resource_not_found",
      "data_unavailable",
      "deadline_exceeded",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
      "invalid_cursor",
    ],
  }),
] as const;
export const apiV1AnalyticsComparisonRouteRegistry = [
  analyticsRoute({
    id: "site.analytics.comparison",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/comparison",
    operationId: "site.analytics.comparison",
    scopes: ["analytics:read"],
    conditionalScopes: [
      {
        when: "current.filter.type=saved|reference.filter.type=saved",
        scopes: ["analytics:read", "analysis:read"],
      },
    ],
    requestSchema: SiteComparisonQueryDtoSchema,
    responseSchema: AnalyticsComparisonResponseSchema,
    declaredErrors: [
      "validation_failed",
      "missing_scope",
      "resource_not_found",
      "query_too_expensive",
      "range_too_wide",
      "too_many_buckets",
      "comparison_alignment_mismatch",
      "deadline_exceeded",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
    ],
  }),
  analyticsRoute({
    id: "site.analytics.comparisonBreakdown",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/comparison/breakdowns/{dimension}",
    operationId: "site.analytics.comparisonBreakdown",
    scopes: ["analytics:read"],
    conditionalScopes: [
      {
        when: "current.filter.type=saved|reference.filter.type=saved",
        scopes: ["analytics:read", "analysis:read"],
      },
    ],
    requestSchema: SiteComparisonBreakdownV2QueryDtoSchema,
    responseSchema: AnalyticsComparisonBreakdownV2ResponseSchema,
    declaredErrors: [
      "validation_failed",
      "missing_scope",
      "resource_not_found",
      "query_too_expensive",
      "range_too_wide",
      "too_many_buckets",
      "comparison_alignment_mismatch",
      "dimension_not_supported",
      "deadline_exceeded",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
    ],
  }),
  analyticsRoute({
    id: "team.analytics.comparison",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/team/analytics/comparison",
    operationId: "team.analytics.comparison",
    scopes: ["analytics:read"],
    requestSchema: TeamComparisonQueryDtoSchema,
    responseSchema: AnalyticsComparisonResponseSchema,
    declaredErrors: [
      "validation_failed",
      "missing_scope",
      "query_too_expensive",
      "range_too_wide",
      "too_many_buckets",
      "comparison_alignment_mismatch",
      "deadline_exceeded",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
    ],
  }),
  analyticsRoute({
    id: "team.analytics.comparisonBreakdown",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/team/analytics/comparison/breakdowns/{dimension}",
    operationId: "team.analytics.comparisonBreakdown",
    scopes: ["analytics:read"],
    requestSchema: TeamComparisonBreakdownV2QueryDtoSchema,
    responseSchema: AnalyticsComparisonBreakdownV2ResponseSchema,
    declaredErrors: [
      "validation_failed",
      "missing_scope",
      "query_too_expensive",
      "range_too_wide",
      "too_many_buckets",
      "comparison_alignment_mismatch",
      "dimension_not_supported",
      "deadline_exceeded",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
    ],
  }),
] as const satisfies readonly ApiV1AnalyticsComparisonRouteDescriptor<string>[];
export const apiV1AnalyticsSchemaRouteRegistry = [
  {
    id: "site.analytics.schema",
    lifecycle: "exposed",
    method: "GET",
    path: "/api/v1/sites/{siteId}/analytics/schema",
    scopes: ["analytics:read"],
    responseSchema: AnalyticsSchemaResponseSchema,
    declaredErrors: [
      "missing_scope",
      "resource_not_found",
      "validation_failed",
      "internal_error",
      "method_not_allowed",
    ],
  },
  {
    id: "team.analytics.schema",
    lifecycle: "exposed",
    method: "GET",
    path: "/api/v1/team/analytics/schema",
    scopes: ["analytics:read"],
    responseSchema: AnalyticsSchemaResponseSchema,
    declaredErrors: [
      "missing_scope",
      "resource_not_found",
      "validation_failed",
      "internal_error",
      "method_not_allowed",
    ],
  },
] as const satisfies readonly ApiV1AnalyticsSchemaRouteDescriptor<string>[];
export const apiV1AnalyticsTimeseriesRouteRegistry = [
  {
    id: "site.analytics.timeseries",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/timeseries",
    operationId: "site.analytics.timeseries",
    scopes: ["analytics:read"],
    conditionalScopes: [
      {
        when: "filter.type=saved",
        scopes: ["analytics:read", "analysis:read"],
      },
    ],
    requestSchema: SiteTimeseriesQueryDtoSchema,
    responseSchema: AnalyticsTimeseriesResponseSchema,
    declaredErrors: [
      "validation_failed",
      "missing_scope",
      "resource_not_found",
      "data_unavailable",
      "deadline_exceeded",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
    ],
  },
  {
    id: "team.analytics.timeseries",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/team/analytics/timeseries",
    operationId: "team.analytics.timeseries",
    scopes: ["analytics:read"],
    requestSchema: TeamTimeseriesQueryDtoSchema,
    responseSchema: AnalyticsTimeseriesResponseSchema,
    declaredErrors: [
      "validation_failed",
      "missing_scope",
      "data_unavailable",
      "deadline_exceeded",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
    ],
  },
] as const satisfies readonly ApiV1AnalyticsTimeseriesRouteDescriptor<string>[];
export const apiV1AnalyticsTeamSitesRouteRegistry = [
  {
    id: "team.analytics.sites",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/team/analytics/sites",
    operationId: "team.analytics.sites",
    scopes: ["analytics:read"],
    requestSchema: TeamSitesQueryDtoSchema,
    responseSchema: TeamAnalyticsSitesResponseSchema,
    declaredErrors: [
      "validation_failed",
      "missing_scope",
      "data_unavailable",
      "deadline_exceeded",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
      "invalid_cursor",
    ],
  },
] as const satisfies readonly ApiV1AnalyticsTeamSitesRouteDescriptor<string>[];
export const apiV1AnalyticsBreakdownRouteRegistry = [
  {
    id: "site.analytics.breakdown",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/breakdowns/{dimension}",
    operationId: "site.analytics.breakdown",
    scopes: ["analytics:read"],
    conditionalScopes: [
      {
        when: "filter.type=saved",
        scopes: ["analytics:read", "analysis:read"],
      },
    ],
    requestSchema: SiteBreakdownQueryDtoSchema,
    responseSchema: AnalyticsBreakdownResponseSchema,
    declaredErrors: [
      "validation_failed",
      "missing_scope",
      "resource_not_found",
      "deadline_exceeded",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
    ],
  },
] as const satisfies readonly ApiV1AnalyticsBreakdownRouteDescriptor<string>[];
export const apiV1AnalyticsTeamBreakdownRouteRegistry = [
  {
    id: "team.analytics.breakdown",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/team/analytics/breakdowns/{dimension}",
    operationId: "team.analytics.breakdown",
    scopes: ["analytics:read"],
    requestSchema: TeamBreakdownQueryDtoSchema,
    responseSchema: AnalyticsBreakdownResponseSchema,
    declaredErrors: [
      "validation_failed",
      "missing_scope",
      "unsupported_query",
      "deadline_exceeded",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
    ],
  },
] as const satisfies readonly ApiV1AnalyticsTeamBreakdownRouteDescriptor<string>[];
export const apiV1AnalyticsCrossBreakdownRouteRegistry = [
  {
    id: "site.analytics.crossBreakdown",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/cross-breakdowns",
    operationId: "site.analytics.crossBreakdown",
    scopes: ["analytics:read"],
    conditionalScopes: [
      {
        when: "filter.type=saved",
        scopes: ["analytics:read", "analysis:read"],
      },
    ],
    requestSchema: SiteCrossBreakdownQueryDtoSchema,
    responseSchema: AnalyticsCrossBreakdownResponseSchema,
    declaredErrors: [
      "validation_failed",
      "missing_scope",
      "resource_not_found",
      "dimension_not_supported",
      "deadline_exceeded",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
    ],
  },
] as const satisfies readonly ApiV1AnalyticsCrossBreakdownRouteDescriptor<string>[];
export const apiV1AnalyticsListRouteRegistry = [
  {
    id: "site.analytics.pages",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/pages",
    operationId: "site.analytics.pages",
    scopes: ["analytics:read"],
    conditionalScopes: [
      {
        when: "filter.type=saved",
        scopes: ["analytics:read", "analysis:read"],
      },
    ],
    requestSchema: SitePagesQueryDtoSchema,
    responseSchema: AnalyticsPagesResponseSchema,
    declaredErrors: [
      "validation_failed",
      "missing_scope",
      "resource_not_found",
      "deadline_exceeded",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
    ],
  },
  {
    id: "site.analytics.referrers",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/referrers",
    operationId: "site.analytics.referrers",
    scopes: ["analytics:read"],
    conditionalScopes: [
      {
        when: "filter.type=saved",
        scopes: ["analytics:read", "analysis:read"],
      },
    ],
    requestSchema: SiteReferrersQueryDtoSchema,
    responseSchema: AnalyticsReferrersResponseSchema,
    declaredErrors: [
      "validation_failed",
      "missing_scope",
      "resource_not_found",
      "deadline_exceeded",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
    ],
  },
  {
    id: "site.analytics.channels",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/channels",
    operationId: "site.analytics.channels",
    scopes: ["analytics:read"],
    conditionalScopes: [
      {
        when: "filter.type=saved",
        scopes: ["analytics:read", "analysis:read"],
      },
    ],
    requestSchema: SiteChannelsQueryDtoSchema,
    responseSchema: AnalyticsChannelsResponseSchema,
    declaredErrors: [
      "validation_failed",
      "missing_scope",
      "resource_not_found",
      "deadline_exceeded",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
    ],
  },
] as const satisfies readonly ApiV1AnalyticsListRouteDescriptor<string>[];
export const apiV1AnalyticsFilterValuesRouteRegistry = [
  {
    id: "site.analytics.filterValues",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/filter-values",
    operationId: "site.analytics.filterValues",
    scopes: ["analytics:read"],
    conditionalScopes: [
      {
        when: "filter.type=saved",
        scopes: ["analytics:read", "analysis:read"],
      },
    ],
    requestSchema: SiteFilterValuesQueryDtoSchema,
    responseSchema: AnalyticsFilterValuesResponseSchema,
    declaredErrors: [
      "validation_failed",
      "missing_scope",
      "resource_not_found",
      "deadline_exceeded",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
    ],
  },
] as const satisfies readonly ApiV1AnalyticsFilterValuesRouteDescriptor<string>[];
export const apiV1AnalyticsRetentionRouteRegistry = [
  {
    id: "site.analytics.retentionCohorts",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/retention/cohorts",
    operationId: "site.analytics.retentionCohorts",
    scopes: ["analytics:read"],
    conditionalScopes: [
      {
        when: "filter.type=saved",
        scopes: ["analytics:read", "analysis:read"],
      },
    ],
    requestSchema: SiteRetentionCohortsQueryDtoSchema,
    responseSchema: AnalyticsRetentionCohortsResponseSchema,
    declaredErrors: [
      "validation_failed",
      "missing_scope",
      "resource_not_found",
      "deadline_exceeded",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
    ],
  },
] as const satisfies readonly ApiV1AnalyticsRetentionRouteDescriptor<string>[];
export const apiV1AnalyticsFunnelAnalysisRouteRegistry = [
  {
    id: "site.analytics.funnelAnalysis",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/funnel-analysis",
    operationId: "site.analytics.funnelAnalysis",
    scopes: ["analytics:read"],
    conditionalScopes: [
      {
        when: "filter.type=saved",
        scopes: ["analytics:read", "analysis:read"],
      },
    ],
    requestSchema: SiteFunnelAnalysisQueryDtoSchema,
    responseSchema: AnalyticsFunnelAnalysisResponseSchema,
    declaredErrors: [
      "validation_failed",
      "missing_scope",
      "resource_not_found",
      "data_unavailable",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
    ],
  },
] as const satisfies readonly ApiV1AnalyticsFunnelAnalysisRouteDescriptor<string>[];
export const apiV1AnalyticsGoalRouteRegistry = [
  {
    id: "site.analytics.goalSummary",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/goals/summary",
    operationId: "site.analytics.goalSummary",
    scopes: ["analytics:read"],
    conditionalScopes: [
      {
        when: "filter.type=saved",
        scopes: ["analytics:read", "analysis:read"],
      },
    ],
    requestSchema: SiteGoalSummaryQueryDtoSchema,
    responseSchema: AnalyticsGoalSummaryResponseSchema,
    declaredErrors: [
      "validation_failed",
      "missing_scope",
      "resource_not_found",
      "data_unavailable",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
    ],
  },
  {
    id: "site.analytics.goalTimeseries",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/goals/timeseries",
    operationId: "site.analytics.goalTimeseries",
    scopes: ["analytics:read"],
    conditionalScopes: [
      {
        when: "filter.type=saved",
        scopes: ["analytics:read", "analysis:read"],
      },
    ],
    requestSchema: SiteGoalTimeseriesQueryDtoSchema,
    responseSchema: AnalyticsGoalTimeseriesResponseSchema,
    declaredErrors: [
      "validation_failed",
      "missing_scope",
      "resource_not_found",
      "data_unavailable",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
    ],
  },
] as const satisfies readonly ApiV1AnalyticsGoalRouteDescriptor<string>[];
export const apiV1AnalyticsPerformanceRouteRegistry = [
  {
    id: "site.analytics.performanceSummary",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/performance/summary",
    operationId: "site.analytics.performanceSummary",
    scopes: ["analytics:read"],
    conditionalScopes: [
      {
        when: "filter.type=saved",
        scopes: ["analytics:read", "analysis:read"],
      },
    ],
    requestSchema: SitePerformanceSummaryQueryDtoSchema,
    responseSchema: AnalyticsPerformanceSummaryResponseSchema,
    declaredErrors: [
      "validation_failed",
      "missing_scope",
      "resource_not_found",
      "deadline_exceeded",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
    ],
  },
  {
    id: "site.analytics.performanceTimeseries",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/performance/timeseries",
    operationId: "site.analytics.performanceTimeseries",
    scopes: ["analytics:read"],
    conditionalScopes: [
      {
        when: "filter.type=saved",
        scopes: ["analytics:read", "analysis:read"],
      },
    ],
    requestSchema: SitePerformanceTimeseriesQueryDtoSchema,
    responseSchema: AnalyticsPerformanceTimeseriesResponseSchema,
    declaredErrors: [
      "validation_failed",
      "missing_scope",
      "resource_not_found",
      "deadline_exceeded",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
    ],
  },
  {
    id: "site.analytics.performanceBreakdown",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/performance/breakdowns/{dimension}",
    operationId: "site.analytics.performanceBreakdown",
    pathParameterSchemas: {
      dimension: SitePerformanceBreakdownDimensionSchema,
    },
    scopes: ["analytics:read"],
    conditionalScopes: [
      {
        when: "filter.type=saved",
        scopes: ["analytics:read", "analysis:read"],
      },
    ],
    requestSchema: SitePerformanceBreakdownQueryDtoSchema,
    responseSchema: AnalyticsPerformanceBreakdownResponseSchema,
    declaredErrors: [
      "validation_failed",
      "missing_scope",
      "resource_not_found",
      "deadline_exceeded",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
    ],
  },
] as const satisfies readonly ApiV1AnalyticsPerformanceRouteDescriptor<string>[];
export const apiV1AnalyticsEventsRouteRegistry = [
  {
    id: "site.analytics.eventsSummary",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/events/summary",
    operationId: "site.analytics.eventsSummary",
    scopes: ["analytics:read"],
    conditionalScopes: [
      {
        when: "filter.type=saved",
        scopes: ["analytics:read", "analysis:read"],
      },
    ],
    requestSchema: SiteEventsSummaryQueryDtoSchema,
    responseSchema: AnalyticsEventsSummaryResponseSchema,
    declaredErrors: [
      "validation_failed",
      "missing_scope",
      "resource_not_found",
      "deadline_exceeded",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
    ],
  },
  {
    id: "site.analytics.eventsTimeseries",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/events/timeseries",
    operationId: "site.analytics.eventsTimeseries",
    scopes: ["analytics:read"],
    conditionalScopes: [
      {
        when: "filter.type=saved",
        scopes: ["analytics:read", "analysis:read"],
      },
    ],
    requestSchema: SiteEventsTimeseriesQueryDtoSchema,
    responseSchema: AnalyticsEventsTimeseriesResponseSchema,
    declaredErrors: [
      "validation_failed",
      "missing_scope",
      "resource_not_found",
      "deadline_exceeded",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
    ],
  },
] as const satisfies readonly ApiV1AnalyticsEventsRouteDescriptor<string>[];
export const apiV1AnalyticsEventRecordsRouteRegistry = [
  {
    id: "site.analytics.eventsSearch",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/events/search",
    operationId: "site.analytics.eventsSearch",
    scopes: ["analytics:read"],
    conditionalScopes: [
      {
        when: "filter.type=saved",
        scopes: ["analytics:read", "analysis:read"],
      },
    ],
    requestSchema: SiteEventsSearchQueryDtoSchema,
    responseSchema: AnalyticsEventsSearchResponseSchema,
    declaredErrors: [
      "validation_failed",
      "missing_scope",
      "resource_not_found",
      "deadline_exceeded",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
    ],
  },
  {
    id: "site.analytics.eventDetail",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/events/detail",
    operationId: "site.analytics.eventDetail",
    scopes: ["analytics:read"],
    requestSchema: SiteEventDetailQueryDtoSchema,
    responseSchema: AnalyticsEventDetailResponseSchema,
    declaredErrors: [
      "validation_failed",
      "missing_scope",
      "resource_not_found",
      "deadline_exceeded",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
    ],
  },
] as const satisfies readonly ApiV1AnalyticsEventRecordsRouteDescriptor<string>[];
export const apiV1AnalyticsEventTypesRouteRegistry = [
  {
    id: "site.analytics.eventTypes",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/event-types",
    operationId: "site.analytics.eventTypes",
    scopes: ["analytics:read"],
    conditionalScopes: [
      {
        when: "filter.type=saved",
        scopes: ["analytics:read", "analysis:read"],
      },
    ],
    requestSchema: SiteEventTypesQueryDtoSchema,
    responseSchema: AnalyticsEventTypesResponseSchema,
    declaredErrors: [
      "validation_failed",
      "missing_scope",
      "resource_not_found",
      "deadline_exceeded",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
    ],
  },
  {
    id: "site.analytics.eventTypeDetail",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/event-types/detail",
    operationId: "site.analytics.eventTypeDetail",
    scopes: ["analytics:read"],
    conditionalScopes: [
      {
        when: "filter.type=saved",
        scopes: ["analytics:read", "analysis:read"],
      },
    ],
    requestSchema: SiteEventTypeDetailQueryDtoSchema,
    responseSchema: AnalyticsEventTypeDetailResponseSchema,
    declaredErrors: [
      "validation_failed",
      "missing_scope",
      "resource_not_found",
      "deadline_exceeded",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
    ],
  },
  {
    id: "site.analytics.eventFields",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/event-types/fields",
    operationId: "site.analytics.eventFields",
    scopes: ["analytics:read"],
    conditionalScopes: [
      {
        when: "filter.type=saved",
        scopes: ["analytics:read", "analysis:read"],
      },
    ],
    requestSchema: SiteEventFieldsQueryDtoSchema,
    responseSchema: AnalyticsEventFieldsResponseSchema,
    declaredErrors: [
      "validation_failed",
      "missing_scope",
      "resource_not_found",
      "deadline_exceeded",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
    ],
  },
  {
    id: "site.analytics.eventFieldValues",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/event-types/field-values",
    operationId: "site.analytics.eventFieldValues",
    scopes: ["analytics:read"],
    conditionalScopes: [
      {
        when: "filter.type=saved",
        scopes: ["analytics:read", "analysis:read"],
      },
    ],
    requestSchema: SiteEventFieldValuesQueryDtoSchema,
    responseSchema: AnalyticsEventFieldValuesResponseSchema,
    declaredErrors: [
      "validation_failed",
      "missing_scope",
      "resource_not_found",
      "deadline_exceeded",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
    ],
  },
] as const satisfies readonly ApiV1AnalyticsEventTypesRouteDescriptor<string>[];
export const apiV1AnalyticsJourneyDetailsRouteRegistry = [
  {
    id: "site.analytics.visitorDetail",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/visitors/detail",
    operationId: "site.analytics.visitorDetail",
    scopes: ["analytics:read"],
    requestSchema: SiteVisitorDetailQueryDtoSchema,
    responseSchema: AnalyticsVisitorDetailResponseSchema,
    declaredErrors: [
      "validation_failed",
      "missing_scope",
      "resource_not_found",
      "deadline_exceeded",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
    ],
  },
  {
    id: "site.analytics.sessionDetail",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/sessions/detail",
    operationId: "site.analytics.sessionDetail",
    scopes: ["analytics:read"],
    requestSchema: SiteSessionDetailQueryDtoSchema,
    responseSchema: AnalyticsSessionDetailResponseSchema,
    declaredErrors: [
      "validation_failed",
      "missing_scope",
      "resource_not_found",
      "deadline_exceeded",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
    ],
  },
  {
    id: "site.analytics.journeyEventDetail",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/journey-events/detail",
    operationId: "site.analytics.journeyEventDetail",
    scopes: ["analytics:read"],
    requestSchema: SiteJourneyEventDetailQueryDtoSchema,
    responseSchema: AnalyticsJourneyEventDetailResponseSchema,
    declaredErrors: [
      "validation_failed",
      "missing_scope",
      "resource_not_found",
      "deadline_exceeded",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
    ],
  },
] as const satisfies readonly ApiV1AnalyticsJourneyDetailsRouteDescriptor<string>[];
export const apiV1AnalyticsJourneySearchRouteRegistry = [
  {
    id: "site.analytics.visitorsSearch",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/visitors/search",
    operationId: "site.analytics.visitorsSearch",
    scopes: ["analytics:read"],
    conditionalScopes: [
      {
        when: "filter.type=saved",
        scopes: ["analytics:read", "analysis:read"],
      },
    ],
    requestSchema: SiteVisitorsSearchQueryDtoSchema,
    responseSchema: AnalyticsVisitorsSearchResponseSchema,
    declaredErrors: [
      "validation_failed",
      "invalid_cursor",
      "missing_scope",
      "resource_not_found",
      "deadline_exceeded",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
    ],
  },
  {
    id: "site.analytics.sessionsSearch",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/sessions/search",
    operationId: "site.analytics.sessionsSearch",
    scopes: ["analytics:read"],
    conditionalScopes: [
      {
        when: "filter.type=saved",
        scopes: ["analytics:read", "analysis:read"],
      },
    ],
    requestSchema: SiteSessionsSearchQueryDtoSchema,
    responseSchema: AnalyticsSessionsSearchResponseSchema,
    declaredErrors: [
      "validation_failed",
      "invalid_cursor",
      "missing_scope",
      "resource_not_found",
      "deadline_exceeded",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
    ],
  },
] as const satisfies readonly ApiV1AnalyticsJourneySearchRouteDescriptor<string>[];
export const apiV1AnalyticsJourneyTrajectoryRouteRegistry = [
  {
    id: "site.analytics.visitorEvents",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/visitors/events",
    operationId: "site.analytics.visitorEvents",
    scopes: ["analytics:read"],
    conditionalScopes: [
      {
        when: "filter.type=saved",
        scopes: ["analytics:read", "analysis:read"],
      },
    ],
    requestSchema: SiteVisitorEventsQueryDtoSchema,
    responseSchema: AnalyticsJourneyEventsResponseSchema,
    declaredErrors: [
      "validation_failed",
      "invalid_cursor",
      "missing_scope",
      "resource_not_found",
      "deadline_exceeded",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
    ],
  },
  {
    id: "site.analytics.visitorSessions",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/visitors/sessions",
    operationId: "site.analytics.visitorSessions",
    scopes: ["analytics:read"],
    conditionalScopes: [
      {
        when: "filter.type=saved",
        scopes: ["analytics:read", "analysis:read"],
      },
    ],
    requestSchema: SiteVisitorSessionsQueryDtoSchema,
    responseSchema: AnalyticsJourneySessionsResponseSchema,
    declaredErrors: [
      "validation_failed",
      "invalid_cursor",
      "missing_scope",
      "resource_not_found",
      "deadline_exceeded",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
    ],
  },
  {
    id: "site.analytics.sessionEvents",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/sessions/events",
    operationId: "site.analytics.sessionEvents",
    scopes: ["analytics:read"],
    conditionalScopes: [
      {
        when: "filter.type=saved",
        scopes: ["analytics:read", "analysis:read"],
      },
    ],
    requestSchema: SiteSessionEventsQueryDtoSchema,
    responseSchema: AnalyticsJourneyEventsResponseSchema,
    declaredErrors: [
      "validation_failed",
      "invalid_cursor",
      "missing_scope",
      "resource_not_found",
      "deadline_exceeded",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
    ],
  },
] as const satisfies readonly ApiV1AnalyticsJourneyTrajectoryRouteDescriptor<string>[];
export const apiV1AnalyticsRealtimeRouteRegistry = [
  {
    id: "site.analytics.realtimeSnapshot",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/realtime/snapshot",
    operationId: "site.analytics.realtimeSnapshot",
    scopes: ["analytics:read"],
    requestSchema: SiteRealtimeSnapshotQueryDtoSchema,
    responseSchema: AnalyticsRealtimeSnapshotResponseSchema,
    declaredErrors: [
      "validation_failed",
      "missing_scope",
      "deadline_exceeded",
      "data_unavailable",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
    ],
  },
  {
    id: "site.analytics.realtimeActiveVisitors",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/realtime/active-visitors",
    operationId: "site.analytics.realtimeActiveVisitors",
    scopes: ["analytics:read"],
    requestSchema: SiteRealtimeActiveVisitorsQueryDtoSchema,
    responseSchema: AnalyticsRealtimeActiveVisitorsResponseSchema,
    declaredErrors: [
      "validation_failed",
      "missing_scope",
      "deadline_exceeded",
      "data_unavailable",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
    ],
  },
  {
    id: "site.analytics.realtimeEvents",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/realtime/events",
    operationId: "site.analytics.realtimeEvents",
    scopes: ["analytics:read"],
    requestSchema: SiteRealtimeEventsQueryDtoSchema,
    responseSchema: AnalyticsRealtimeEventsResponseSchema,
    declaredErrors: [
      "validation_failed",
      "missing_scope",
      "deadline_exceeded",
      "data_unavailable",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
    ],
  },
  {
    id: "site.analytics.realtimeSessions",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/realtime/sessions",
    operationId: "site.analytics.realtimeSessions",
    scopes: ["analytics:read"],
    requestSchema: SiteRealtimeSessionsQueryDtoSchema,
    responseSchema: AnalyticsRealtimeSessionsResponseSchema,
    declaredErrors: [
      "validation_failed",
      "missing_scope",
      "deadline_exceeded",
      "data_unavailable",
      "internal_error",
      "method_not_allowed",
      "not_acceptable",
      "unsupported_media_type",
    ],
  },
] as const satisfies readonly ApiV1AnalyticsRealtimeRouteDescriptor<string>[];
/** Read-only saved-filter resources. These remain planned until rollout evidence is complete. */
export const apiV1ApplicationRouteRegistry = [
  applicationRoute({
    id: "sites.list",
    lifecycle: "exposed",
    method: "GET",
    path: "/api/v1/sites",
    operationId: "sites.list",
    scopes: ["site:read"],
    requestSchema: ListSitesInputSchema,
    responseSchema: SiteResourcePageSchema,
    declaredErrors: ["missing_scope", "invalid_cursor", "internal_error"],
  }),
  applicationRoute({
    id: "sites.create",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/sites",
    operationId: "sites.create",
    scopes: ["site:write"],
    requestSchema: CreateSiteInputSchema,
    responseSchema: SiteResourceSchema,
    declaredErrors: [
      "validation_failed",
      "payload_too_large",
      "missing_scope",
      "conflict",
      "unsupported_media_type",
      "not_acceptable",
      "internal_error",
    ],
  }),
  applicationRoute({
    id: "sites.get",
    lifecycle: "exposed",
    method: "GET",
    path: "/api/v1/sites/{siteId}",
    operationId: "sites.get",
    scopes: ["site:read"],
    requestSchema: GetSiteInputSchema,
    responseSchema: SiteResourceSchema,
    declaredErrors: ["missing_scope", "resource_not_found", "internal_error"],
  }),
  applicationRoute({
    id: "sites.update",
    lifecycle: "exposed",
    method: "PATCH",
    path: "/api/v1/sites/{siteId}",
    operationId: "sites.update",
    scopes: ["site:write"],
    requestSchema: UpdateSiteInputSchema,
    responseSchema: SiteResourceSchema,
    declaredErrors: [
      "validation_failed",
      "payload_too_large",
      "missing_scope",
      "resource_not_found",
      "conflict",
      "unsupported_media_type",
      "not_acceptable",
      "internal_error",
    ],
  }),
  applicationRoute({
    id: "sites.delete",
    lifecycle: "exposed",
    method: "DELETE",
    path: "/api/v1/sites/{siteId}",
    operationId: "sites.delete",
    scopes: ["site:write"],
    requestSchema: DeleteSiteInputSchema,
    responseSchema: z.undefined(),
    declaredErrors: ["missing_scope", "resource_not_found", "internal_error"],
  }),
  applicationRoute({
    id: "settings.tracking.get",
    lifecycle: "exposed",
    method: "GET",
    path: "/api/v1/sites/{siteId}/settings/tracking",
    operationId: "settings.tracking.get",
    scopes: ["site_config:read"],
    requestSchema: SiteSettingsInputSchema,
    responseSchema: TrackingSettingsSchema,
    declaredErrors: ["missing_scope", "resource_not_found", "internal_error"],
  }),
  applicationRoute({
    id: "settings.tracking.update",
    lifecycle: "exposed",
    method: "PATCH",
    path: "/api/v1/sites/{siteId}/settings/tracking",
    operationId: "settings.tracking.update",
    scopes: ["site_config:write"],
    requestSchema: UpdateTrackingSettingsInputSchema,
    responseSchema: TrackingSettingsSchema,
    declaredErrors: [
      "validation_failed",
      "payload_too_large",
      "missing_scope",
      "resource_not_found",
      "unsupported_media_type",
      "not_acceptable",
      "internal_error",
    ],
  }),
  applicationRoute({
    id: "settings.privacy.get",
    lifecycle: "exposed",
    method: "GET",
    path: "/api/v1/sites/{siteId}/settings/privacy",
    operationId: "settings.privacy.get",
    scopes: ["site_config:read"],
    requestSchema: SiteSettingsInputSchema,
    responseSchema: PrivacySettingsSchema,
    declaredErrors: ["missing_scope", "resource_not_found", "internal_error"],
  }),
  applicationRoute({
    id: "settings.privacy.update",
    lifecycle: "exposed",
    method: "PATCH",
    path: "/api/v1/sites/{siteId}/settings/privacy",
    operationId: "settings.privacy.update",
    scopes: ["site_config:write"],
    requestSchema: UpdatePrivacySettingsInputSchema,
    responseSchema: PrivacySettingsSchema,
    declaredErrors: [
      "validation_failed",
      "payload_too_large",
      "missing_scope",
      "resource_not_found",
      "unsupported_media_type",
      "not_acceptable",
      "internal_error",
    ],
  }),
  applicationRoute({
    id: "settings.sharing.get",
    lifecycle: "exposed",
    method: "GET",
    path: "/api/v1/sites/{siteId}/settings/sharing",
    operationId: "settings.sharing.get",
    scopes: ["site_config:read"],
    requestSchema: SiteSettingsInputSchema,
    responseSchema: SharingSettingsSchema,
    declaredErrors: ["missing_scope", "resource_not_found", "internal_error"],
  }),
  applicationRoute({
    id: "settings.sharing.update",
    lifecycle: "exposed",
    method: "PATCH",
    path: "/api/v1/sites/{siteId}/settings/sharing",
    operationId: "settings.sharing.update",
    scopes: ["site_config:write"],
    requestSchema: UpdateSharingSettingsInputSchema,
    responseSchema: SharingSettingsSchema,
    declaredErrors: [
      "validation_failed",
      "payload_too_large",
      "missing_scope",
      "resource_not_found",
      "conflict",
      "unsupported_media_type",
      "not_acceptable",
      "internal_error",
    ],
  }),
  applicationRoute({
    id: "settings.tracking-script.get",
    lifecycle: "exposed",
    method: "GET",
    path: "/api/v1/sites/{siteId}/settings/tracking-script",
    operationId: "settings.trackingScript.get",
    scopes: ["site_config:read"],
    requestSchema: SiteSettingsInputSchema,
    responseSchema: TrackingScriptSchema,
    declaredErrors: ["missing_scope", "resource_not_found", "internal_error"],
  }),
  applicationRoute({
    id: "funnels.list",
    lifecycle: "exposed",
    method: "GET",
    path: "/api/v1/sites/{siteId}/funnels",
    operationId: "funnels.list",
    scopes: ["analysis:read"],
    requestSchema: ListFunnelsInputSchema,
    responseSchema: FunnelResourcePageSchema,
    declaredErrors: [
      "missing_scope",
      "resource_not_found",
      "invalid_cursor",
      "internal_error",
    ],
  }),
  applicationRoute({
    id: "funnels.create",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/sites/{siteId}/funnels",
    operationId: "funnels.create",
    scopes: ["analysis:write"],
    requestSchema: CreateFunnelInputSchema,
    responseSchema: FunnelResourceSchema,
    declaredErrors: [
      "validation_failed",
      "payload_too_large",
      "missing_scope",
      "resource_not_found",
      "unsupported_media_type",
      "not_acceptable",
      "internal_error",
    ],
  }),
  applicationRoute({
    id: "funnels.get",
    lifecycle: "exposed",
    method: "GET",
    path: "/api/v1/sites/{siteId}/funnels/{funnelId}",
    operationId: "funnels.get",
    scopes: ["analysis:read"],
    requestSchema: GetFunnelInputSchema,
    responseSchema: FunnelResourceSchema,
    declaredErrors: ["missing_scope", "resource_not_found", "internal_error"],
  }),
  applicationRoute({
    id: "funnels.update",
    lifecycle: "exposed",
    method: "PATCH",
    path: "/api/v1/sites/{siteId}/funnels/{funnelId}",
    operationId: "funnels.update",
    scopes: ["analysis:write"],
    requestSchema: UpdateFunnelInputSchema,
    responseSchema: FunnelResourceSchema,
    declaredErrors: [
      "validation_failed",
      "payload_too_large",
      "missing_scope",
      "resource_not_found",
      "unsupported_media_type",
      "not_acceptable",
      "internal_error",
    ],
  }),
  applicationRoute({
    id: "funnels.delete",
    lifecycle: "exposed",
    method: "DELETE",
    path: "/api/v1/sites/{siteId}/funnels/{funnelId}",
    operationId: "funnels.delete",
    scopes: ["analysis:write"],
    requestSchema: GetFunnelInputSchema,
    responseSchema: z.undefined(),
    declaredErrors: ["missing_scope", "resource_not_found", "internal_error"],
  }),
  applicationRoute({
    id: "goals.list",
    lifecycle: "exposed",
    method: "GET",
    path: "/api/v1/sites/{siteId}/goals",
    operationId: "goals.list",
    scopes: ["analysis:read"],
    requestSchema: ListGoalsInputSchema,
    responseSchema: GoalResourcePageSchema,
    declaredErrors: [
      "missing_scope",
      "resource_not_found",
      "invalid_cursor",
      "internal_error",
    ],
  }),
  applicationRoute({
    id: "goals.create",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/sites/{siteId}/goals",
    operationId: "goals.create",
    scopes: ["analysis:write"],
    requestSchema: CreateGoalInputSchema,
    responseSchema: GoalResourceSchema,
    declaredErrors: [
      "validation_failed",
      "payload_too_large",
      "missing_scope",
      "resource_not_found",
      "unsupported_media_type",
      "not_acceptable",
      "internal_error",
    ],
  }),
  applicationRoute({
    id: "goals.get",
    lifecycle: "exposed",
    method: "GET",
    path: "/api/v1/sites/{siteId}/goals/{goalId}",
    operationId: "goals.get",
    scopes: ["analysis:read"],
    requestSchema: GetGoalInputSchema,
    responseSchema: GoalResourceSchema,
    declaredErrors: ["missing_scope", "resource_not_found", "internal_error"],
  }),
  applicationRoute({
    id: "goals.update",
    lifecycle: "exposed",
    method: "PATCH",
    path: "/api/v1/sites/{siteId}/goals/{goalId}",
    operationId: "goals.update",
    scopes: ["analysis:write"],
    requestSchema: UpdateGoalInputSchema,
    responseSchema: GoalResourceSchema,
    declaredErrors: [
      "validation_failed",
      "payload_too_large",
      "missing_scope",
      "resource_not_found",
      "unsupported_media_type",
      "not_acceptable",
      "internal_error",
    ],
  }),
  applicationRoute({
    id: "goals.delete",
    lifecycle: "exposed",
    method: "DELETE",
    path: "/api/v1/sites/{siteId}/goals/{goalId}",
    operationId: "goals.delete",
    scopes: ["analysis:write"],
    requestSchema: GetGoalInputSchema,
    responseSchema: z.undefined(),
    declaredErrors: ["missing_scope", "resource_not_found", "internal_error"],
  }),
  applicationRoute({
    id: "site.saved-filters.list",
    lifecycle: "exposed",
    method: "GET",
    path: "/api/v1/sites/{siteId}/saved-filters",
    operationId: "savedFilters.list",
    scopes: ["analysis:read"],
    requestSchema: ListTeamVisibleSavedFiltersInputSchema,
    responseSchema: SavedFilterPageSchema,
    declaredErrors: [
      "missing_scope",
      "resource_not_found",
      "invalid_cursor",
      "internal_error",
    ],
  }),
  applicationRoute({
    id: "site.saved-filters.get",
    lifecycle: "exposed",
    method: "GET",
    path: "/api/v1/sites/{siteId}/saved-filters/{savedFilterId}",
    operationId: "savedFilters.get",
    scopes: ["analysis:read"],
    requestSchema: GetTeamVisibleSavedFilterInputSchema,
    responseSchema: SavedFilterDefinitionSchema,
    declaredErrors: [
      "missing_scope",
      "resource_not_found",
      "invalid_cursor",
      "internal_error",
    ],
  }),
] as const;
export const apiV1BatchRouteRegistry = [
  {
    id: "batch",
    lifecycle: "exposed",
    method: "POST",
    path: "/api/v1/batch",
    scopes: ["analytics:read"],
    requestSchema: TypedBatchRequestSchema,
    responseSchema: TypedBatchResponseSchema,
    declaredErrors: [
      "validation_failed",
      "invalid_json",
      "payload_too_large",
      "unsupported_media_type",
      "batch_child_not_allowed",
      "deadline_exceeded",
      "internal_error",
    ],
  },
] as const satisfies readonly ApiV1BatchRouteDescriptor[];
/**
 * Explicit allow-list for typed batch children. Keep this list independent of
 * route naming conventions so the runtime and generated OpenAPI contract
 * cannot silently disagree when a new route is added.
 */
export const apiV1BatchEligibleRouteIds = [
  "site.analytics.overview",
  "team.analytics.overview",
  "site.analytics.comparison",
  "site.analytics.comparisonBreakdown",
  "team.analytics.comparison",
  "team.analytics.comparisonBreakdown",
  "site.analytics.schema",
  "team.analytics.schema",
  "site.analytics.timeseries",
  "team.analytics.timeseries",
  "team.analytics.sites",
  "site.analytics.breakdown",
  "team.analytics.breakdown",
  "site.analytics.crossBreakdown",
  "site.analytics.pages",
  "site.analytics.referrers",
  "site.analytics.channels",
  "site.analytics.filterValues",
  "site.analytics.retentionCohorts",
  "site.analytics.funnelAnalysis",
  "site.analytics.performanceSummary",
  "site.analytics.performanceTimeseries",
  "site.analytics.performanceBreakdown",
  "site.analytics.eventsSummary",
  "site.analytics.eventsTimeseries",
  "site.analytics.eventsSearch",
  "site.analytics.eventDetail",
  "site.analytics.journeyEventDetail",
  "site.analytics.eventTypes",
  "site.analytics.eventTypeDetail",
  "site.analytics.eventFields",
  "site.analytics.eventFieldValues",
  "site.analytics.visitorDetail",
  "site.analytics.sessionDetail",
  "site.analytics.visitorsSearch",
  "site.analytics.sessionsSearch",
  "site.analytics.visitorEvents",
  "site.analytics.visitorSessions",
  "site.analytics.sessionEvents",
  "site.analytics.realtimeSnapshot",
  "site.analytics.realtimeActiveVisitors",
  "site.analytics.realtimeEvents",
  "site.analytics.realtimeSessions",
  "site.saved-filters.list",
  "site.saved-filters.get",
] as const;
export const apiV1RouteRegistry = [
  ...apiV1AnalyticsRouteRegistry,
  ...apiV1CoreRouteRegistry,
  ...apiV1AnalyticsComparisonRouteRegistry,
  ...apiV1AnalyticsSchemaRouteRegistry,
  ...apiV1AnalyticsTimeseriesRouteRegistry,
  ...apiV1AnalyticsTeamSitesRouteRegistry,
  ...apiV1AnalyticsBreakdownRouteRegistry,
  ...apiV1AnalyticsTeamBreakdownRouteRegistry,
  ...apiV1AnalyticsCrossBreakdownRouteRegistry,
  ...apiV1AnalyticsListRouteRegistry,
  ...apiV1AnalyticsFilterValuesRouteRegistry,
  ...apiV1AnalyticsRetentionRouteRegistry,
  ...apiV1AnalyticsFunnelAnalysisRouteRegistry,
  ...apiV1AnalyticsGoalRouteRegistry,
  ...apiV1AnalyticsPerformanceRouteRegistry,
  ...apiV1AnalyticsEventsRouteRegistry,
  ...apiV1AnalyticsEventRecordsRouteRegistry,
  ...apiV1AnalyticsEventTypesRouteRegistry,
  ...apiV1AnalyticsJourneyDetailsRouteRegistry,
  ...apiV1AnalyticsJourneySearchRouteRegistry,
  ...apiV1AnalyticsJourneyTrajectoryRouteRegistry,
  ...apiV1AnalyticsRealtimeRouteRegistry,
  ...apiV1ApplicationRouteRegistry,
  ...apiV1BatchRouteRegistry,
] as const;
/** Stable rollout keys are derived from semantic route variants, never paths. */

/**
 * The canonical non-batch graph. Batch is deliberately kept as a separate
 * descriptor so consumers cannot accidentally enqueue another batch request or
 * make the batch registry recursive.
 */
export const apiV1NonBatchRouteRegistry = apiV1RouteRegistry.filter(
  (route) => route.id !== "batch",
);
