import type { DemoSiteProfile } from "./demo-site-profiles-types";

export const DEMO_SITE_PROFILES_PART_1: DemoSiteProfile[] = [
  {
    id: "demo-site-001",
    teamId: "demo-team-001",
    name: "Corporate Website",
    domain: "acme-corp.com",
    iconPath: "/images/demo-sites/corporate.svg",
    dailyPvRange: [8200, 14500],
    bounceRateRange: [0.38, 0.52],
    avgDurationMsRange: [45000, 95000],
    topCountries: [
      { code: "US", weight: 0.35 },
      { code: "GB", weight: 0.15 },
      { code: "DE", weight: 0.12 },
      { code: "CA", weight: 0.1 },
      { code: "AU", weight: 0.08 },
      { code: "FR", weight: 0.06 },
      { code: "JP", weight: 0.04 },
      { code: "IN", weight: 0.03 },
      { code: "BR", weight: 0.03 },
      { code: "NL", weight: 0.02 },
      { code: "SG", weight: 0.02 },
    ],
    topReferrers: [
      { name: "google.com", weight: 0.4 },
      { name: "(direct)", weight: 0.25 },
      { name: "linkedin.com", weight: 0.12 },
      { name: "twitter.com", weight: 0.08 },
      { name: "bing.com", weight: 0.05 },
      { name: "facebook.com", weight: 0.04 },
      { name: "baidu.com", weight: 0.03 },
      { name: "reddit.com", weight: 0.03 },
    ],
    paths: [
      "/",
      "/about",
      "/products",
      "/pricing",
      "/careers",
      "/contact",
      "/blog",
      "/blog/company-update",
      "/solutions",
      "/partners",
    ],
    titles: [
      "Home",
      "About Us",
      "Products",
      "Pricing",
      "Careers",
      "Contact",
      "Blog",
      "Company Update",
      "Solutions",
      "Partners",
    ],
    deviceWeights: { Desktop: 0.68, Mobile: 0.27, Tablet: 0.05 },
    weekendFactor: 0.35,
    eventNames: [
      "cta_click",
      "demo_request",
      "newsletter_signup",
      "pdf_download",
      "contact_form",
    ],
    hourProfile: { riseHour: 10, activeWidth: 12, baseLevel: 0.12 },
    visitorReturnRate: 0.18,
  },
  {
    id: "demo-site-002",
    teamId: "demo-team-001",
    name: "E-Commerce Store",
    domain: "shopwave.store",
    iconPath: "/images/demo-sites/commerce.svg",
    dailyPvRange: [12000, 22000],
    bounceRateRange: [0.28, 0.42],
    avgDurationMsRange: [120000, 240000],
    topCountries: [
      { code: "US", weight: 0.3 },
      { code: "CN", weight: 0.15 },
      { code: "DE", weight: 0.1 },
      { code: "GB", weight: 0.1 },
      { code: "JP", weight: 0.08 },
      { code: "FR", weight: 0.06 },
      { code: "KR", weight: 0.05 },
      { code: "AU", weight: 0.04 },
      { code: "CA", weight: 0.04 },
      { code: "BR", weight: 0.04 },
      { code: "IN", weight: 0.03 },
      { code: "IT", weight: 0.01 },
    ],
    topReferrers: [
      { name: "google.com", weight: 0.35 },
      { name: "(direct)", weight: 0.2 },
      { name: "instagram.com", weight: 0.12 },
      { name: "facebook.com", weight: 0.1 },
      { name: "pinterest.com", weight: 0.07 },
      { name: "twitter.com", weight: 0.05 },
      { name: "youtube.com", weight: 0.04 },
      { name: "tiktok.com", weight: 0.04 },
      { name: "bing.com", weight: 0.03 },
    ],
    paths: [
      "/",
      "/collections",
      "/collections/new-arrivals",
      "/products/wireless-headphones",
      "/products/smart-watch",
      "/cart",
      "/checkout",
      "/account",
      "/sale",
      "/products/laptop-stand",
      "/wishlist",
      "/returns",
    ],
    titles: [
      "Shop Home",
      "Collections",
      "New Arrivals",
      "Wireless Headphones",
      "Smart Watch",
      "Cart",
      "Checkout",
      "My Account",
      "Sale",
      "Laptop Stand",
      "Wishlist",
      "Returns",
    ],
    deviceWeights: { Desktop: 0.42, Mobile: 0.52, Tablet: 0.06 },
    weekendFactor: 1.25,
    eventNames: [
      "add_to_cart",
      "purchase",
      "wishlist_add",
      "product_view",
      "checkout_start",
      "coupon_apply",
      "review_submit",
    ],
    hourProfile: { riseHour: 5, activeWidth: 17, baseLevel: 0.22 },
    visitorReturnRate: 0.22,
  },
  {
    id: "demo-site-003",
    teamId: "demo-team-001",
    name: "News Portal",
    domain: "dailypulse.news",
    iconPath: "/images/demo-sites/news.svg",
    dailyPvRange: [18000, 35000],
    bounceRateRange: [0.55, 0.72],
    avgDurationMsRange: [30000, 70000],
    topCountries: [
      { code: "US", weight: 0.4 },
      { code: "GB", weight: 0.18 },
      { code: "CA", weight: 0.1 },
      { code: "AU", weight: 0.08 },
      { code: "IN", weight: 0.06 },
      { code: "DE", weight: 0.04 },
      { code: "IE", weight: 0.03 },
      { code: "NZ", weight: 0.03 },
      { code: "SG", weight: 0.02 },
      { code: "ZA", weight: 0.02 },
      { code: "PH", weight: 0.02 },
      { code: "NG", weight: 0.02 },
    ],
    topReferrers: [
      { name: "google.com", weight: 0.3 },
      { name: "(direct)", weight: 0.15 },
      { name: "news.google.com", weight: 0.15 },
      { name: "twitter.com", weight: 0.12 },
      { name: "facebook.com", weight: 0.1 },
      { name: "reddit.com", weight: 0.06 },
      { name: "apple.news", weight: 0.05 },
      { name: "flipboard.com", weight: 0.04 },
      { name: "bing.com", weight: 0.03 },
    ],
    paths: [
      "/",
      "/politics",
      "/tech",
      "/world",
      "/business",
      "/sports",
      "/culture",
      "/opinion",
      "/science",
      "/health",
    ],
    titles: [
      "Breaking News",
      "Politics",
      "Tech",
      "World",
      "Business",
      "Sports",
      "Culture",
      "Opinion",
      "Science",
      "Health",
    ],
    deviceWeights: { Desktop: 0.35, Mobile: 0.6, Tablet: 0.05 },
    weekendFactor: 0.9,
    eventNames: [
      "article_read",
      "share_click",
      "newsletter_subscribe",
      "comment_post",
      "bookmark",
    ],
    hourProfile: { riseHour: 6, activeWidth: 17, baseLevel: 0.25 },
    visitorReturnRate: 0.3,
  },
  {
    id: "demo-site-004",
    teamId: "demo-team-001",
    name: "Marketing Landing",
    domain: "launch.brightpath.co",
    iconPath: "/images/demo-sites/launch.svg",
    dailyPvRange: [3500, 7200],
    bounceRateRange: [0.62, 0.78],
    avgDurationMsRange: [15000, 40000],
    topCountries: [
      { code: "US", weight: 0.5 },
      { code: "CA", weight: 0.12 },
      { code: "GB", weight: 0.1 },
      { code: "AU", weight: 0.08 },
      { code: "DE", weight: 0.05 },
      { code: "FR", weight: 0.04 },
      { code: "NL", weight: 0.03 },
      { code: "IN", weight: 0.03 },
      { code: "BR", weight: 0.03 },
      { code: "SG", weight: 0.02 },
    ],
    topReferrers: [
      { name: "google.com", weight: 0.25 },
      { name: "facebook.com", weight: 0.2 },
      { name: "instagram.com", weight: 0.15 },
      { name: "(direct)", weight: 0.12 },
      { name: "twitter.com", weight: 0.1 },
      { name: "linkedin.com", weight: 0.08 },
      { name: "producthunt.com", weight: 0.05 },
      { name: "tiktok.com", weight: 0.05 },
    ],
    paths: [
      "/",
      "/features",
      "/pricing",
      "/testimonials",
      "/faq",
      "/get-started",
    ],
    titles: [
      "BrightPath — Launch Faster",
      "Features",
      "Pricing",
      "Testimonials",
      "FAQ",
      "Get Started",
    ],
    deviceWeights: { Desktop: 0.48, Mobile: 0.47, Tablet: 0.05 },
    weekendFactor: 0.55,
    eventNames: [
      "signup_click",
      "video_play",
      "pricing_view",
      "testimonial_scroll",
      "cta_click",
    ],
    hourProfile: { riseHour: 12, activeWidth: 9, baseLevel: 0.06 },
    visitorReturnRate: 0.05,
  },
];
