// ---------------------------------------------------------------------------
//  Demo site profiles
// ---------------------------------------------------------------------------

export interface DemoSiteHourProfile {
  /** UTC hour when traffic begins rising (0–23). May cause midnight wrap if riseHour + activeWidth > 24. */
  riseHour: number;
  /** Duration in hours of the active (sine) window */
  activeWidth: number;
  /** Baseline traffic level outside the active window (0–1). Higher = flatter curve. */
  baseLevel: number;
}

export interface DemoSiteProfile {
  id: string;
  teamId: string;
  name: string;
  domain: string;
  dailyPvRange: [number, number];
  bounceRateRange: [number, number];
  avgDurationMsRange: [number, number];
  topCountries: Array<{ code: string; weight: number }>;
  topReferrers: Array<{ name: string; weight: number }>;
  paths: string[];
  titles: string[];
  deviceWeights: { Desktop: number; Mobile: number; Tablet: number };
  weekendFactor: number;
  eventNames: string[];
  hourProfile: DemoSiteHourProfile;
  /**
   * Share of a visit window's visitors drawn from the "returning" head of the
   * site's visitor universe (0–1). High = sticky audience (forum / SaaS),
   * low = drive-by traffic (marketing page / portfolio). Defaults to 0.25.
   */
  visitorReturnRate?: number;
  /**
   * Optional override for the path Markov transition graph. When omitted the
   * graph is derived from `paths` order — first path is the entry node, each
   * subsequent path carries a slightly lower forward weight.
   */
  pathFlow?: Record<string, Array<{ to: string; weight: number }>>;
}

export const DEMO_TEAMS = [
  {
    id: "demo-team-001",
    name: "XEOOS Team",
    slug: "xeoos-team",
    ownerUserId: "demo-user-001",
  },
] as const;

export const DEMO_SITE_PROFILES: DemoSiteProfile[] = [
  {
    id: "demo-site-001",
    teamId: "demo-team-001",
    name: "Corporate Website",
    domain: "acme-corp.com",
    dailyPvRange: [8200, 14500],
    bounceRateRange: [0.38, 0.52],
    avgDurationMsRange: [45000, 95000],
    topCountries: [
      { code: "US", weight: 0.35 },
      { code: "GB", weight: 0.15 },
      { code: "DE", weight: 0.12 },
      { code: "CA", weight: 0.1 },
      { code: "AU", weight: 0.08 },
      { code: "FR", weight: 0.06 },
      { code: "JP", weight: 0.04 },
      { code: "IN", weight: 0.03 },
      { code: "BR", weight: 0.03 },
      { code: "NL", weight: 0.02 },
      { code: "SG", weight: 0.02 },
    ],
    topReferrers: [
      { name: "google.com", weight: 0.4 },
      { name: "(direct)", weight: 0.25 },
      { name: "linkedin.com", weight: 0.12 },
      { name: "twitter.com", weight: 0.08 },
      { name: "bing.com", weight: 0.05 },
      { name: "facebook.com", weight: 0.04 },
      { name: "baidu.com", weight: 0.03 },
      { name: "reddit.com", weight: 0.03 },
    ],
    paths: [
      "/",
      "/about",
      "/products",
      "/pricing",
      "/careers",
      "/contact",
      "/blog",
      "/blog/company-update",
      "/solutions",
      "/partners",
    ],
    titles: [
      "Home",
      "About Us",
      "Products",
      "Pricing",
      "Careers",
      "Contact",
      "Blog",
      "Company Update",
      "Solutions",
      "Partners",
    ],
    deviceWeights: { Desktop: 0.68, Mobile: 0.27, Tablet: 0.05 },
    weekendFactor: 0.35,
    eventNames: [
      "cta_click",
      "demo_request",
      "newsletter_signup",
      "pdf_download",
      "contact_form",
    ],
    hourProfile: { riseHour: 10, activeWidth: 12, baseLevel: 0.12 },
    visitorReturnRate: 0.18,
  },
  {
    id: "demo-site-002",
    teamId: "demo-team-001",
    name: "E-Commerce Store",
    domain: "shopwave.store",
    dailyPvRange: [12000, 22000],
    bounceRateRange: [0.28, 0.42],
    avgDurationMsRange: [120000, 240000],
    topCountries: [
      { code: "US", weight: 0.3 },
      { code: "CN", weight: 0.15 },
      { code: "DE", weight: 0.1 },
      { code: "GB", weight: 0.1 },
      { code: "JP", weight: 0.08 },
      { code: "FR", weight: 0.06 },
      { code: "KR", weight: 0.05 },
      { code: "AU", weight: 0.04 },
      { code: "CA", weight: 0.04 },
      { code: "BR", weight: 0.04 },
      { code: "IN", weight: 0.03 },
      { code: "IT", weight: 0.01 },
    ],
    topReferrers: [
      { name: "google.com", weight: 0.35 },
      { name: "(direct)", weight: 0.2 },
      { name: "instagram.com", weight: 0.12 },
      { name: "facebook.com", weight: 0.1 },
      { name: "pinterest.com", weight: 0.07 },
      { name: "twitter.com", weight: 0.05 },
      { name: "youtube.com", weight: 0.04 },
      { name: "tiktok.com", weight: 0.04 },
      { name: "bing.com", weight: 0.03 },
    ],
    paths: [
      "/",
      "/collections",
      "/collections/new-arrivals",
      "/products/wireless-headphones",
      "/products/smart-watch",
      "/cart",
      "/checkout",
      "/account",
      "/sale",
      "/products/laptop-stand",
      "/wishlist",
      "/returns",
    ],
    titles: [
      "Shop Home",
      "Collections",
      "New Arrivals",
      "Wireless Headphones",
      "Smart Watch",
      "Cart",
      "Checkout",
      "My Account",
      "Sale",
      "Laptop Stand",
      "Wishlist",
      "Returns",
    ],
    deviceWeights: { Desktop: 0.42, Mobile: 0.52, Tablet: 0.06 },
    weekendFactor: 1.25,
    eventNames: [
      "add_to_cart",
      "purchase",
      "wishlist_add",
      "product_view",
      "checkout_start",
      "coupon_apply",
      "review_submit",
    ],
    hourProfile: { riseHour: 5, activeWidth: 17, baseLevel: 0.22 },
    visitorReturnRate: 0.22,
  },
  {
    id: "demo-site-003",
    teamId: "demo-team-001",
    name: "News Portal",
    domain: "dailypulse.news",
    dailyPvRange: [18000, 35000],
    bounceRateRange: [0.55, 0.72],
    avgDurationMsRange: [30000, 70000],
    topCountries: [
      { code: "US", weight: 0.4 },
      { code: "GB", weight: 0.18 },
      { code: "CA", weight: 0.1 },
      { code: "AU", weight: 0.08 },
      { code: "IN", weight: 0.06 },
      { code: "DE", weight: 0.04 },
      { code: "IE", weight: 0.03 },
      { code: "NZ", weight: 0.03 },
      { code: "SG", weight: 0.02 },
      { code: "ZA", weight: 0.02 },
      { code: "PH", weight: 0.02 },
      { code: "NG", weight: 0.02 },
    ],
    topReferrers: [
      { name: "google.com", weight: 0.3 },
      { name: "(direct)", weight: 0.15 },
      { name: "news.google.com", weight: 0.15 },
      { name: "twitter.com", weight: 0.12 },
      { name: "facebook.com", weight: 0.1 },
      { name: "reddit.com", weight: 0.06 },
      { name: "apple.news", weight: 0.05 },
      { name: "flipboard.com", weight: 0.04 },
      { name: "bing.com", weight: 0.03 },
    ],
    paths: [
      "/",
      "/politics",
      "/tech",
      "/world",
      "/business",
      "/sports",
      "/culture",
      "/opinion",
      "/science",
      "/health",
    ],
    titles: [
      "Breaking News",
      "Politics",
      "Tech",
      "World",
      "Business",
      "Sports",
      "Culture",
      "Opinion",
      "Science",
      "Health",
    ],
    deviceWeights: { Desktop: 0.35, Mobile: 0.6, Tablet: 0.05 },
    weekendFactor: 0.9,
    eventNames: [
      "article_read",
      "share_click",
      "newsletter_subscribe",
      "comment_post",
      "bookmark",
    ],
    hourProfile: { riseHour: 6, activeWidth: 17, baseLevel: 0.25 },
    visitorReturnRate: 0.3,
  },
  {
    id: "demo-site-004",
    teamId: "demo-team-001",
    name: "Marketing Landing",
    domain: "launch.brightpath.co",
    dailyPvRange: [3500, 7200],
    bounceRateRange: [0.62, 0.78],
    avgDurationMsRange: [15000, 40000],
    topCountries: [
      { code: "US", weight: 0.5 },
      { code: "CA", weight: 0.12 },
      { code: "GB", weight: 0.1 },
      { code: "AU", weight: 0.08 },
      { code: "DE", weight: 0.05 },
      { code: "FR", weight: 0.04 },
      { code: "NL", weight: 0.03 },
      { code: "IN", weight: 0.03 },
      { code: "BR", weight: 0.03 },
      { code: "SG", weight: 0.02 },
    ],
    topReferrers: [
      { name: "google.com", weight: 0.25 },
      { name: "facebook.com", weight: 0.2 },
      { name: "instagram.com", weight: 0.15 },
      { name: "(direct)", weight: 0.12 },
      { name: "twitter.com", weight: 0.1 },
      { name: "linkedin.com", weight: 0.08 },
      { name: "producthunt.com", weight: 0.05 },
      { name: "tiktok.com", weight: 0.05 },
    ],
    paths: [
      "/",
      "/features",
      "/pricing",
      "/testimonials",
      "/faq",
      "/get-started",
    ],
    titles: [
      "BrightPath — Launch Faster",
      "Features",
      "Pricing",
      "Testimonials",
      "FAQ",
      "Get Started",
    ],
    deviceWeights: { Desktop: 0.48, Mobile: 0.47, Tablet: 0.05 },
    weekendFactor: 0.55,
    eventNames: [
      "signup_click",
      "video_play",
      "pricing_view",
      "testimonial_scroll",
      "cta_click",
    ],
    hourProfile: { riseHour: 12, activeWidth: 9, baseLevel: 0.06 },
    visitorReturnRate: 0.05,
  },

  {
    id: "demo-site-005",
    teamId: "demo-team-001",
    name: "Developer Docs",
    domain: "docs.devstack.io",
    dailyPvRange: [6500, 12000],
    bounceRateRange: [0.22, 0.35],
    avgDurationMsRange: [180000, 420000],
    topCountries: [
      { code: "US", weight: 0.25 },
      { code: "CN", weight: 0.15 },
      { code: "IN", weight: 0.12 },
      { code: "DE", weight: 0.1 },
      { code: "GB", weight: 0.08 },
      { code: "JP", weight: 0.06 },
      { code: "BR", weight: 0.05 },
      { code: "FR", weight: 0.04 },
      { code: "KR", weight: 0.04 },
      { code: "RU", weight: 0.03 },
      { code: "CA", weight: 0.03 },
      { code: "PL", weight: 0.02 },
      { code: "NL", weight: 0.02 },
      { code: "SE", weight: 0.01 },
    ],
    topReferrers: [
      { name: "google.com", weight: 0.35 },
      { name: "(direct)", weight: 0.2 },
      { name: "github.com", weight: 0.15 },
      { name: "stackoverflow.com", weight: 0.1 },
      { name: "dev.to", weight: 0.05 },
      { name: "twitter.com", weight: 0.04 },
      { name: "reddit.com", weight: 0.04 },
      { name: "hackernews.com", weight: 0.04 },
      { name: "bing.com", weight: 0.03 },
    ],
    paths: [
      "/",
      "/getting-started",
      "/api-reference",
      "/guides/authentication",
      "/guides/webhooks",
      "/sdk/javascript",
      "/sdk/python",
      "/sdk/go",
      "/changelog",
      "/examples",
      "/migration-guide",
      "/troubleshooting",
    ],
    titles: [
      "Documentation",
      "Getting Started",
      "API Reference",
      "Authentication Guide",
      "Webhooks Guide",
      "JavaScript SDK",
      "Python SDK",
      "Go SDK",
      "Changelog",
      "Examples",
      "Migration Guide",
      "Troubleshooting",
    ],
    deviceWeights: { Desktop: 0.85, Mobile: 0.12, Tablet: 0.03 },
    weekendFactor: 0.45,
    eventNames: [
      "code_copy",
      "api_key_generate",
      "search",
      "feedback_submit",
      "example_run",
    ],
    hourProfile: { riseHour: 3, activeWidth: 18, baseLevel: 0.2 },
    visitorReturnRate: 0.42,
  },
  {
    id: "demo-site-006",
    teamId: "demo-team-001",
    name: "SaaS Dashboard",
    domain: "app.cloudmetrics.io",
    dailyPvRange: [4200, 8500],
    bounceRateRange: [0.12, 0.22],
    avgDurationMsRange: [240000, 600000],
    topCountries: [
      { code: "US", weight: 0.3 },
      { code: "DE", weight: 0.12 },
      { code: "GB", weight: 0.1 },
      { code: "CA", weight: 0.08 },
      { code: "FR", weight: 0.07 },
      { code: "AU", weight: 0.06 },
      { code: "JP", weight: 0.05 },
      { code: "NL", weight: 0.05 },
      { code: "SG", weight: 0.04 },
      { code: "SE", weight: 0.04 },
      { code: "BR", weight: 0.03 },
      { code: "IN", weight: 0.03 },
      { code: "KR", weight: 0.03 },
    ],
    topReferrers: [
      { name: "(direct)", weight: 0.55 },
      { name: "google.com", weight: 0.2 },
      { name: "github.com", weight: 0.08 },
      { name: "twitter.com", weight: 0.05 },
      { name: "linkedin.com", weight: 0.05 },
      { name: "producthunt.com", weight: 0.04 },
      { name: "bing.com", weight: 0.03 },
    ],
    paths: [
      "/",
      "/dashboard",
      "/analytics",
      "/settings",
      "/integrations",
      "/billing",
      "/team",
      "/alerts",
      "/reports",
      "/api-keys",
    ],
    titles: [
      "CloudMetrics",
      "Dashboard",
      "Analytics",
      "Settings",
      "Integrations",
      "Billing",
      "Team",
      "Alerts",
      "Reports",
      "API Keys",
    ],
    deviceWeights: { Desktop: 0.82, Mobile: 0.15, Tablet: 0.03 },
    weekendFactor: 0.3,
    eventNames: [
      "dashboard_view",
      "report_export",
      "alert_create",
      "integration_connect",
      "plan_upgrade",
    ],
    hourProfile: { riseHour: 8, activeWidth: 11, baseLevel: 0.08 },
    visitorReturnRate: 0.55,
  },
  {
    id: "demo-site-007",
    teamId: "demo-team-001",
    name: "Open Source Project",
    domain: "oss-toolkit.dev",
    dailyPvRange: [2800, 5500],
    bounceRateRange: [0.32, 0.48],
    avgDurationMsRange: [90000, 200000],
    topCountries: [
      { code: "US", weight: 0.22 },
      { code: "CN", weight: 0.18 },
      { code: "IN", weight: 0.12 },
      { code: "DE", weight: 0.08 },
      { code: "BR", weight: 0.07 },
      { code: "JP", weight: 0.06 },
      { code: "GB", weight: 0.05 },
      { code: "RU", weight: 0.05 },
      { code: "FR", weight: 0.04 },
      { code: "KR", weight: 0.04 },
      { code: "CA", weight: 0.03 },
      { code: "PL", weight: 0.03 },
      { code: "ID", weight: 0.02 },
      { code: "TR", weight: 0.01 },
    ],
    topReferrers: [
      { name: "github.com", weight: 0.35 },
      { name: "google.com", weight: 0.25 },
      { name: "(direct)", weight: 0.12 },
      { name: "stackoverflow.com", weight: 0.08 },
      { name: "reddit.com", weight: 0.06 },
      { name: "hackernews.com", weight: 0.05 },
      { name: "dev.to", weight: 0.04 },
      { name: "twitter.com", weight: 0.03 },
      { name: "npmjs.com", weight: 0.02 },
    ],
    paths: [
      "/",
      "/docs",
      "/docs/installation",
      "/docs/configuration",
      "/docs/plugins",
      "/examples",
      "/playground",
      "/blog",
      "/sponsors",
      "/community",
    ],
    titles: [
      "OSS Toolkit",
      "Documentation",
      "Installation",
      "Configuration",
      "Plugins",
      "Examples",
      "Playground",
      "Blog",
      "Sponsors",
      "Community",
    ],
    deviceWeights: { Desktop: 0.8, Mobile: 0.16, Tablet: 0.04 },
    weekendFactor: 0.65,
    eventNames: [
      "star_click",
      "install_copy",
      "playground_run",
      "docs_search",
      "issue_create",
    ],
    hourProfile: { riseHour: 20, activeWidth: 16, baseLevel: 0.18 },
    visitorReturnRate: 0.45,
  },
  {
    id: "demo-site-008",
    teamId: "demo-team-001",
    name: "API Documentation",
    domain: "api.swiftlink.dev",
    dailyPvRange: [2200, 4800],
    bounceRateRange: [0.18, 0.3],
    avgDurationMsRange: [200000, 480000],
    topCountries: [
      { code: "US", weight: 0.28 },
      { code: "IN", weight: 0.15 },
      { code: "DE", weight: 0.1 },
      { code: "CN", weight: 0.09 },
      { code: "GB", weight: 0.08 },
      { code: "JP", weight: 0.06 },
      { code: "BR", weight: 0.05 },
      { code: "FR", weight: 0.04 },
      { code: "CA", weight: 0.04 },
      { code: "KR", weight: 0.04 },
      { code: "NL", weight: 0.03 },
      { code: "AU", weight: 0.02 },
      { code: "PL", weight: 0.02 },
    ],
    topReferrers: [
      { name: "(direct)", weight: 0.3 },
      { name: "google.com", weight: 0.28 },
      { name: "github.com", weight: 0.15 },
      { name: "stackoverflow.com", weight: 0.1 },
      { name: "dev.to", weight: 0.05 },
      { name: "twitter.com", weight: 0.04 },
      { name: "reddit.com", weight: 0.04 },
      { name: "bing.com", weight: 0.04 },
    ],
    paths: [
      "/",
      "/v2/endpoints",
      "/v2/authentication",
      "/v2/rate-limits",
      "/v2/errors",
      "/v2/webhooks",
      "/sdks",
      "/sdks/node",
      "/sdks/python",
      "/changelog",
      "/status",
    ],
    titles: [
      "SwiftLink API",
      "Endpoints",
      "Authentication",
      "Rate Limits",
      "Errors",
      "Webhooks",
      "SDKs",
      "Node SDK",
      "Python SDK",
      "Changelog",
      "Status",
    ],
    deviceWeights: { Desktop: 0.88, Mobile: 0.1, Tablet: 0.02 },
    weekendFactor: 0.38,
    eventNames: [
      "api_test",
      "code_copy",
      "sdk_download",
      "search_query",
      "feedback",
    ],
    hourProfile: { riseHour: 4, activeWidth: 15, baseLevel: 0.15 },
    visitorReturnRate: 0.5,
  },

  {
    id: "demo-site-009",
    teamId: "demo-team-001",
    name: "Personal Blog",
    domain: "thoughts.jchen.me",
    dailyPvRange: [800, 2200],
    bounceRateRange: [0.45, 0.62],
    avgDurationMsRange: [60000, 150000],
    topCountries: [
      { code: "CN", weight: 0.35 },
      { code: "US", weight: 0.2 },
      { code: "JP", weight: 0.08 },
      { code: "SG", weight: 0.08 },
      { code: "TW", weight: 0.06 },
      { code: "HK", weight: 0.05 },
      { code: "DE", weight: 0.04 },
      { code: "GB", weight: 0.04 },
      { code: "CA", weight: 0.03 },
      { code: "AU", weight: 0.03 },
      { code: "KR", weight: 0.02 },
      { code: "MY", weight: 0.02 },
    ],
    topReferrers: [
      { name: "google.com", weight: 0.3 },
      { name: "(direct)", weight: 0.22 },
      { name: "twitter.com", weight: 0.15 },
      { name: "baidu.com", weight: 0.1 },
      { name: "weibo.com", weight: 0.06 },
      { name: "github.com", weight: 0.05 },
      { name: "zhihu.com", weight: 0.05 },
      { name: "bing.com", weight: 0.04 },
      { name: "reddit.com", weight: 0.03 },
    ],
    paths: [
      "/",
      "/posts",
      "/posts/building-in-public",
      "/posts/rust-vs-go",
      "/posts/side-project-lessons",
      "/posts/design-systems",
      "/about",
      "/projects",
      "/newsletter",
      "/archive",
    ],
    titles: [
      "J.Chen's Blog",
      "Posts",
      "Building in Public",
      "Rust vs Go",
      "Side Project Lessons",
      "Design Systems",
      "About",
      "Projects",
      "Newsletter",
      "Archive",
    ],
    deviceWeights: { Desktop: 0.62, Mobile: 0.33, Tablet: 0.05 },
    weekendFactor: 1.15,
    eventNames: [
      "article_read_complete",
      "newsletter_subscribe",
      "share_click",
      "comment",
    ],
    hourProfile: { riseHour: 21, activeWidth: 13, baseLevel: 0.1 },
    visitorReturnRate: 0.2,
  },
  {
    id: "demo-site-010",
    teamId: "demo-team-001",
    name: "Community Forum",
    domain: "community.pixelforge.io",
    dailyPvRange: [5500, 10000],
    bounceRateRange: [0.18, 0.28],
    avgDurationMsRange: [300000, 720000],
    topCountries: [
      { code: "US", weight: 0.28 },
      { code: "DE", weight: 0.12 },
      { code: "GB", weight: 0.1 },
      { code: "FR", weight: 0.08 },
      { code: "CA", weight: 0.06 },
      { code: "JP", weight: 0.06 },
      { code: "AU", weight: 0.05 },
      { code: "BR", weight: 0.05 },
      { code: "IN", weight: 0.05 },
      { code: "NL", weight: 0.04 },
      { code: "KR", weight: 0.04 },
      { code: "SE", weight: 0.03 },
      { code: "PL", weight: 0.02 },
      { code: "ES", weight: 0.02 },
    ],
    topReferrers: [
      { name: "(direct)", weight: 0.35 },
      { name: "google.com", weight: 0.28 },
      { name: "github.com", weight: 0.1 },
      { name: "twitter.com", weight: 0.08 },
      { name: "reddit.com", weight: 0.06 },
      { name: "discord.com", weight: 0.05 },
      { name: "youtube.com", weight: 0.04 },
      { name: "dev.to", weight: 0.04 },
    ],
    paths: [
      "/",
      "/latest",
      "/categories/general",
      "/categories/showcase",
      "/categories/help",
      "/categories/feedback",
      "/t/getting-started-guide",
      "/t/monthly-challenge",
      "/u/profile",
      "/search",
    ],
    titles: [
      "PixelForge Community",
      "Latest",
      "General",
      "Showcase",
      "Help",
      "Feedback",
      "Getting Started",
      "Monthly Challenge",
      "Profile",
      "Search",
    ],
    deviceWeights: { Desktop: 0.72, Mobile: 0.24, Tablet: 0.04 },
    weekendFactor: 1.2,
    eventNames: [
      "post_create",
      "reply_submit",
      "like_click",
      "bookmark",
      "mention",
      "upload",
    ],
    hourProfile: { riseHour: 7, activeWidth: 18, baseLevel: 0.28 },
    visitorReturnRate: 0.62,
  },
  {
    id: "demo-site-011",
    teamId: "demo-team-001",
    name: "Portfolio Site",
    domain: "studio.mikalee.design",
    dailyPvRange: [600, 1800],
    bounceRateRange: [0.5, 0.68],
    avgDurationMsRange: [40000, 100000],
    topCountries: [
      { code: "US", weight: 0.32 },
      { code: "GB", weight: 0.12 },
      { code: "DE", weight: 0.08 },
      { code: "FR", weight: 0.08 },
      { code: "CA", weight: 0.07 },
      { code: "JP", weight: 0.06 },
      { code: "AU", weight: 0.05 },
      { code: "NL", weight: 0.05 },
      { code: "SE", weight: 0.04 },
      { code: "IT", weight: 0.04 },
      { code: "BR", weight: 0.03 },
      { code: "KR", weight: 0.03 },
      { code: "SG", weight: 0.03 },
    ],
    topReferrers: [
      { name: "dribbble.com", weight: 0.22 },
      { name: "google.com", weight: 0.2 },
      { name: "(direct)", weight: 0.18 },
      { name: "behance.net", weight: 0.12 },
      { name: "linkedin.com", weight: 0.1 },
      { name: "twitter.com", weight: 0.08 },
      { name: "instagram.com", weight: 0.06 },
      { name: "pinterest.com", weight: 0.04 },
    ],
    paths: [
      "/",
      "/work",
      "/work/brand-identity",
      "/work/web-design",
      "/work/mobile-app",
      "/about",
      "/contact",
      "/blog",
      "/services",
    ],
    titles: [
      "Mika Lee Design",
      "Work",
      "Brand Identity",
      "Web Design",
      "Mobile App",
      "About",
      "Contact",
      "Blog",
      "Services",
    ],
    deviceWeights: { Desktop: 0.58, Mobile: 0.35, Tablet: 0.07 },
    weekendFactor: 0.7,
    eventNames: [
      "project_view",
      "contact_form",
      "resume_download",
      "social_click",
    ],
    hourProfile: { riseHour: 10, activeWidth: 11, baseLevel: 0.08 },
    visitorReturnRate: 0.1,
  },
  {
    id: "demo-site-012",
    teamId: "demo-team-001",
    name: "Education Platform",
    domain: "learn.codeacademy.org",
    dailyPvRange: [7000, 13000],
    bounceRateRange: [0.15, 0.25],
    avgDurationMsRange: [480000, 1200000],
    topCountries: [
      { code: "US", weight: 0.22 },
      { code: "IN", weight: 0.18 },
      { code: "BR", weight: 0.1 },
      { code: "NG", weight: 0.06 },
      { code: "GB", weight: 0.06 },
      { code: "DE", weight: 0.05 },
      { code: "ID", weight: 0.05 },
      { code: "PH", weight: 0.04 },
      { code: "PK", weight: 0.04 },
      { code: "CA", weight: 0.04 },
      { code: "MX", weight: 0.03 },
      { code: "KE", weight: 0.03 },
      { code: "EG", weight: 0.03 },
      { code: "VN", weight: 0.03 },
      { code: "TR", weight: 0.02 },
      { code: "CO", weight: 0.02 },
    ],
    topReferrers: [
      { name: "google.com", weight: 0.35 },
      { name: "(direct)", weight: 0.25 },
      { name: "youtube.com", weight: 0.1 },
      { name: "reddit.com", weight: 0.06 },
      { name: "twitter.com", weight: 0.05 },
      { name: "facebook.com", weight: 0.05 },
      { name: "linkedin.com", weight: 0.04 },
      { name: "dev.to", weight: 0.04 },
      { name: "quora.com", weight: 0.03 },
      { name: "stackoverflow.com", weight: 0.03 },
    ],
    paths: [
      "/",
      "/courses",
      "/courses/javascript-fundamentals",
      "/courses/python-data-science",
      "/courses/react-masterclass",
      "/courses/sql-basics",
      "/dashboard",
      "/certificates",
      "/community",
      "/pricing",
      "/blog",
      "/paths/fullstack",
    ],
    titles: [
      "CodeAcademy",
      "Courses",
      "JavaScript Fundamentals",
      "Python Data Science",
      "React Masterclass",
      "SQL Basics",
      "Dashboard",
      "Certificates",
      "Community",
      "Pricing",
      "Blog",
      "Full-Stack Path",
    ],
    deviceWeights: { Desktop: 0.65, Mobile: 0.3, Tablet: 0.05 },
    weekendFactor: 1.1,
    eventNames: [
      "lesson_complete",
      "quiz_submit",
      "certificate_earn",
      "course_enroll",
      "exercise_run",
      "hint_request",
    ],
    hourProfile: { riseHour: 0, activeWidth: 20, baseLevel: 0.22 },
    visitorReturnRate: 0.48,
  },
];

export function findSiteProfile(siteId: string): DemoSiteProfile {
  return (
    DEMO_SITE_PROFILES.find((s) => s.id === siteId) ?? DEMO_SITE_PROFILES[0]
  );
}
