import type { DemoSiteProfile } from "./demo-site-profiles-types";

export const DEMO_SITE_PROFILES_PART_2: DemoSiteProfile[] = [
  {
    id: "demo-site-005",
    teamId: "demo-team-001",
    name: "Developer Docs",
    domain: "docs.devstack.io",
    iconPath: "/images/demo-sites/docs.svg",
    dailyPvRange: [6500, 12000],
    bounceRateRange: [0.22, 0.35],
    avgDurationMsRange: [180000, 420000],
    topCountries: [
      { code: "US", weight: 0.25 },
      { code: "CN", weight: 0.15 },
      { code: "IN", weight: 0.12 },
      { code: "DE", weight: 0.1 },
      { code: "GB", weight: 0.08 },
      { code: "JP", weight: 0.06 },
      { code: "BR", weight: 0.05 },
      { code: "FR", weight: 0.04 },
      { code: "KR", weight: 0.04 },
      { code: "RU", weight: 0.03 },
      { code: "CA", weight: 0.03 },
      { code: "PL", weight: 0.02 },
      { code: "NL", weight: 0.02 },
      { code: "SE", weight: 0.01 },
    ],
    topReferrers: [
      { name: "google.com", weight: 0.35 },
      { name: "(direct)", weight: 0.2 },
      { name: "github.com", weight: 0.15 },
      { name: "stackoverflow.com", weight: 0.1 },
      { name: "dev.to", weight: 0.05 },
      { name: "twitter.com", weight: 0.04 },
      { name: "reddit.com", weight: 0.04 },
      { name: "hackernews.com", weight: 0.04 },
      { name: "bing.com", weight: 0.03 },
    ],
    paths: [
      "/",
      "/getting-started",
      "/api-reference",
      "/guides/authentication",
      "/guides/webhooks",
      "/sdk/javascript",
      "/sdk/python",
      "/sdk/go",
      "/changelog",
      "/examples",
      "/migration-guide",
      "/troubleshooting",
    ],
    titles: [
      "Documentation",
      "Getting Started",
      "API Reference",
      "Authentication Guide",
      "Webhooks Guide",
      "JavaScript SDK",
      "Python SDK",
      "Go SDK",
      "Changelog",
      "Examples",
      "Migration Guide",
      "Troubleshooting",
    ],
    deviceWeights: { Desktop: 0.85, Mobile: 0.12, Tablet: 0.03 },
    weekendFactor: 0.45,
    eventNames: [
      "code_copy",
      "api_key_generate",
      "search",
      "feedback_submit",
      "example_run",
    ],
    hourProfile: { riseHour: 3, activeWidth: 18, baseLevel: 0.2 },
    visitorReturnRate: 0.42,
  },
  {
    id: "demo-site-006",
    teamId: "demo-team-001",
    name: "SaaS Dashboard",
    domain: "app.cloudmetrics.io",
    iconPath: "/images/demo-sites/saas.svg",
    dailyPvRange: [4200, 8500],
    bounceRateRange: [0.12, 0.22],
    avgDurationMsRange: [240000, 600000],
    topCountries: [
      { code: "US", weight: 0.3 },
      { code: "DE", weight: 0.12 },
      { code: "GB", weight: 0.1 },
      { code: "CA", weight: 0.08 },
      { code: "FR", weight: 0.07 },
      { code: "AU", weight: 0.06 },
      { code: "JP", weight: 0.05 },
      { code: "NL", weight: 0.05 },
      { code: "SG", weight: 0.04 },
      { code: "SE", weight: 0.04 },
      { code: "BR", weight: 0.03 },
      { code: "IN", weight: 0.03 },
      { code: "KR", weight: 0.03 },
    ],
    topReferrers: [
      { name: "(direct)", weight: 0.55 },
      { name: "google.com", weight: 0.2 },
      { name: "github.com", weight: 0.08 },
      { name: "twitter.com", weight: 0.05 },
      { name: "linkedin.com", weight: 0.05 },
      { name: "producthunt.com", weight: 0.04 },
      { name: "bing.com", weight: 0.03 },
    ],
    paths: [
      "/",
      "/dashboard",
      "/analytics",
      "/settings",
      "/integrations",
      "/billing",
      "/team",
      "/alerts",
      "/reports",
      "/api-keys",
    ],
    titles: [
      "CloudMetrics",
      "Dashboard",
      "Analytics",
      "Settings",
      "Integrations",
      "Billing",
      "Team",
      "Alerts",
      "Reports",
      "API Keys",
    ],
    deviceWeights: { Desktop: 0.82, Mobile: 0.15, Tablet: 0.03 },
    weekendFactor: 0.3,
    eventNames: [
      "dashboard_view",
      "report_export",
      "alert_create",
      "integration_connect",
      "plan_upgrade",
    ],
    hourProfile: { riseHour: 8, activeWidth: 11, baseLevel: 0.08 },
    visitorReturnRate: 0.55,
  },
  {
    id: "demo-site-007",
    teamId: "demo-team-001",
    name: "Open Source Project",
    domain: "oss-toolkit.dev",
    iconPath: "/images/demo-sites/oss.svg",
    dailyPvRange: [2800, 5500],
    bounceRateRange: [0.32, 0.48],
    avgDurationMsRange: [90000, 200000],
    topCountries: [
      { code: "US", weight: 0.22 },
      { code: "CN", weight: 0.18 },
      { code: "IN", weight: 0.12 },
      { code: "DE", weight: 0.08 },
      { code: "BR", weight: 0.07 },
      { code: "JP", weight: 0.06 },
      { code: "GB", weight: 0.05 },
      { code: "RU", weight: 0.05 },
      { code: "FR", weight: 0.04 },
      { code: "KR", weight: 0.04 },
      { code: "CA", weight: 0.03 },
      { code: "PL", weight: 0.03 },
      { code: "ID", weight: 0.02 },
      { code: "TR", weight: 0.01 },
    ],
    topReferrers: [
      { name: "github.com", weight: 0.35 },
      { name: "google.com", weight: 0.25 },
      { name: "(direct)", weight: 0.12 },
      { name: "stackoverflow.com", weight: 0.08 },
      { name: "reddit.com", weight: 0.06 },
      { name: "hackernews.com", weight: 0.05 },
      { name: "dev.to", weight: 0.04 },
      { name: "twitter.com", weight: 0.03 },
      { name: "npmjs.com", weight: 0.02 },
    ],
    paths: [
      "/",
      "/docs",
      "/docs/installation",
      "/docs/configuration",
      "/docs/plugins",
      "/examples",
      "/playground",
      "/blog",
      "/sponsors",
      "/community",
    ],
    titles: [
      "OSS Toolkit",
      "Documentation",
      "Installation",
      "Configuration",
      "Plugins",
      "Examples",
      "Playground",
      "Blog",
      "Sponsors",
      "Community",
    ],
    deviceWeights: { Desktop: 0.8, Mobile: 0.16, Tablet: 0.04 },
    weekendFactor: 0.65,
    eventNames: [
      "star_click",
      "install_copy",
      "playground_run",
      "docs_search",
      "issue_create",
    ],
    hourProfile: { riseHour: 20, activeWidth: 16, baseLevel: 0.18 },
    visitorReturnRate: 0.45,
  },
  {
    id: "demo-site-008",
    teamId: "demo-team-001",
    name: "API Documentation",
    domain: "api.swiftlink.dev",
    iconPath: "/images/demo-sites/api.svg",
    dailyPvRange: [2200, 4800],
    bounceRateRange: [0.18, 0.3],
    avgDurationMsRange: [200000, 480000],
    topCountries: [
      { code: "US", weight: 0.28 },
      { code: "IN", weight: 0.15 },
      { code: "DE", weight: 0.1 },
      { code: "CN", weight: 0.09 },
      { code: "GB", weight: 0.08 },
      { code: "JP", weight: 0.06 },
      { code: "BR", weight: 0.05 },
      { code: "FR", weight: 0.04 },
      { code: "CA", weight: 0.04 },
      { code: "KR", weight: 0.04 },
      { code: "NL", weight: 0.03 },
      { code: "AU", weight: 0.02 },
      { code: "PL", weight: 0.02 },
    ],
    topReferrers: [
      { name: "(direct)", weight: 0.3 },
      { name: "google.com", weight: 0.28 },
      { name: "github.com", weight: 0.15 },
      { name: "stackoverflow.com", weight: 0.1 },
      { name: "dev.to", weight: 0.05 },
      { name: "twitter.com", weight: 0.04 },
      { name: "reddit.com", weight: 0.04 },
      { name: "bing.com", weight: 0.04 },
    ],
    paths: [
      "/",
      "/v2/endpoints",
      "/v2/authentication",
      "/v2/rate-limits",
      "/v2/errors",
      "/v2/webhooks",
      "/sdks",
      "/sdks/node",
      "/sdks/python",
      "/changelog",
      "/status",
    ],
    titles: [
      "SwiftLink API",
      "Endpoints",
      "Authentication",
      "Rate Limits",
      "Errors",
      "Webhooks",
      "SDKs",
      "Node SDK",
      "Python SDK",
      "Changelog",
      "Status",
    ],
    deviceWeights: { Desktop: 0.88, Mobile: 0.1, Tablet: 0.02 },
    weekendFactor: 0.38,
    eventNames: [
      "api_test",
      "code_copy",
      "sdk_download",
      "search_query",
      "feedback",
    ],
    hourProfile: { riseHour: 4, activeWidth: 15, baseLevel: 0.15 },
    visitorReturnRate: 0.5,
  },
];
