import type { DemoSiteProfile } from "./demo-site-profiles-types";

export const DEMO_SITE_PROFILES_PART_3: DemoSiteProfile[] = [
  {
    id: "demo-site-009",
    teamId: "demo-team-001",
    name: "Personal Blog",
    domain: "thoughts.jchen.me",
    iconPath: "/images/demo-sites/blog.svg",
    dailyPvRange: [800, 2200],
    bounceRateRange: [0.45, 0.62],
    avgDurationMsRange: [60000, 150000],
    topCountries: [
      { code: "CN", weight: 0.35 },
      { code: "US", weight: 0.2 },
      { code: "JP", weight: 0.08 },
      { code: "SG", weight: 0.08 },
      { code: "TW", weight: 0.06 },
      { code: "HK", weight: 0.05 },
      { code: "DE", weight: 0.04 },
      { code: "GB", weight: 0.04 },
      { code: "CA", weight: 0.03 },
      { code: "AU", weight: 0.03 },
      { code: "KR", weight: 0.02 },
      { code: "MY", weight: 0.02 },
    ],
    topReferrers: [
      { name: "google.com", weight: 0.3 },
      { name: "(direct)", weight: 0.22 },
      { name: "twitter.com", weight: 0.15 },
      { name: "baidu.com", weight: 0.1 },
      { name: "weibo.com", weight: 0.06 },
      { name: "github.com", weight: 0.05 },
      { name: "zhihu.com", weight: 0.05 },
      { name: "bing.com", weight: 0.04 },
      { name: "reddit.com", weight: 0.03 },
    ],
    paths: [
      "/",
      "/posts",
      "/posts/building-in-public",
      "/posts/rust-vs-go",
      "/posts/side-project-lessons",
      "/posts/design-systems",
      "/about",
      "/projects",
      "/newsletter",
      "/archive",
    ],
    titles: [
      "J.Chen's Blog",
      "Posts",
      "Building in Public",
      "Rust vs Go",
      "Side Project Lessons",
      "Design Systems",
      "About",
      "Projects",
      "Newsletter",
      "Archive",
    ],
    deviceWeights: { Desktop: 0.62, Mobile: 0.33, Tablet: 0.05 },
    weekendFactor: 1.15,
    eventNames: [
      "article_read_complete",
      "newsletter_subscribe",
      "share_click",
      "comment",
    ],
    hourProfile: { riseHour: 21, activeWidth: 13, baseLevel: 0.1 },
    visitorReturnRate: 0.2,
  },
  {
    id: "demo-site-010",
    teamId: "demo-team-001",
    name: "Community Forum",
    domain: "community.pixelforge.io",
    iconPath: "/images/demo-sites/community.svg",
    dailyPvRange: [5500, 10000],
    bounceRateRange: [0.18, 0.28],
    avgDurationMsRange: [300000, 720000],
    topCountries: [
      { code: "US", weight: 0.28 },
      { code: "DE", weight: 0.12 },
      { code: "GB", weight: 0.1 },
      { code: "FR", weight: 0.08 },
      { code: "CA", weight: 0.06 },
      { code: "JP", weight: 0.06 },
      { code: "AU", weight: 0.05 },
      { code: "BR", weight: 0.05 },
      { code: "IN", weight: 0.05 },
      { code: "NL", weight: 0.04 },
      { code: "KR", weight: 0.04 },
      { code: "SE", weight: 0.03 },
      { code: "PL", weight: 0.02 },
      { code: "ES", weight: 0.02 },
    ],
    topReferrers: [
      { name: "(direct)", weight: 0.35 },
      { name: "google.com", weight: 0.28 },
      { name: "github.com", weight: 0.1 },
      { name: "twitter.com", weight: 0.08 },
      { name: "reddit.com", weight: 0.06 },
      { name: "discord.com", weight: 0.05 },
      { name: "youtube.com", weight: 0.04 },
      { name: "dev.to", weight: 0.04 },
    ],
    paths: [
      "/",
      "/latest",
      "/categories/general",
      "/categories/showcase",
      "/categories/help",
      "/categories/feedback",
      "/t/getting-started-guide",
      "/t/monthly-challenge",
      "/u/profile",
      "/search",
    ],
    titles: [
      "PixelForge Community",
      "Latest",
      "General",
      "Showcase",
      "Help",
      "Feedback",
      "Getting Started",
      "Monthly Challenge",
      "Profile",
      "Search",
    ],
    deviceWeights: { Desktop: 0.72, Mobile: 0.24, Tablet: 0.04 },
    weekendFactor: 1.2,
    eventNames: [
      "post_create",
      "reply_submit",
      "like_click",
      "bookmark",
      "mention",
      "upload",
    ],
    hourProfile: { riseHour: 7, activeWidth: 18, baseLevel: 0.28 },
    visitorReturnRate: 0.62,
  },
  {
    id: "demo-site-011",
    teamId: "demo-team-001",
    name: "Portfolio Site",
    domain: "studio.mikalee.design",
    iconPath: "/images/demo-sites/portfolio.svg",
    dailyPvRange: [600, 1800],
    bounceRateRange: [0.5, 0.68],
    avgDurationMsRange: [40000, 100000],
    topCountries: [
      { code: "US", weight: 0.32 },
      { code: "GB", weight: 0.12 },
      { code: "DE", weight: 0.08 },
      { code: "FR", weight: 0.08 },
      { code: "CA", weight: 0.07 },
      { code: "JP", weight: 0.06 },
      { code: "AU", weight: 0.05 },
      { code: "NL", weight: 0.05 },
      { code: "SE", weight: 0.04 },
      { code: "IT", weight: 0.04 },
      { code: "BR", weight: 0.03 },
      { code: "KR", weight: 0.03 },
      { code: "SG", weight: 0.03 },
    ],
    topReferrers: [
      { name: "dribbble.com", weight: 0.22 },
      { name: "google.com", weight: 0.2 },
      { name: "(direct)", weight: 0.18 },
      { name: "behance.net", weight: 0.12 },
      { name: "linkedin.com", weight: 0.1 },
      { name: "twitter.com", weight: 0.08 },
      { name: "instagram.com", weight: 0.06 },
      { name: "pinterest.com", weight: 0.04 },
    ],
    paths: [
      "/",
      "/work",
      "/work/brand-identity",
      "/work/web-design",
      "/work/mobile-app",
      "/about",
      "/contact",
      "/blog",
      "/services",
    ],
    titles: [
      "Mika Lee Design",
      "Work",
      "Brand Identity",
      "Web Design",
      "Mobile App",
      "About",
      "Contact",
      "Blog",
      "Services",
    ],
    deviceWeights: { Desktop: 0.58, Mobile: 0.35, Tablet: 0.07 },
    weekendFactor: 0.7,
    eventNames: [
      "project_view",
      "contact_form",
      "resume_download",
      "social_click",
    ],
    hourProfile: { riseHour: 10, activeWidth: 11, baseLevel: 0.08 },
    visitorReturnRate: 0.1,
  },
  {
    id: "demo-site-012",
    teamId: "demo-team-001",
    name: "Education Platform",
    domain: "learn.codeacademy.org",
    iconPath: "/images/demo-sites/education.svg",
    dailyPvRange: [7000, 13000],
    bounceRateRange: [0.15, 0.25],
    avgDurationMsRange: [480000, 1200000],
    topCountries: [
      { code: "US", weight: 0.22 },
      { code: "IN", weight: 0.18 },
      { code: "BR", weight: 0.1 },
      { code: "NG", weight: 0.06 },
      { code: "GB", weight: 0.06 },
      { code: "DE", weight: 0.05 },
      { code: "ID", weight: 0.05 },
      { code: "PH", weight: 0.04 },
      { code: "PK", weight: 0.04 },
      { code: "CA", weight: 0.04 },
      { code: "MX", weight: 0.03 },
      { code: "KE", weight: 0.03 },
      { code: "EG", weight: 0.03 },
      { code: "VN", weight: 0.03 },
      { code: "TR", weight: 0.02 },
      { code: "CO", weight: 0.02 },
    ],
    topReferrers: [
      { name: "google.com", weight: 0.35 },
      { name: "(direct)", weight: 0.25 },
      { name: "youtube.com", weight: 0.1 },
      { name: "reddit.com", weight: 0.06 },
      { name: "twitter.com", weight: 0.05 },
      { name: "facebook.com", weight: 0.05 },
      { name: "linkedin.com", weight: 0.04 },
      { name: "dev.to", weight: 0.04 },
      { name: "quora.com", weight: 0.03 },
      { name: "stackoverflow.com", weight: 0.03 },
    ],
    paths: [
      "/",
      "/courses",
      "/courses/javascript-fundamentals",
      "/courses/python-data-science",
      "/courses/react-masterclass",
      "/courses/sql-basics",
      "/dashboard",
      "/certificates",
      "/community",
      "/pricing",
      "/blog",
      "/paths/fullstack",
    ],
    titles: [
      "CodeAcademy",
      "Courses",
      "JavaScript Fundamentals",
      "Python Data Science",
      "React Masterclass",
      "SQL Basics",
      "Dashboard",
      "Certificates",
      "Community",
      "Pricing",
      "Blog",
      "Full-Stack Path",
    ],
    deviceWeights: { Desktop: 0.65, Mobile: 0.3, Tablet: 0.05 },
    weekendFactor: 1.1,
    eventNames: [
      "lesson_complete",
      "quiz_submit",
      "certificate_earn",
      "course_enroll",
      "exercise_run",
      "hint_request",
    ],
    hourProfile: { riseHour: 0, activeWidth: 20, baseLevel: 0.22 },
    visitorReturnRate: 0.48,
  },
];
