/* Generated from ApiV1RouteRegistry. Do not edit manually. */

export const apiV1GeneratedRouteMetadata = {
  "site.analytics.overview": {
    id: "site.analytics.overview",
    operationId: "site.analytics.overview",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/overview",
    lifecycle: "exposed",
  },
  "team.analytics.overview": {
    id: "team.analytics.overview",
    operationId: "team.analytics.overview",
    method: "POST",
    path: "/api/v1/team/analytics/overview",
    lifecycle: "exposed",
  },
  "core.root": {
    id: "core.root",
    operationId: "core.root",
    method: "GET",
    path: "/api/v1",
    lifecycle: "exposed",
  },
  "core.token.get": {
    id: "core.token.get",
    operationId: "core.token.get",
    method: "GET",
    path: "/api/v1/token",
    lifecycle: "exposed",
  },
  "core.token.check": {
    id: "core.token.check",
    operationId: "core.token.check",
    method: "POST",
    path: "/api/v1/token/check",
    lifecycle: "exposed",
  },
  "core.capabilities": {
    id: "core.capabilities",
    operationId: "core.capabilities",
    method: "GET",
    path: "/api/v1/capabilities",
    lifecycle: "exposed",
  },
  "core.team.get": {
    id: "core.team.get",
    operationId: "core.team.get",
    method: "GET",
    path: "/api/v1/team",
    lifecycle: "exposed",
  },
  "core.team.usage": {
    id: "core.team.usage",
    operationId: "core.team.usage",
    method: "GET",
    path: "/api/v1/team/usage",
    lifecycle: "exposed",
  },
  "site.analytics.comparison": {
    id: "site.analytics.comparison",
    operationId: "site.analytics.comparison",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/comparison",
    lifecycle: "exposed",
  },
  "site.analytics.comparisonBreakdown": {
    id: "site.analytics.comparisonBreakdown",
    operationId: "site.analytics.comparisonBreakdown",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/comparison/breakdowns/{dimension}",
    lifecycle: "exposed",
  },
  "team.analytics.comparison": {
    id: "team.analytics.comparison",
    operationId: "team.analytics.comparison",
    method: "POST",
    path: "/api/v1/team/analytics/comparison",
    lifecycle: "exposed",
  },
  "team.analytics.comparisonBreakdown": {
    id: "team.analytics.comparisonBreakdown",
    operationId: "team.analytics.comparisonBreakdown",
    method: "POST",
    path: "/api/v1/team/analytics/comparison/breakdowns/{dimension}",
    lifecycle: "exposed",
  },
  "site.analytics.schema": {
    id: "site.analytics.schema",
    operationId: "site.analytics.schema",
    method: "GET",
    path: "/api/v1/sites/{siteId}/analytics/schema",
    lifecycle: "exposed",
  },
  "team.analytics.schema": {
    id: "team.analytics.schema",
    operationId: "team.analytics.schema",
    method: "GET",
    path: "/api/v1/team/analytics/schema",
    lifecycle: "exposed",
  },
  "site.analytics.timeseries": {
    id: "site.analytics.timeseries",
    operationId: "site.analytics.timeseries",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/timeseries",
    lifecycle: "exposed",
  },
  "team.analytics.timeseries": {
    id: "team.analytics.timeseries",
    operationId: "team.analytics.timeseries",
    method: "POST",
    path: "/api/v1/team/analytics/timeseries",
    lifecycle: "exposed",
  },
  "team.analytics.sites": {
    id: "team.analytics.sites",
    operationId: "team.analytics.sites",
    method: "POST",
    path: "/api/v1/team/analytics/sites",
    lifecycle: "exposed",
  },
  "site.analytics.breakdown": {
    id: "site.analytics.breakdown",
    operationId: "site.analytics.breakdown",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/breakdowns/{dimension}",
    lifecycle: "exposed",
  },
  "team.analytics.breakdown": {
    id: "team.analytics.breakdown",
    operationId: "team.analytics.breakdown",
    method: "POST",
    path: "/api/v1/team/analytics/breakdowns/{dimension}",
    lifecycle: "exposed",
  },
  "site.analytics.crossBreakdown": {
    id: "site.analytics.crossBreakdown",
    operationId: "site.analytics.crossBreakdown",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/cross-breakdowns",
    lifecycle: "exposed",
  },
  "site.analytics.pages": {
    id: "site.analytics.pages",
    operationId: "site.analytics.pages",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/pages",
    lifecycle: "exposed",
  },
  "site.analytics.referrers": {
    id: "site.analytics.referrers",
    operationId: "site.analytics.referrers",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/referrers",
    lifecycle: "exposed",
  },
  "site.analytics.channels": {
    id: "site.analytics.channels",
    operationId: "site.analytics.channels",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/channels",
    lifecycle: "exposed",
  },
  "site.analytics.filterValues": {
    id: "site.analytics.filterValues",
    operationId: "site.analytics.filterValues",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/filter-values",
    lifecycle: "exposed",
  },
  "site.analytics.retentionCohorts": {
    id: "site.analytics.retentionCohorts",
    operationId: "site.analytics.retentionCohorts",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/retention/cohorts",
    lifecycle: "exposed",
  },
  "site.analytics.funnelAnalysis": {
    id: "site.analytics.funnelAnalysis",
    operationId: "site.analytics.funnelAnalysis",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/funnel-analysis",
    lifecycle: "exposed",
  },
  "site.analytics.performanceSummary": {
    id: "site.analytics.performanceSummary",
    operationId: "site.analytics.performanceSummary",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/performance/summary",
    lifecycle: "exposed",
  },
  "site.analytics.performanceTimeseries": {
    id: "site.analytics.performanceTimeseries",
    operationId: "site.analytics.performanceTimeseries",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/performance/timeseries",
    lifecycle: "exposed",
  },
  "site.analytics.performanceBreakdown": {
    id: "site.analytics.performanceBreakdown",
    operationId: "site.analytics.performanceBreakdown",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/performance/breakdowns/{dimension}",
    lifecycle: "exposed",
  },
  "site.analytics.eventsSummary": {
    id: "site.analytics.eventsSummary",
    operationId: "site.analytics.eventsSummary",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/events/summary",
    lifecycle: "exposed",
  },
  "site.analytics.eventsTimeseries": {
    id: "site.analytics.eventsTimeseries",
    operationId: "site.analytics.eventsTimeseries",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/events/timeseries",
    lifecycle: "exposed",
  },
  "site.analytics.eventsSearch": {
    id: "site.analytics.eventsSearch",
    operationId: "site.analytics.eventsSearch",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/events/search",
    lifecycle: "exposed",
  },
  "site.analytics.eventDetail": {
    id: "site.analytics.eventDetail",
    operationId: "site.analytics.eventDetail",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/events/detail",
    lifecycle: "exposed",
  },
  "site.analytics.journeyEventDetail": {
    id: "site.analytics.journeyEventDetail",
    operationId: "site.analytics.journeyEventDetail",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/journey-events/detail",
    lifecycle: "exposed",
  },
  "site.analytics.eventTypes": {
    id: "site.analytics.eventTypes",
    operationId: "site.analytics.eventTypes",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/event-types",
    lifecycle: "exposed",
  },
  "site.analytics.eventTypeDetail": {
    id: "site.analytics.eventTypeDetail",
    operationId: "site.analytics.eventTypeDetail",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/event-types/detail",
    lifecycle: "exposed",
  },
  "site.analytics.eventFields": {
    id: "site.analytics.eventFields",
    operationId: "site.analytics.eventFields",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/event-types/fields",
    lifecycle: "exposed",
  },
  "site.analytics.eventFieldValues": {
    id: "site.analytics.eventFieldValues",
    operationId: "site.analytics.eventFieldValues",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/event-types/field-values",
    lifecycle: "exposed",
  },
  "site.analytics.visitorDetail": {
    id: "site.analytics.visitorDetail",
    operationId: "site.analytics.visitorDetail",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/visitors/detail",
    lifecycle: "exposed",
  },
  "site.analytics.sessionDetail": {
    id: "site.analytics.sessionDetail",
    operationId: "site.analytics.sessionDetail",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/sessions/detail",
    lifecycle: "exposed",
  },
  "site.analytics.visitorsSearch": {
    id: "site.analytics.visitorsSearch",
    operationId: "site.analytics.visitorsSearch",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/visitors/search",
    lifecycle: "exposed",
  },
  "site.analytics.sessionsSearch": {
    id: "site.analytics.sessionsSearch",
    operationId: "site.analytics.sessionsSearch",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/sessions/search",
    lifecycle: "exposed",
  },
  "site.analytics.visitorEvents": {
    id: "site.analytics.visitorEvents",
    operationId: "site.analytics.visitorEvents",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/visitors/events",
    lifecycle: "exposed",
  },
  "site.analytics.visitorSessions": {
    id: "site.analytics.visitorSessions",
    operationId: "site.analytics.visitorSessions",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/visitors/sessions",
    lifecycle: "exposed",
  },
  "site.analytics.sessionEvents": {
    id: "site.analytics.sessionEvents",
    operationId: "site.analytics.sessionEvents",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/sessions/events",
    lifecycle: "exposed",
  },
  "site.analytics.realtimeSnapshot": {
    id: "site.analytics.realtimeSnapshot",
    operationId: "site.analytics.realtimeSnapshot",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/realtime/snapshot",
    lifecycle: "exposed",
  },
  "site.analytics.realtimeActiveVisitors": {
    id: "site.analytics.realtimeActiveVisitors",
    operationId: "site.analytics.realtimeActiveVisitors",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/realtime/active-visitors",
    lifecycle: "exposed",
  },
  "site.analytics.realtimeEvents": {
    id: "site.analytics.realtimeEvents",
    operationId: "site.analytics.realtimeEvents",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/realtime/events",
    lifecycle: "exposed",
  },
  "site.analytics.realtimeSessions": {
    id: "site.analytics.realtimeSessions",
    operationId: "site.analytics.realtimeSessions",
    method: "POST",
    path: "/api/v1/sites/{siteId}/analytics/realtime/sessions",
    lifecycle: "exposed",
  },
  "sites.list": {
    id: "sites.list",
    operationId: "sites.list",
    method: "GET",
    path: "/api/v1/sites",
    lifecycle: "exposed",
  },
  "sites.create": {
    id: "sites.create",
    operationId: "sites.create",
    method: "POST",
    path: "/api/v1/sites",
    lifecycle: "exposed",
  },
  "sites.get": {
    id: "sites.get",
    operationId: "sites.get",
    method: "GET",
    path: "/api/v1/sites/{siteId}",
    lifecycle: "exposed",
  },
  "sites.update": {
    id: "sites.update",
    operationId: "sites.update",
    method: "PATCH",
    path: "/api/v1/sites/{siteId}",
    lifecycle: "exposed",
  },
  "sites.delete": {
    id: "sites.delete",
    operationId: "sites.delete",
    method: "DELETE",
    path: "/api/v1/sites/{siteId}",
    lifecycle: "exposed",
  },
  "settings.tracking.get": {
    id: "settings.tracking.get",
    operationId: "settings.tracking.get",
    method: "GET",
    path: "/api/v1/sites/{siteId}/settings/tracking",
    lifecycle: "exposed",
  },
  "settings.tracking.update": {
    id: "settings.tracking.update",
    operationId: "settings.tracking.update",
    method: "PATCH",
    path: "/api/v1/sites/{siteId}/settings/tracking",
    lifecycle: "exposed",
  },
  "settings.privacy.get": {
    id: "settings.privacy.get",
    operationId: "settings.privacy.get",
    method: "GET",
    path: "/api/v1/sites/{siteId}/settings/privacy",
    lifecycle: "exposed",
  },
  "settings.privacy.update": {
    id: "settings.privacy.update",
    operationId: "settings.privacy.update",
    method: "PATCH",
    path: "/api/v1/sites/{siteId}/settings/privacy",
    lifecycle: "exposed",
  },
  "settings.sharing.get": {
    id: "settings.sharing.get",
    operationId: "settings.sharing.get",
    method: "GET",
    path: "/api/v1/sites/{siteId}/settings/sharing",
    lifecycle: "exposed",
  },
  "settings.sharing.update": {
    id: "settings.sharing.update",
    operationId: "settings.sharing.update",
    method: "PATCH",
    path: "/api/v1/sites/{siteId}/settings/sharing",
    lifecycle: "exposed",
  },
  "settings.tracking-script.get": {
    id: "settings.tracking-script.get",
    operationId: "settings.trackingScript.get",
    method: "GET",
    path: "/api/v1/sites/{siteId}/settings/tracking-script",
    lifecycle: "exposed",
  },
  "funnels.list": {
    id: "funnels.list",
    operationId: "funnels.list",
    method: "GET",
    path: "/api/v1/sites/{siteId}/funnels",
    lifecycle: "exposed",
  },
  "funnels.create": {
    id: "funnels.create",
    operationId: "funnels.create",
    method: "POST",
    path: "/api/v1/sites/{siteId}/funnels",
    lifecycle: "exposed",
  },
  "funnels.get": {
    id: "funnels.get",
    operationId: "funnels.get",
    method: "GET",
    path: "/api/v1/sites/{siteId}/funnels/{funnelId}",
    lifecycle: "exposed",
  },
  "funnels.update": {
    id: "funnels.update",
    operationId: "funnels.update",
    method: "PATCH",
    path: "/api/v1/sites/{siteId}/funnels/{funnelId}",
    lifecycle: "exposed",
  },
  "funnels.delete": {
    id: "funnels.delete",
    operationId: "funnels.delete",
    method: "DELETE",
    path: "/api/v1/sites/{siteId}/funnels/{funnelId}",
    lifecycle: "exposed",
  },
  "site.saved-filters.list": {
    id: "site.saved-filters.list",
    operationId: "savedFilters.list",
    method: "GET",
    path: "/api/v1/sites/{siteId}/saved-filters",
    lifecycle: "exposed",
  },
  "site.saved-filters.get": {
    id: "site.saved-filters.get",
    operationId: "savedFilters.get",
    method: "GET",
    path: "/api/v1/sites/{siteId}/saved-filters/{savedFilterId}",
    lifecycle: "exposed",
  },
  batch: {
    id: "batch",
    operationId: "batch",
    method: "POST",
    path: "/api/v1/batch",
    lifecycle: "exposed",
  },
} as const;

export type ApiV1GeneratedRouteId = keyof typeof apiV1GeneratedRouteMetadata;

export function apiV1GeneratedRouteMethod(
  id: ApiV1GeneratedRouteId,
): (typeof apiV1GeneratedRouteMetadata)[ApiV1GeneratedRouteId]["method"] {
  return apiV1GeneratedRouteMetadata[id].method;
}

export function apiV1GeneratedRoutePath(
  id: ApiV1GeneratedRouteId,
  parameters: Readonly<Record<string, string>> = {},
): string {
  return apiV1GeneratedRouteMetadata[id].path.replace(
    /\{([^}]+)\}/gu,
    (_match, name: string) => {
      const value = parameters[name];
      if (!value)
        throw new Error(`Missing generated API v1 route parameter: ${name}`);
      return encodeURIComponent(value);
    },
  );
}
