/**
 * Builds the browser tracker SDK using esbuild.
 * Generates two variants:
 *   - sdk.min.ts        (BUILD_PERFORMANCE=true)  for sites with performance sampling
 *   - sdk.no-perf.min.ts (BUILD_PERFORMANCE=false) for sites without performance
 * Placeholder strings (__IF_*__) survive minification and are replaced at serve time.
 */
import * as esbuild from "esbuild";
import { writeFileSync } from "fs";
import { dirname, resolve } from "path";
import { minify } from "terser";
import { fileURLToPath } from "url";

import { createScriptLogger } from "./shared/logger";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const entry = resolve(root, "src/tracker/sdk.ts");

const rlog = createScriptLogger({
  logFile: "build-sdk.log",
});

const commonOpts: esbuild.BuildOptions = {
  entryPoints: [entry],
  bundle: true,
  minify: false,
  format: "iife",
  target: ["es2020"],
  write: false,
};

const noPerformancePlugin: esbuild.Plugin = {
  name: "tracker-no-performance-stub",
  setup(build) {
    build.onResolve({ filter: /^\.\/performance$/ }, () => ({
      path: "tracker-no-performance-stub",
      namespace: "tracker-no-performance-stub",
    }));

    build.onLoad(
      { filter: /.*/, namespace: "tracker-no-performance-stub" },
      () => ({
        loader: "ts",
        contents: `
          export function createPerformanceTracker() {
            return {
              buildPayload() { return null; },
              hasVisit() { return false; },
              start() {},
              stop() {},
            };
          }
        `,
      }),
    );
  },
};

function generateOutput(text: string, label: string): string {
  const escaped = JSON.stringify(text);
  return [
    `// Auto-generated by scripts/build-tracker-sdk.ts — DO NOT EDIT`,
    `// Source: src/tracker/sdk.ts (${new Date().toISOString()})`,
    `// Variant: ${label}`,
    `export const SDK_MIN = ${escaped};`,
    "",
  ].join("\n");
}

async function minifySdk(text: string, label: string): Promise<string> {
  const result = await minify(text, {
    ecma: 2020,
    compress: {
      passes: 2,
    },
    mangle: true,
    format: {
      comments: false,
    },
  });
  if (!result.code) {
    throw new Error(`Terser produced empty output for ${label}`);
  }
  return result.code;
}

async function build() {
  rlog.info("Building tracker SDK variants...");
  // Variant A: Full (with performance)
  const fullResult = await esbuild.build({
    ...commonOpts,
    define: { BUILD_PERFORMANCE: "true" },
  });
  const fullText = await minifySdk(
    fullResult.outputFiles![0].text,
    "full (performance included)",
  );
  const fullPath = resolve(root, "src/tracker/sdk.min.ts");
  writeFileSync(
    fullPath,
    generateOutput(fullText, "full (performance included)"),
    "utf-8",
  );
  rlog.success(
    `  sdk.min.ts        : ${(fullText.length / 1024).toFixed(2)} KB (performance: yes)`,
  );

  // Variant B: No performance
  const noPerfResult = await esbuild.build({
    ...commonOpts,
    define: { BUILD_PERFORMANCE: "false" },
    plugins: [noPerformancePlugin],
  });
  const noPerfText = await minifySdk(
    noPerfResult.outputFiles![0].text,
    "no-perf (performance stripped)",
  );
  const noPerfPath = resolve(root, "src/tracker/sdk.no-perf.min.ts");
  writeFileSync(
    noPerfPath,
    generateOutput(noPerfText, "no-perf (performance stripped)"),
    "utf-8",
  );
  rlog.success(
    `  sdk.no-perf.min.ts: ${(noPerfText.length / 1024).toFixed(2)} KB (performance: no)`,
  );

  const saved = fullText.length - noPerfText.length;
  rlog.info(
    `  Saved ${saved} bytes (${(saved / 1024).toFixed(2)} KB) when performance disabled`,
  );
}

build().catch((err) => {
  rlog.error("Failed to build tracker SDK:", err);
  process.exit(1);
});
