/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRuntimeConfigErrorRouteImport } from './routes/$locale.runtime-config-error'
import { Route as LocaleResetPasswordRouteImport } from './routes/$locale.reset-password'
import { Route as LocaleLoginRouteImport } from './routes/$locale.login'
import { Route as LocaleInviteRouteImport } from './routes/$locale.invite'
import { Route as LocaleAppRouteImport } from './routes/$locale.app'
import { Route as LocaleAppIndexRouteImport } from './routes/$locale.app.index'
import { Route as LocaleShareSlugRouteImport } from './routes/$locale.share.$slug'
import { Route as LocaleAppInboxRouteImport } from './routes/$locale.app.inbox'
import { Route as LocaleAppAccountRouteImport } from './routes/$locale.app.account'
import { Route as LocaleAppTeamSlugRouteImport } from './routes/$locale.app.$teamSlug'
import { Route as LocaleShareSlugIndexRouteImport } from './routes/$locale.share.$slug.index'
import { Route as LocaleAppTeamSlugIndexRouteImport } from './routes/$locale.app.$teamSlug.index'
import { Route as LocaleShareSlugRetentionRouteImport } from './routes/$locale.share.$slug.retention'
import { Route as LocaleShareSlugReferrersRouteImport } from './routes/$locale.share.$slug.referrers'
import { Route as LocaleShareSlugPerformanceRouteImport } from './routes/$locale.share.$slug.performance'
import { Route as LocaleShareSlugPagesRouteImport } from './routes/$locale.share.$slug.pages'
import { Route as LocaleShareSlugGeoRouteImport } from './routes/$locale.share.$slug.geo'
import { Route as LocaleShareSlugDevicesRouteImport } from './routes/$locale.share.$slug.devices'
import { Route as LocaleShareSlugCampaignsRouteImport } from './routes/$locale.share.$slug.campaigns'
import { Route as LocaleShareSlugBrowsersRouteImport } from './routes/$locale.share.$slug.browsers'
import { Route as LocaleEmbedsLandingViewRouteImport } from './routes/$locale.embeds.landing.$view'
import { Route as LocaleAppManageVersionUpdatesRouteImport } from './routes/$locale.app.manage.version-updates'
import { Route as LocaleAppManageUsersRouteImport } from './routes/$locale.app.manage.users'
import { Route as LocaleAppManageTeamsRouteImport } from './routes/$locale.app.manage.teams'
import { Route as LocaleAppManageSystemSettingsRouteImport } from './routes/$locale.app.manage.system-settings'
import { Route as LocaleAppManageSystemPerformanceRouteImport } from './routes/$locale.app.manage.system-performance'
import { Route as LocaleAppManageScheduledTasksRouteImport } from './routes/$locale.app.manage.scheduled-tasks'
import { Route as LocaleAppManageRequestObservationRouteImport } from './routes/$locale.app.manage.request-observation'
import { Route as LocaleAppTeamSlugWidgetsRouteImport } from './routes/$locale.app.$teamSlug.widgets'
import { Route as LocaleAppTeamSlugSettingsRouteImport } from './routes/$locale.app.$teamSlug.settings'
import { Route as LocaleAppTeamSlugPublicLinksRouteImport } from './routes/$locale.app.$teamSlug.public-links'
import { Route as LocaleAppTeamSlugNotificationsRouteImport } from './routes/$locale.app.$teamSlug.notifications'
import { Route as LocaleAppTeamSlugMembersRouteImport } from './routes/$locale.app.$teamSlug.members'
import { Route as LocaleAppTeamSlugApiKeysRouteImport } from './routes/$locale.app.$teamSlug.api-keys'
import { Route as LocaleAppTeamSlugSiteSlugRouteImport } from './routes/$locale.app.$teamSlug.$siteSlug'
import { Route as LocaleAppTeamSlugSiteSlugIndexRouteImport } from './routes/$locale.app.$teamSlug.$siteSlug.index'
import { Route as LocaleShareSlugPagesPageKeyRouteImport } from './routes/$locale.share.$slug.pages_.$pageKey'
import { Route as LocaleAppTeamSlugNotificationsEmailPreviewRouteImport } from './routes/$locale.app.$teamSlug.notifications_.email-preview'
import { Route as LocaleAppTeamSlugManageSitesRouteImport } from './routes/$locale.app.$teamSlug.manage.sites'
import { Route as LocaleAppTeamSlugAccountNotificationsRouteImport } from './routes/$locale.app.$teamSlug.account.notifications'
import { Route as LocaleAppTeamSlugSiteSlugVisitorsRouteImport } from './routes/$locale.app.$teamSlug.$siteSlug.visitors'
import { Route as LocaleAppTeamSlugSiteSlugSettingsRouteImport } from './routes/$locale.app.$teamSlug.$siteSlug.settings'
import { Route as LocaleAppTeamSlugSiteSlugSessionsRouteImport } from './routes/$locale.app.$teamSlug.$siteSlug.sessions'
import { Route as LocaleAppTeamSlugSiteSlugRetentionRouteImport } from './routes/$locale.app.$teamSlug.$siteSlug.retention'
import { Route as LocaleAppTeamSlugSiteSlugReferrersRouteImport } from './routes/$locale.app.$teamSlug.$siteSlug.referrers'
import { Route as LocaleAppTeamSlugSiteSlugRealtimeRouteImport } from './routes/$locale.app.$teamSlug.$siteSlug.realtime'
import { Route as LocaleAppTeamSlugSiteSlugPerformanceRouteImport } from './routes/$locale.app.$teamSlug.$siteSlug.performance'
import { Route as LocaleAppTeamSlugSiteSlugPagesRouteImport } from './routes/$locale.app.$teamSlug.$siteSlug.pages'
import { Route as LocaleAppTeamSlugSiteSlugGeoRouteImport } from './routes/$locale.app.$teamSlug.$siteSlug.geo'
import { Route as LocaleAppTeamSlugSiteSlugFunnelsRouteImport } from './routes/$locale.app.$teamSlug.$siteSlug.funnels'
import { Route as LocaleAppTeamSlugSiteSlugEventsRouteImport } from './routes/$locale.app.$teamSlug.$siteSlug.events'
import { Route as LocaleAppTeamSlugSiteSlugDevicesRouteImport } from './routes/$locale.app.$teamSlug.$siteSlug.devices'
import { Route as LocaleAppTeamSlugSiteSlugCampaignsRouteImport } from './routes/$locale.app.$teamSlug.$siteSlug.campaigns'
import { Route as LocaleAppTeamSlugSiteSlugBrowsersRouteImport } from './routes/$locale.app.$teamSlug.$siteSlug.browsers'
import { Route as LocaleAppTeamSlugSiteSlugVisitorsDetailRouteImport } from './routes/$locale.app.$teamSlug.$siteSlug.visitors_.detail'
import { Route as LocaleAppTeamSlugSiteSlugSessionsDetailRouteImport } from './routes/$locale.app.$teamSlug.$siteSlug.sessions_.detail'
import { Route as LocaleAppTeamSlugSiteSlugPagesPageKeyRouteImport } from './routes/$locale.app.$teamSlug.$siteSlug.pages_.$pageKey'
import { Route as LocaleAppTeamSlugSiteSlugEventsDetailRouteImport } from './routes/$locale.app.$teamSlug.$siteSlug.events_.detail'

const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRuntimeConfigErrorRoute =
  LocaleRuntimeConfigErrorRouteImport.update({
    id: '/runtime-config-error',
    path: '/runtime-config-error',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleResetPasswordRoute = LocaleResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleLoginRoute = LocaleLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleInviteRoute = LocaleInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAppRoute = LocaleAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAppIndexRoute = LocaleAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleAppRoute,
} as any)
const LocaleShareSlugRoute = LocaleShareSlugRouteImport.update({
  id: '/share/$slug',
  path: '/share/$slug',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAppInboxRoute = LocaleAppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => LocaleAppRoute,
} as any)
const LocaleAppAccountRoute = LocaleAppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => LocaleAppRoute,
} as any)
const LocaleAppTeamSlugRoute = LocaleAppTeamSlugRouteImport.update({
  id: '/$teamSlug',
  path: '/$teamSlug',
  getParentRoute: () => LocaleAppRoute,
} as any)
const LocaleShareSlugIndexRoute = LocaleShareSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleShareSlugRoute,
} as any)
const LocaleAppTeamSlugIndexRoute = LocaleAppTeamSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleAppTeamSlugRoute,
} as any)
const LocaleShareSlugRetentionRoute =
  LocaleShareSlugRetentionRouteImport.update({
    id: '/retention',
    path: '/retention',
    getParentRoute: () => LocaleShareSlugRoute,
  } as any)
const LocaleShareSlugReferrersRoute =
  LocaleShareSlugReferrersRouteImport.update({
    id: '/referrers',
    path: '/referrers',
    getParentRoute: () => LocaleShareSlugRoute,
  } as any)
const LocaleShareSlugPerformanceRoute =
  LocaleShareSlugPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => LocaleShareSlugRoute,
  } as any)
const LocaleShareSlugPagesRoute = LocaleShareSlugPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => LocaleShareSlugRoute,
} as any)
const LocaleShareSlugGeoRoute = LocaleShareSlugGeoRouteImport.update({
  id: '/geo',
  path: '/geo',
  getParentRoute: () => LocaleShareSlugRoute,
} as any)
const LocaleShareSlugDevicesRoute = LocaleShareSlugDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => LocaleShareSlugRoute,
} as any)
const LocaleShareSlugCampaignsRoute =
  LocaleShareSlugCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => LocaleShareSlugRoute,
  } as any)
const LocaleShareSlugBrowsersRoute = LocaleShareSlugBrowsersRouteImport.update({
  id: '/browsers',
  path: '/browsers',
  getParentRoute: () => LocaleShareSlugRoute,
} as any)
const LocaleEmbedsLandingViewRoute = LocaleEmbedsLandingViewRouteImport.update({
  id: '/embeds/landing/$view',
  path: '/embeds/landing/$view',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAppManageVersionUpdatesRoute =
  LocaleAppManageVersionUpdatesRouteImport.update({
    id: '/manage/version-updates',
    path: '/manage/version-updates',
    getParentRoute: () => LocaleAppRoute,
  } as any)
const LocaleAppManageUsersRoute = LocaleAppManageUsersRouteImport.update({
  id: '/manage/users',
  path: '/manage/users',
  getParentRoute: () => LocaleAppRoute,
} as any)
const LocaleAppManageTeamsRoute = LocaleAppManageTeamsRouteImport.update({
  id: '/manage/teams',
  path: '/manage/teams',
  getParentRoute: () => LocaleAppRoute,
} as any)
const LocaleAppManageSystemSettingsRoute =
  LocaleAppManageSystemSettingsRouteImport.update({
    id: '/manage/system-settings',
    path: '/manage/system-settings',
    getParentRoute: () => LocaleAppRoute,
  } as any)
const LocaleAppManageSystemPerformanceRoute =
  LocaleAppManageSystemPerformanceRouteImport.update({
    id: '/manage/system-performance',
    path: '/manage/system-performance',
    getParentRoute: () => LocaleAppRoute,
  } as any)
const LocaleAppManageScheduledTasksRoute =
  LocaleAppManageScheduledTasksRouteImport.update({
    id: '/manage/scheduled-tasks',
    path: '/manage/scheduled-tasks',
    getParentRoute: () => LocaleAppRoute,
  } as any)
const LocaleAppManageRequestObservationRoute =
  LocaleAppManageRequestObservationRouteImport.update({
    id: '/manage/request-observation',
    path: '/manage/request-observation',
    getParentRoute: () => LocaleAppRoute,
  } as any)
const LocaleAppTeamSlugWidgetsRoute =
  LocaleAppTeamSlugWidgetsRouteImport.update({
    id: '/widgets',
    path: '/widgets',
    getParentRoute: () => LocaleAppTeamSlugRoute,
  } as any)
const LocaleAppTeamSlugSettingsRoute =
  LocaleAppTeamSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LocaleAppTeamSlugRoute,
  } as any)
const LocaleAppTeamSlugPublicLinksRoute =
  LocaleAppTeamSlugPublicLinksRouteImport.update({
    id: '/public-links',
    path: '/public-links',
    getParentRoute: () => LocaleAppTeamSlugRoute,
  } as any)
const LocaleAppTeamSlugNotificationsRoute =
  LocaleAppTeamSlugNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => LocaleAppTeamSlugRoute,
  } as any)
const LocaleAppTeamSlugMembersRoute =
  LocaleAppTeamSlugMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => LocaleAppTeamSlugRoute,
  } as any)
const LocaleAppTeamSlugApiKeysRoute =
  LocaleAppTeamSlugApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => LocaleAppTeamSlugRoute,
  } as any)
const LocaleAppTeamSlugSiteSlugRoute =
  LocaleAppTeamSlugSiteSlugRouteImport.update({
    id: '/$siteSlug',
    path: '/$siteSlug',
    getParentRoute: () => LocaleAppTeamSlugRoute,
  } as any)
const LocaleAppTeamSlugSiteSlugIndexRoute =
  LocaleAppTeamSlugSiteSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LocaleAppTeamSlugSiteSlugRoute,
  } as any)
const LocaleShareSlugPagesPageKeyRoute =
  LocaleShareSlugPagesPageKeyRouteImport.update({
    id: '/pages_/$pageKey',
    path: '/pages/$pageKey',
    getParentRoute: () => LocaleShareSlugRoute,
  } as any)
const LocaleAppTeamSlugNotificationsEmailPreviewRoute =
  LocaleAppTeamSlugNotificationsEmailPreviewRouteImport.update({
    id: '/notifications_/email-preview',
    path: '/notifications/email-preview',
    getParentRoute: () => LocaleAppTeamSlugRoute,
  } as any)
const LocaleAppTeamSlugManageSitesRoute =
  LocaleAppTeamSlugManageSitesRouteImport.update({
    id: '/manage/sites',
    path: '/manage/sites',
    getParentRoute: () => LocaleAppTeamSlugRoute,
  } as any)
const LocaleAppTeamSlugAccountNotificationsRoute =
  LocaleAppTeamSlugAccountNotificationsRouteImport.update({
    id: '/account/notifications',
    path: '/account/notifications',
    getParentRoute: () => LocaleAppTeamSlugRoute,
  } as any)
const LocaleAppTeamSlugSiteSlugVisitorsRoute =
  LocaleAppTeamSlugSiteSlugVisitorsRouteImport.update({
    id: '/visitors',
    path: '/visitors',
    getParentRoute: () => LocaleAppTeamSlugSiteSlugRoute,
  } as any)
const LocaleAppTeamSlugSiteSlugSettingsRoute =
  LocaleAppTeamSlugSiteSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LocaleAppTeamSlugSiteSlugRoute,
  } as any)
const LocaleAppTeamSlugSiteSlugSessionsRoute =
  LocaleAppTeamSlugSiteSlugSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => LocaleAppTeamSlugSiteSlugRoute,
  } as any)
const LocaleAppTeamSlugSiteSlugRetentionRoute =
  LocaleAppTeamSlugSiteSlugRetentionRouteImport.update({
    id: '/retention',
    path: '/retention',
    getParentRoute: () => LocaleAppTeamSlugSiteSlugRoute,
  } as any)
const LocaleAppTeamSlugSiteSlugReferrersRoute =
  LocaleAppTeamSlugSiteSlugReferrersRouteImport.update({
    id: '/referrers',
    path: '/referrers',
    getParentRoute: () => LocaleAppTeamSlugSiteSlugRoute,
  } as any)
const LocaleAppTeamSlugSiteSlugRealtimeRoute =
  LocaleAppTeamSlugSiteSlugRealtimeRouteImport.update({
    id: '/realtime',
    path: '/realtime',
    getParentRoute: () => LocaleAppTeamSlugSiteSlugRoute,
  } as any)
const LocaleAppTeamSlugSiteSlugPerformanceRoute =
  LocaleAppTeamSlugSiteSlugPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => LocaleAppTeamSlugSiteSlugRoute,
  } as any)
const LocaleAppTeamSlugSiteSlugPagesRoute =
  LocaleAppTeamSlugSiteSlugPagesRouteImport.update({
    id: '/pages',
    path: '/pages',
    getParentRoute: () => LocaleAppTeamSlugSiteSlugRoute,
  } as any)
const LocaleAppTeamSlugSiteSlugGeoRoute =
  LocaleAppTeamSlugSiteSlugGeoRouteImport.update({
    id: '/geo',
    path: '/geo',
    getParentRoute: () => LocaleAppTeamSlugSiteSlugRoute,
  } as any)
const LocaleAppTeamSlugSiteSlugFunnelsRoute =
  LocaleAppTeamSlugSiteSlugFunnelsRouteImport.update({
    id: '/funnels',
    path: '/funnels',
    getParentRoute: () => LocaleAppTeamSlugSiteSlugRoute,
  } as any)
const LocaleAppTeamSlugSiteSlugEventsRoute =
  LocaleAppTeamSlugSiteSlugEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => LocaleAppTeamSlugSiteSlugRoute,
  } as any)
const LocaleAppTeamSlugSiteSlugDevicesRoute =
  LocaleAppTeamSlugSiteSlugDevicesRouteImport.update({
    id: '/devices',
    path: '/devices',
    getParentRoute: () => LocaleAppTeamSlugSiteSlugRoute,
  } as any)
const LocaleAppTeamSlugSiteSlugCampaignsRoute =
  LocaleAppTeamSlugSiteSlugCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => LocaleAppTeamSlugSiteSlugRoute,
  } as any)
const LocaleAppTeamSlugSiteSlugBrowsersRoute =
  LocaleAppTeamSlugSiteSlugBrowsersRouteImport.update({
    id: '/browsers',
    path: '/browsers',
    getParentRoute: () => LocaleAppTeamSlugSiteSlugRoute,
  } as any)
const LocaleAppTeamSlugSiteSlugVisitorsDetailRoute =
  LocaleAppTeamSlugSiteSlugVisitorsDetailRouteImport.update({
    id: '/visitors_/detail',
    path: '/visitors/detail',
    getParentRoute: () => LocaleAppTeamSlugSiteSlugRoute,
  } as any)
const LocaleAppTeamSlugSiteSlugSessionsDetailRoute =
  LocaleAppTeamSlugSiteSlugSessionsDetailRouteImport.update({
    id: '/sessions_/detail',
    path: '/sessions/detail',
    getParentRoute: () => LocaleAppTeamSlugSiteSlugRoute,
  } as any)
const LocaleAppTeamSlugSiteSlugPagesPageKeyRoute =
  LocaleAppTeamSlugSiteSlugPagesPageKeyRouteImport.update({
    id: '/pages_/$pageKey',
    path: '/pages/$pageKey',
    getParentRoute: () => LocaleAppTeamSlugSiteSlugRoute,
  } as any)
const LocaleAppTeamSlugSiteSlugEventsDetailRoute =
  LocaleAppTeamSlugSiteSlugEventsDetailRouteImport.update({
    id: '/events_/detail',
    path: '/events/detail',
    getParentRoute: () => LocaleAppTeamSlugSiteSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/app': typeof LocaleAppRouteWithChildren
  '/$locale/invite': typeof LocaleInviteRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/reset-password': typeof LocaleResetPasswordRoute
  '/$locale/runtime-config-error': typeof LocaleRuntimeConfigErrorRoute
  '/$locale/app/$teamSlug': typeof LocaleAppTeamSlugRouteWithChildren
  '/$locale/app/account': typeof LocaleAppAccountRoute
  '/$locale/app/inbox': typeof LocaleAppInboxRoute
  '/$locale/share/$slug': typeof LocaleShareSlugRouteWithChildren
  '/$locale/app/': typeof LocaleAppIndexRoute
  '/$locale/app/$teamSlug/$siteSlug': typeof LocaleAppTeamSlugSiteSlugRouteWithChildren
  '/$locale/app/$teamSlug/api-keys': typeof LocaleAppTeamSlugApiKeysRoute
  '/$locale/app/$teamSlug/members': typeof LocaleAppTeamSlugMembersRoute
  '/$locale/app/$teamSlug/notifications': typeof LocaleAppTeamSlugNotificationsRoute
  '/$locale/app/$teamSlug/public-links': typeof LocaleAppTeamSlugPublicLinksRoute
  '/$locale/app/$teamSlug/settings': typeof LocaleAppTeamSlugSettingsRoute
  '/$locale/app/$teamSlug/widgets': typeof LocaleAppTeamSlugWidgetsRoute
  '/$locale/app/manage/request-observation': typeof LocaleAppManageRequestObservationRoute
  '/$locale/app/manage/scheduled-tasks': typeof LocaleAppManageScheduledTasksRoute
  '/$locale/app/manage/system-performance': typeof LocaleAppManageSystemPerformanceRoute
  '/$locale/app/manage/system-settings': typeof LocaleAppManageSystemSettingsRoute
  '/$locale/app/manage/teams': typeof LocaleAppManageTeamsRoute
  '/$locale/app/manage/users': typeof LocaleAppManageUsersRoute
  '/$locale/app/manage/version-updates': typeof LocaleAppManageVersionUpdatesRoute
  '/$locale/embeds/landing/$view': typeof LocaleEmbedsLandingViewRoute
  '/$locale/share/$slug/browsers': typeof LocaleShareSlugBrowsersRoute
  '/$locale/share/$slug/campaigns': typeof LocaleShareSlugCampaignsRoute
  '/$locale/share/$slug/devices': typeof LocaleShareSlugDevicesRoute
  '/$locale/share/$slug/geo': typeof LocaleShareSlugGeoRoute
  '/$locale/share/$slug/pages': typeof LocaleShareSlugPagesRoute
  '/$locale/share/$slug/performance': typeof LocaleShareSlugPerformanceRoute
  '/$locale/share/$slug/referrers': typeof LocaleShareSlugReferrersRoute
  '/$locale/share/$slug/retention': typeof LocaleShareSlugRetentionRoute
  '/$locale/app/$teamSlug/': typeof LocaleAppTeamSlugIndexRoute
  '/$locale/share/$slug/': typeof LocaleShareSlugIndexRoute
  '/$locale/app/$teamSlug/$siteSlug/browsers': typeof LocaleAppTeamSlugSiteSlugBrowsersRoute
  '/$locale/app/$teamSlug/$siteSlug/campaigns': typeof LocaleAppTeamSlugSiteSlugCampaignsRoute
  '/$locale/app/$teamSlug/$siteSlug/devices': typeof LocaleAppTeamSlugSiteSlugDevicesRoute
  '/$locale/app/$teamSlug/$siteSlug/events': typeof LocaleAppTeamSlugSiteSlugEventsRoute
  '/$locale/app/$teamSlug/$siteSlug/funnels': typeof LocaleAppTeamSlugSiteSlugFunnelsRoute
  '/$locale/app/$teamSlug/$siteSlug/geo': typeof LocaleAppTeamSlugSiteSlugGeoRoute
  '/$locale/app/$teamSlug/$siteSlug/pages': typeof LocaleAppTeamSlugSiteSlugPagesRoute
  '/$locale/app/$teamSlug/$siteSlug/performance': typeof LocaleAppTeamSlugSiteSlugPerformanceRoute
  '/$locale/app/$teamSlug/$siteSlug/realtime': typeof LocaleAppTeamSlugSiteSlugRealtimeRoute
  '/$locale/app/$teamSlug/$siteSlug/referrers': typeof LocaleAppTeamSlugSiteSlugReferrersRoute
  '/$locale/app/$teamSlug/$siteSlug/retention': typeof LocaleAppTeamSlugSiteSlugRetentionRoute
  '/$locale/app/$teamSlug/$siteSlug/sessions': typeof LocaleAppTeamSlugSiteSlugSessionsRoute
  '/$locale/app/$teamSlug/$siteSlug/settings': typeof LocaleAppTeamSlugSiteSlugSettingsRoute
  '/$locale/app/$teamSlug/$siteSlug/visitors': typeof LocaleAppTeamSlugSiteSlugVisitorsRoute
  '/$locale/app/$teamSlug/account/notifications': typeof LocaleAppTeamSlugAccountNotificationsRoute
  '/$locale/app/$teamSlug/manage/sites': typeof LocaleAppTeamSlugManageSitesRoute
  '/$locale/app/$teamSlug/notifications/email-preview': typeof LocaleAppTeamSlugNotificationsEmailPreviewRoute
  '/$locale/share/$slug/pages/$pageKey': typeof LocaleShareSlugPagesPageKeyRoute
  '/$locale/app/$teamSlug/$siteSlug/': typeof LocaleAppTeamSlugSiteSlugIndexRoute
  '/$locale/app/$teamSlug/$siteSlug/events/detail': typeof LocaleAppTeamSlugSiteSlugEventsDetailRoute
  '/$locale/app/$teamSlug/$siteSlug/pages/$pageKey': typeof LocaleAppTeamSlugSiteSlugPagesPageKeyRoute
  '/$locale/app/$teamSlug/$siteSlug/sessions/detail': typeof LocaleAppTeamSlugSiteSlugSessionsDetailRoute
  '/$locale/app/$teamSlug/$siteSlug/visitors/detail': typeof LocaleAppTeamSlugSiteSlugVisitorsDetailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/invite': typeof LocaleInviteRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/reset-password': typeof LocaleResetPasswordRoute
  '/$locale/runtime-config-error': typeof LocaleRuntimeConfigErrorRoute
  '/$locale/app/account': typeof LocaleAppAccountRoute
  '/$locale/app/inbox': typeof LocaleAppInboxRoute
  '/$locale/app': typeof LocaleAppIndexRoute
  '/$locale/app/$teamSlug/api-keys': typeof LocaleAppTeamSlugApiKeysRoute
  '/$locale/app/$teamSlug/members': typeof LocaleAppTeamSlugMembersRoute
  '/$locale/app/$teamSlug/notifications': typeof LocaleAppTeamSlugNotificationsRoute
  '/$locale/app/$teamSlug/public-links': typeof LocaleAppTeamSlugPublicLinksRoute
  '/$locale/app/$teamSlug/settings': typeof LocaleAppTeamSlugSettingsRoute
  '/$locale/app/$teamSlug/widgets': typeof LocaleAppTeamSlugWidgetsRoute
  '/$locale/app/manage/request-observation': typeof LocaleAppManageRequestObservationRoute
  '/$locale/app/manage/scheduled-tasks': typeof LocaleAppManageScheduledTasksRoute
  '/$locale/app/manage/system-performance': typeof LocaleAppManageSystemPerformanceRoute
  '/$locale/app/manage/system-settings': typeof LocaleAppManageSystemSettingsRoute
  '/$locale/app/manage/teams': typeof LocaleAppManageTeamsRoute
  '/$locale/app/manage/users': typeof LocaleAppManageUsersRoute
  '/$locale/app/manage/version-updates': typeof LocaleAppManageVersionUpdatesRoute
  '/$locale/embeds/landing/$view': typeof LocaleEmbedsLandingViewRoute
  '/$locale/share/$slug/browsers': typeof LocaleShareSlugBrowsersRoute
  '/$locale/share/$slug/campaigns': typeof LocaleShareSlugCampaignsRoute
  '/$locale/share/$slug/devices': typeof LocaleShareSlugDevicesRoute
  '/$locale/share/$slug/geo': typeof LocaleShareSlugGeoRoute
  '/$locale/share/$slug/pages': typeof LocaleShareSlugPagesRoute
  '/$locale/share/$slug/performance': typeof LocaleShareSlugPerformanceRoute
  '/$locale/share/$slug/referrers': typeof LocaleShareSlugReferrersRoute
  '/$locale/share/$slug/retention': typeof LocaleShareSlugRetentionRoute
  '/$locale/app/$teamSlug': typeof LocaleAppTeamSlugIndexRoute
  '/$locale/share/$slug': typeof LocaleShareSlugIndexRoute
  '/$locale/app/$teamSlug/$siteSlug/browsers': typeof LocaleAppTeamSlugSiteSlugBrowsersRoute
  '/$locale/app/$teamSlug/$siteSlug/campaigns': typeof LocaleAppTeamSlugSiteSlugCampaignsRoute
  '/$locale/app/$teamSlug/$siteSlug/devices': typeof LocaleAppTeamSlugSiteSlugDevicesRoute
  '/$locale/app/$teamSlug/$siteSlug/events': typeof LocaleAppTeamSlugSiteSlugEventsRoute
  '/$locale/app/$teamSlug/$siteSlug/funnels': typeof LocaleAppTeamSlugSiteSlugFunnelsRoute
  '/$locale/app/$teamSlug/$siteSlug/geo': typeof LocaleAppTeamSlugSiteSlugGeoRoute
  '/$locale/app/$teamSlug/$siteSlug/pages': typeof LocaleAppTeamSlugSiteSlugPagesRoute
  '/$locale/app/$teamSlug/$siteSlug/performance': typeof LocaleAppTeamSlugSiteSlugPerformanceRoute
  '/$locale/app/$teamSlug/$siteSlug/realtime': typeof LocaleAppTeamSlugSiteSlugRealtimeRoute
  '/$locale/app/$teamSlug/$siteSlug/referrers': typeof LocaleAppTeamSlugSiteSlugReferrersRoute
  '/$locale/app/$teamSlug/$siteSlug/retention': typeof LocaleAppTeamSlugSiteSlugRetentionRoute
  '/$locale/app/$teamSlug/$siteSlug/sessions': typeof LocaleAppTeamSlugSiteSlugSessionsRoute
  '/$locale/app/$teamSlug/$siteSlug/settings': typeof LocaleAppTeamSlugSiteSlugSettingsRoute
  '/$locale/app/$teamSlug/$siteSlug/visitors': typeof LocaleAppTeamSlugSiteSlugVisitorsRoute
  '/$locale/app/$teamSlug/account/notifications': typeof LocaleAppTeamSlugAccountNotificationsRoute
  '/$locale/app/$teamSlug/manage/sites': typeof LocaleAppTeamSlugManageSitesRoute
  '/$locale/app/$teamSlug/notifications/email-preview': typeof LocaleAppTeamSlugNotificationsEmailPreviewRoute
  '/$locale/share/$slug/pages/$pageKey': typeof LocaleShareSlugPagesPageKeyRoute
  '/$locale/app/$teamSlug/$siteSlug': typeof LocaleAppTeamSlugSiteSlugIndexRoute
  '/$locale/app/$teamSlug/$siteSlug/events/detail': typeof LocaleAppTeamSlugSiteSlugEventsDetailRoute
  '/$locale/app/$teamSlug/$siteSlug/pages/$pageKey': typeof LocaleAppTeamSlugSiteSlugPagesPageKeyRoute
  '/$locale/app/$teamSlug/$siteSlug/sessions/detail': typeof LocaleAppTeamSlugSiteSlugSessionsDetailRoute
  '/$locale/app/$teamSlug/$siteSlug/visitors/detail': typeof LocaleAppTeamSlugSiteSlugVisitorsDetailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/app': typeof LocaleAppRouteWithChildren
  '/$locale/invite': typeof LocaleInviteRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/reset-password': typeof LocaleResetPasswordRoute
  '/$locale/runtime-config-error': typeof LocaleRuntimeConfigErrorRoute
  '/$locale/app/$teamSlug': typeof LocaleAppTeamSlugRouteWithChildren
  '/$locale/app/account': typeof LocaleAppAccountRoute
  '/$locale/app/inbox': typeof LocaleAppInboxRoute
  '/$locale/share/$slug': typeof LocaleShareSlugRouteWithChildren
  '/$locale/app/': typeof LocaleAppIndexRoute
  '/$locale/app/$teamSlug/$siteSlug': typeof LocaleAppTeamSlugSiteSlugRouteWithChildren
  '/$locale/app/$teamSlug/api-keys': typeof LocaleAppTeamSlugApiKeysRoute
  '/$locale/app/$teamSlug/members': typeof LocaleAppTeamSlugMembersRoute
  '/$locale/app/$teamSlug/notifications': typeof LocaleAppTeamSlugNotificationsRoute
  '/$locale/app/$teamSlug/public-links': typeof LocaleAppTeamSlugPublicLinksRoute
  '/$locale/app/$teamSlug/settings': typeof LocaleAppTeamSlugSettingsRoute
  '/$locale/app/$teamSlug/widgets': typeof LocaleAppTeamSlugWidgetsRoute
  '/$locale/app/manage/request-observation': typeof LocaleAppManageRequestObservationRoute
  '/$locale/app/manage/scheduled-tasks': typeof LocaleAppManageScheduledTasksRoute
  '/$locale/app/manage/system-performance': typeof LocaleAppManageSystemPerformanceRoute
  '/$locale/app/manage/system-settings': typeof LocaleAppManageSystemSettingsRoute
  '/$locale/app/manage/teams': typeof LocaleAppManageTeamsRoute
  '/$locale/app/manage/users': typeof LocaleAppManageUsersRoute
  '/$locale/app/manage/version-updates': typeof LocaleAppManageVersionUpdatesRoute
  '/$locale/embeds/landing/$view': typeof LocaleEmbedsLandingViewRoute
  '/$locale/share/$slug/browsers': typeof LocaleShareSlugBrowsersRoute
  '/$locale/share/$slug/campaigns': typeof LocaleShareSlugCampaignsRoute
  '/$locale/share/$slug/devices': typeof LocaleShareSlugDevicesRoute
  '/$locale/share/$slug/geo': typeof LocaleShareSlugGeoRoute
  '/$locale/share/$slug/pages': typeof LocaleShareSlugPagesRoute
  '/$locale/share/$slug/performance': typeof LocaleShareSlugPerformanceRoute
  '/$locale/share/$slug/referrers': typeof LocaleShareSlugReferrersRoute
  '/$locale/share/$slug/retention': typeof LocaleShareSlugRetentionRoute
  '/$locale/app/$teamSlug/': typeof LocaleAppTeamSlugIndexRoute
  '/$locale/share/$slug/': typeof LocaleShareSlugIndexRoute
  '/$locale/app/$teamSlug/$siteSlug/browsers': typeof LocaleAppTeamSlugSiteSlugBrowsersRoute
  '/$locale/app/$teamSlug/$siteSlug/campaigns': typeof LocaleAppTeamSlugSiteSlugCampaignsRoute
  '/$locale/app/$teamSlug/$siteSlug/devices': typeof LocaleAppTeamSlugSiteSlugDevicesRoute
  '/$locale/app/$teamSlug/$siteSlug/events': typeof LocaleAppTeamSlugSiteSlugEventsRoute
  '/$locale/app/$teamSlug/$siteSlug/funnels': typeof LocaleAppTeamSlugSiteSlugFunnelsRoute
  '/$locale/app/$teamSlug/$siteSlug/geo': typeof LocaleAppTeamSlugSiteSlugGeoRoute
  '/$locale/app/$teamSlug/$siteSlug/pages': typeof LocaleAppTeamSlugSiteSlugPagesRoute
  '/$locale/app/$teamSlug/$siteSlug/performance': typeof LocaleAppTeamSlugSiteSlugPerformanceRoute
  '/$locale/app/$teamSlug/$siteSlug/realtime': typeof LocaleAppTeamSlugSiteSlugRealtimeRoute
  '/$locale/app/$teamSlug/$siteSlug/referrers': typeof LocaleAppTeamSlugSiteSlugReferrersRoute
  '/$locale/app/$teamSlug/$siteSlug/retention': typeof LocaleAppTeamSlugSiteSlugRetentionRoute
  '/$locale/app/$teamSlug/$siteSlug/sessions': typeof LocaleAppTeamSlugSiteSlugSessionsRoute
  '/$locale/app/$teamSlug/$siteSlug/settings': typeof LocaleAppTeamSlugSiteSlugSettingsRoute
  '/$locale/app/$teamSlug/$siteSlug/visitors': typeof LocaleAppTeamSlugSiteSlugVisitorsRoute
  '/$locale/app/$teamSlug/account/notifications': typeof LocaleAppTeamSlugAccountNotificationsRoute
  '/$locale/app/$teamSlug/manage/sites': typeof LocaleAppTeamSlugManageSitesRoute
  '/$locale/app/$teamSlug/notifications_/email-preview': typeof LocaleAppTeamSlugNotificationsEmailPreviewRoute
  '/$locale/share/$slug/pages_/$pageKey': typeof LocaleShareSlugPagesPageKeyRoute
  '/$locale/app/$teamSlug/$siteSlug/': typeof LocaleAppTeamSlugSiteSlugIndexRoute
  '/$locale/app/$teamSlug/$siteSlug/events_/detail': typeof LocaleAppTeamSlugSiteSlugEventsDetailRoute
  '/$locale/app/$teamSlug/$siteSlug/pages_/$pageKey': typeof LocaleAppTeamSlugSiteSlugPagesPageKeyRoute
  '/$locale/app/$teamSlug/$siteSlug/sessions_/detail': typeof LocaleAppTeamSlugSiteSlugSessionsDetailRoute
  '/$locale/app/$teamSlug/$siteSlug/visitors_/detail': typeof LocaleAppTeamSlugSiteSlugVisitorsDetailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/app'
    | '/$locale/invite'
    | '/$locale/login'
    | '/$locale/reset-password'
    | '/$locale/runtime-config-error'
    | '/$locale/app/$teamSlug'
    | '/$locale/app/account'
    | '/$locale/app/inbox'
    | '/$locale/share/$slug'
    | '/$locale/app/'
    | '/$locale/app/$teamSlug/$siteSlug'
    | '/$locale/app/$teamSlug/api-keys'
    | '/$locale/app/$teamSlug/members'
    | '/$locale/app/$teamSlug/notifications'
    | '/$locale/app/$teamSlug/public-links'
    | '/$locale/app/$teamSlug/settings'
    | '/$locale/app/$teamSlug/widgets'
    | '/$locale/app/manage/request-observation'
    | '/$locale/app/manage/scheduled-tasks'
    | '/$locale/app/manage/system-performance'
    | '/$locale/app/manage/system-settings'
    | '/$locale/app/manage/teams'
    | '/$locale/app/manage/users'
    | '/$locale/app/manage/version-updates'
    | '/$locale/embeds/landing/$view'
    | '/$locale/share/$slug/browsers'
    | '/$locale/share/$slug/campaigns'
    | '/$locale/share/$slug/devices'
    | '/$locale/share/$slug/geo'
    | '/$locale/share/$slug/pages'
    | '/$locale/share/$slug/performance'
    | '/$locale/share/$slug/referrers'
    | '/$locale/share/$slug/retention'
    | '/$locale/app/$teamSlug/'
    | '/$locale/share/$slug/'
    | '/$locale/app/$teamSlug/$siteSlug/browsers'
    | '/$locale/app/$teamSlug/$siteSlug/campaigns'
    | '/$locale/app/$teamSlug/$siteSlug/devices'
    | '/$locale/app/$teamSlug/$siteSlug/events'
    | '/$locale/app/$teamSlug/$siteSlug/funnels'
    | '/$locale/app/$teamSlug/$siteSlug/geo'
    | '/$locale/app/$teamSlug/$siteSlug/pages'
    | '/$locale/app/$teamSlug/$siteSlug/performance'
    | '/$locale/app/$teamSlug/$siteSlug/realtime'
    | '/$locale/app/$teamSlug/$siteSlug/referrers'
    | '/$locale/app/$teamSlug/$siteSlug/retention'
    | '/$locale/app/$teamSlug/$siteSlug/sessions'
    | '/$locale/app/$teamSlug/$siteSlug/settings'
    | '/$locale/app/$teamSlug/$siteSlug/visitors'
    | '/$locale/app/$teamSlug/account/notifications'
    | '/$locale/app/$teamSlug/manage/sites'
    | '/$locale/app/$teamSlug/notifications/email-preview'
    | '/$locale/share/$slug/pages/$pageKey'
    | '/$locale/app/$teamSlug/$siteSlug/'
    | '/$locale/app/$teamSlug/$siteSlug/events/detail'
    | '/$locale/app/$teamSlug/$siteSlug/pages/$pageKey'
    | '/$locale/app/$teamSlug/$siteSlug/sessions/detail'
    | '/$locale/app/$teamSlug/$siteSlug/visitors/detail'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale'
    | '/$locale/invite'
    | '/$locale/login'
    | '/$locale/reset-password'
    | '/$locale/runtime-config-error'
    | '/$locale/app/account'
    | '/$locale/app/inbox'
    | '/$locale/app'
    | '/$locale/app/$teamSlug/api-keys'
    | '/$locale/app/$teamSlug/members'
    | '/$locale/app/$teamSlug/notifications'
    | '/$locale/app/$teamSlug/public-links'
    | '/$locale/app/$teamSlug/settings'
    | '/$locale/app/$teamSlug/widgets'
    | '/$locale/app/manage/request-observation'
    | '/$locale/app/manage/scheduled-tasks'
    | '/$locale/app/manage/system-performance'
    | '/$locale/app/manage/system-settings'
    | '/$locale/app/manage/teams'
    | '/$locale/app/manage/users'
    | '/$locale/app/manage/version-updates'
    | '/$locale/embeds/landing/$view'
    | '/$locale/share/$slug/browsers'
    | '/$locale/share/$slug/campaigns'
    | '/$locale/share/$slug/devices'
    | '/$locale/share/$slug/geo'
    | '/$locale/share/$slug/pages'
    | '/$locale/share/$slug/performance'
    | '/$locale/share/$slug/referrers'
    | '/$locale/share/$slug/retention'
    | '/$locale/app/$teamSlug'
    | '/$locale/share/$slug'
    | '/$locale/app/$teamSlug/$siteSlug/browsers'
    | '/$locale/app/$teamSlug/$siteSlug/campaigns'
    | '/$locale/app/$teamSlug/$siteSlug/devices'
    | '/$locale/app/$teamSlug/$siteSlug/events'
    | '/$locale/app/$teamSlug/$siteSlug/funnels'
    | '/$locale/app/$teamSlug/$siteSlug/geo'
    | '/$locale/app/$teamSlug/$siteSlug/pages'
    | '/$locale/app/$teamSlug/$siteSlug/performance'
    | '/$locale/app/$teamSlug/$siteSlug/realtime'
    | '/$locale/app/$teamSlug/$siteSlug/referrers'
    | '/$locale/app/$teamSlug/$siteSlug/retention'
    | '/$locale/app/$teamSlug/$siteSlug/sessions'
    | '/$locale/app/$teamSlug/$siteSlug/settings'
    | '/$locale/app/$teamSlug/$siteSlug/visitors'
    | '/$locale/app/$teamSlug/account/notifications'
    | '/$locale/app/$teamSlug/manage/sites'
    | '/$locale/app/$teamSlug/notifications/email-preview'
    | '/$locale/share/$slug/pages/$pageKey'
    | '/$locale/app/$teamSlug/$siteSlug'
    | '/$locale/app/$teamSlug/$siteSlug/events/detail'
    | '/$locale/app/$teamSlug/$siteSlug/pages/$pageKey'
    | '/$locale/app/$teamSlug/$siteSlug/sessions/detail'
    | '/$locale/app/$teamSlug/$siteSlug/visitors/detail'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/app'
    | '/$locale/invite'
    | '/$locale/login'
    | '/$locale/reset-password'
    | '/$locale/runtime-config-error'
    | '/$locale/app/$teamSlug'
    | '/$locale/app/account'
    | '/$locale/app/inbox'
    | '/$locale/share/$slug'
    | '/$locale/app/'
    | '/$locale/app/$teamSlug/$siteSlug'
    | '/$locale/app/$teamSlug/api-keys'
    | '/$locale/app/$teamSlug/members'
    | '/$locale/app/$teamSlug/notifications'
    | '/$locale/app/$teamSlug/public-links'
    | '/$locale/app/$teamSlug/settings'
    | '/$locale/app/$teamSlug/widgets'
    | '/$locale/app/manage/request-observation'
    | '/$locale/app/manage/scheduled-tasks'
    | '/$locale/app/manage/system-performance'
    | '/$locale/app/manage/system-settings'
    | '/$locale/app/manage/teams'
    | '/$locale/app/manage/users'
    | '/$locale/app/manage/version-updates'
    | '/$locale/embeds/landing/$view'
    | '/$locale/share/$slug/browsers'
    | '/$locale/share/$slug/campaigns'
    | '/$locale/share/$slug/devices'
    | '/$locale/share/$slug/geo'
    | '/$locale/share/$slug/pages'
    | '/$locale/share/$slug/performance'
    | '/$locale/share/$slug/referrers'
    | '/$locale/share/$slug/retention'
    | '/$locale/app/$teamSlug/'
    | '/$locale/share/$slug/'
    | '/$locale/app/$teamSlug/$siteSlug/browsers'
    | '/$locale/app/$teamSlug/$siteSlug/campaigns'
    | '/$locale/app/$teamSlug/$siteSlug/devices'
    | '/$locale/app/$teamSlug/$siteSlug/events'
    | '/$locale/app/$teamSlug/$siteSlug/funnels'
    | '/$locale/app/$teamSlug/$siteSlug/geo'
    | '/$locale/app/$teamSlug/$siteSlug/pages'
    | '/$locale/app/$teamSlug/$siteSlug/performance'
    | '/$locale/app/$teamSlug/$siteSlug/realtime'
    | '/$locale/app/$teamSlug/$siteSlug/referrers'
    | '/$locale/app/$teamSlug/$siteSlug/retention'
    | '/$locale/app/$teamSlug/$siteSlug/sessions'
    | '/$locale/app/$teamSlug/$siteSlug/settings'
    | '/$locale/app/$teamSlug/$siteSlug/visitors'
    | '/$locale/app/$teamSlug/account/notifications'
    | '/$locale/app/$teamSlug/manage/sites'
    | '/$locale/app/$teamSlug/notifications_/email-preview'
    | '/$locale/share/$slug/pages_/$pageKey'
    | '/$locale/app/$teamSlug/$siteSlug/'
    | '/$locale/app/$teamSlug/$siteSlug/events_/detail'
    | '/$locale/app/$teamSlug/$siteSlug/pages_/$pageKey'
    | '/$locale/app/$teamSlug/$siteSlug/sessions_/detail'
    | '/$locale/app/$teamSlug/$siteSlug/visitors_/detail'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/runtime-config-error': {
      id: '/$locale/runtime-config-error'
      path: '/runtime-config-error'
      fullPath: '/$locale/runtime-config-error'
      preLoaderRoute: typeof LocaleRuntimeConfigErrorRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/reset-password': {
      id: '/$locale/reset-password'
      path: '/reset-password'
      fullPath: '/$locale/reset-password'
      preLoaderRoute: typeof LocaleResetPasswordRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/login': {
      id: '/$locale/login'
      path: '/login'
      fullPath: '/$locale/login'
      preLoaderRoute: typeof LocaleLoginRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/invite': {
      id: '/$locale/invite'
      path: '/invite'
      fullPath: '/$locale/invite'
      preLoaderRoute: typeof LocaleInviteRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/app': {
      id: '/$locale/app'
      path: '/app'
      fullPath: '/$locale/app'
      preLoaderRoute: typeof LocaleAppRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/app/': {
      id: '/$locale/app/'
      path: '/'
      fullPath: '/$locale/app/'
      preLoaderRoute: typeof LocaleAppIndexRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/share/$slug': {
      id: '/$locale/share/$slug'
      path: '/share/$slug'
      fullPath: '/$locale/share/$slug'
      preLoaderRoute: typeof LocaleShareSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/app/inbox': {
      id: '/$locale/app/inbox'
      path: '/inbox'
      fullPath: '/$locale/app/inbox'
      preLoaderRoute: typeof LocaleAppInboxRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/app/account': {
      id: '/$locale/app/account'
      path: '/account'
      fullPath: '/$locale/app/account'
      preLoaderRoute: typeof LocaleAppAccountRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/app/$teamSlug': {
      id: '/$locale/app/$teamSlug'
      path: '/$teamSlug'
      fullPath: '/$locale/app/$teamSlug'
      preLoaderRoute: typeof LocaleAppTeamSlugRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/share/$slug/': {
      id: '/$locale/share/$slug/'
      path: '/'
      fullPath: '/$locale/share/$slug/'
      preLoaderRoute: typeof LocaleShareSlugIndexRouteImport
      parentRoute: typeof LocaleShareSlugRoute
    }
    '/$locale/app/$teamSlug/': {
      id: '/$locale/app/$teamSlug/'
      path: '/'
      fullPath: '/$locale/app/$teamSlug/'
      preLoaderRoute: typeof LocaleAppTeamSlugIndexRouteImport
      parentRoute: typeof LocaleAppTeamSlugRoute
    }
    '/$locale/share/$slug/retention': {
      id: '/$locale/share/$slug/retention'
      path: '/retention'
      fullPath: '/$locale/share/$slug/retention'
      preLoaderRoute: typeof LocaleShareSlugRetentionRouteImport
      parentRoute: typeof LocaleShareSlugRoute
    }
    '/$locale/share/$slug/referrers': {
      id: '/$locale/share/$slug/referrers'
      path: '/referrers'
      fullPath: '/$locale/share/$slug/referrers'
      preLoaderRoute: typeof LocaleShareSlugReferrersRouteImport
      parentRoute: typeof LocaleShareSlugRoute
    }
    '/$locale/share/$slug/performance': {
      id: '/$locale/share/$slug/performance'
      path: '/performance'
      fullPath: '/$locale/share/$slug/performance'
      preLoaderRoute: typeof LocaleShareSlugPerformanceRouteImport
      parentRoute: typeof LocaleShareSlugRoute
    }
    '/$locale/share/$slug/pages': {
      id: '/$locale/share/$slug/pages'
      path: '/pages'
      fullPath: '/$locale/share/$slug/pages'
      preLoaderRoute: typeof LocaleShareSlugPagesRouteImport
      parentRoute: typeof LocaleShareSlugRoute
    }
    '/$locale/share/$slug/geo': {
      id: '/$locale/share/$slug/geo'
      path: '/geo'
      fullPath: '/$locale/share/$slug/geo'
      preLoaderRoute: typeof LocaleShareSlugGeoRouteImport
      parentRoute: typeof LocaleShareSlugRoute
    }
    '/$locale/share/$slug/devices': {
      id: '/$locale/share/$slug/devices'
      path: '/devices'
      fullPath: '/$locale/share/$slug/devices'
      preLoaderRoute: typeof LocaleShareSlugDevicesRouteImport
      parentRoute: typeof LocaleShareSlugRoute
    }
    '/$locale/share/$slug/campaigns': {
      id: '/$locale/share/$slug/campaigns'
      path: '/campaigns'
      fullPath: '/$locale/share/$slug/campaigns'
      preLoaderRoute: typeof LocaleShareSlugCampaignsRouteImport
      parentRoute: typeof LocaleShareSlugRoute
    }
    '/$locale/share/$slug/browsers': {
      id: '/$locale/share/$slug/browsers'
      path: '/browsers'
      fullPath: '/$locale/share/$slug/browsers'
      preLoaderRoute: typeof LocaleShareSlugBrowsersRouteImport
      parentRoute: typeof LocaleShareSlugRoute
    }
    '/$locale/embeds/landing/$view': {
      id: '/$locale/embeds/landing/$view'
      path: '/embeds/landing/$view'
      fullPath: '/$locale/embeds/landing/$view'
      preLoaderRoute: typeof LocaleEmbedsLandingViewRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/app/manage/version-updates': {
      id: '/$locale/app/manage/version-updates'
      path: '/manage/version-updates'
      fullPath: '/$locale/app/manage/version-updates'
      preLoaderRoute: typeof LocaleAppManageVersionUpdatesRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/app/manage/users': {
      id: '/$locale/app/manage/users'
      path: '/manage/users'
      fullPath: '/$locale/app/manage/users'
      preLoaderRoute: typeof LocaleAppManageUsersRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/app/manage/teams': {
      id: '/$locale/app/manage/teams'
      path: '/manage/teams'
      fullPath: '/$locale/app/manage/teams'
      preLoaderRoute: typeof LocaleAppManageTeamsRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/app/manage/system-settings': {
      id: '/$locale/app/manage/system-settings'
      path: '/manage/system-settings'
      fullPath: '/$locale/app/manage/system-settings'
      preLoaderRoute: typeof LocaleAppManageSystemSettingsRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/app/manage/system-performance': {
      id: '/$locale/app/manage/system-performance'
      path: '/manage/system-performance'
      fullPath: '/$locale/app/manage/system-performance'
      preLoaderRoute: typeof LocaleAppManageSystemPerformanceRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/app/manage/scheduled-tasks': {
      id: '/$locale/app/manage/scheduled-tasks'
      path: '/manage/scheduled-tasks'
      fullPath: '/$locale/app/manage/scheduled-tasks'
      preLoaderRoute: typeof LocaleAppManageScheduledTasksRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/app/manage/request-observation': {
      id: '/$locale/app/manage/request-observation'
      path: '/manage/request-observation'
      fullPath: '/$locale/app/manage/request-observation'
      preLoaderRoute: typeof LocaleAppManageRequestObservationRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/app/$teamSlug/widgets': {
      id: '/$locale/app/$teamSlug/widgets'
      path: '/widgets'
      fullPath: '/$locale/app/$teamSlug/widgets'
      preLoaderRoute: typeof LocaleAppTeamSlugWidgetsRouteImport
      parentRoute: typeof LocaleAppTeamSlugRoute
    }
    '/$locale/app/$teamSlug/settings': {
      id: '/$locale/app/$teamSlug/settings'
      path: '/settings'
      fullPath: '/$locale/app/$teamSlug/settings'
      preLoaderRoute: typeof LocaleAppTeamSlugSettingsRouteImport
      parentRoute: typeof LocaleAppTeamSlugRoute
    }
    '/$locale/app/$teamSlug/public-links': {
      id: '/$locale/app/$teamSlug/public-links'
      path: '/public-links'
      fullPath: '/$locale/app/$teamSlug/public-links'
      preLoaderRoute: typeof LocaleAppTeamSlugPublicLinksRouteImport
      parentRoute: typeof LocaleAppTeamSlugRoute
    }
    '/$locale/app/$teamSlug/notifications': {
      id: '/$locale/app/$teamSlug/notifications'
      path: '/notifications'
      fullPath: '/$locale/app/$teamSlug/notifications'
      preLoaderRoute: typeof LocaleAppTeamSlugNotificationsRouteImport
      parentRoute: typeof LocaleAppTeamSlugRoute
    }
    '/$locale/app/$teamSlug/members': {
      id: '/$locale/app/$teamSlug/members'
      path: '/members'
      fullPath: '/$locale/app/$teamSlug/members'
      preLoaderRoute: typeof LocaleAppTeamSlugMembersRouteImport
      parentRoute: typeof LocaleAppTeamSlugRoute
    }
    '/$locale/app/$teamSlug/api-keys': {
      id: '/$locale/app/$teamSlug/api-keys'
      path: '/api-keys'
      fullPath: '/$locale/app/$teamSlug/api-keys'
      preLoaderRoute: typeof LocaleAppTeamSlugApiKeysRouteImport
      parentRoute: typeof LocaleAppTeamSlugRoute
    }
    '/$locale/app/$teamSlug/$siteSlug': {
      id: '/$locale/app/$teamSlug/$siteSlug'
      path: '/$siteSlug'
      fullPath: '/$locale/app/$teamSlug/$siteSlug'
      preLoaderRoute: typeof LocaleAppTeamSlugSiteSlugRouteImport
      parentRoute: typeof LocaleAppTeamSlugRoute
    }
    '/$locale/app/$teamSlug/$siteSlug/': {
      id: '/$locale/app/$teamSlug/$siteSlug/'
      path: '/'
      fullPath: '/$locale/app/$teamSlug/$siteSlug/'
      preLoaderRoute: typeof LocaleAppTeamSlugSiteSlugIndexRouteImport
      parentRoute: typeof LocaleAppTeamSlugSiteSlugRoute
    }
    '/$locale/share/$slug/pages_/$pageKey': {
      id: '/$locale/share/$slug/pages_/$pageKey'
      path: '/pages/$pageKey'
      fullPath: '/$locale/share/$slug/pages/$pageKey'
      preLoaderRoute: typeof LocaleShareSlugPagesPageKeyRouteImport
      parentRoute: typeof LocaleShareSlugRoute
    }
    '/$locale/app/$teamSlug/notifications_/email-preview': {
      id: '/$locale/app/$teamSlug/notifications_/email-preview'
      path: '/notifications/email-preview'
      fullPath: '/$locale/app/$teamSlug/notifications/email-preview'
      preLoaderRoute: typeof LocaleAppTeamSlugNotificationsEmailPreviewRouteImport
      parentRoute: typeof LocaleAppTeamSlugRoute
    }
    '/$locale/app/$teamSlug/manage/sites': {
      id: '/$locale/app/$teamSlug/manage/sites'
      path: '/manage/sites'
      fullPath: '/$locale/app/$teamSlug/manage/sites'
      preLoaderRoute: typeof LocaleAppTeamSlugManageSitesRouteImport
      parentRoute: typeof LocaleAppTeamSlugRoute
    }
    '/$locale/app/$teamSlug/account/notifications': {
      id: '/$locale/app/$teamSlug/account/notifications'
      path: '/account/notifications'
      fullPath: '/$locale/app/$teamSlug/account/notifications'
      preLoaderRoute: typeof LocaleAppTeamSlugAccountNotificationsRouteImport
      parentRoute: typeof LocaleAppTeamSlugRoute
    }
    '/$locale/app/$teamSlug/$siteSlug/visitors': {
      id: '/$locale/app/$teamSlug/$siteSlug/visitors'
      path: '/visitors'
      fullPath: '/$locale/app/$teamSlug/$siteSlug/visitors'
      preLoaderRoute: typeof LocaleAppTeamSlugSiteSlugVisitorsRouteImport
      parentRoute: typeof LocaleAppTeamSlugSiteSlugRoute
    }
    '/$locale/app/$teamSlug/$siteSlug/settings': {
      id: '/$locale/app/$teamSlug/$siteSlug/settings'
      path: '/settings'
      fullPath: '/$locale/app/$teamSlug/$siteSlug/settings'
      preLoaderRoute: typeof LocaleAppTeamSlugSiteSlugSettingsRouteImport
      parentRoute: typeof LocaleAppTeamSlugSiteSlugRoute
    }
    '/$locale/app/$teamSlug/$siteSlug/sessions': {
      id: '/$locale/app/$teamSlug/$siteSlug/sessions'
      path: '/sessions'
      fullPath: '/$locale/app/$teamSlug/$siteSlug/sessions'
      preLoaderRoute: typeof LocaleAppTeamSlugSiteSlugSessionsRouteImport
      parentRoute: typeof LocaleAppTeamSlugSiteSlugRoute
    }
    '/$locale/app/$teamSlug/$siteSlug/retention': {
      id: '/$locale/app/$teamSlug/$siteSlug/retention'
      path: '/retention'
      fullPath: '/$locale/app/$teamSlug/$siteSlug/retention'
      preLoaderRoute: typeof LocaleAppTeamSlugSiteSlugRetentionRouteImport
      parentRoute: typeof LocaleAppTeamSlugSiteSlugRoute
    }
    '/$locale/app/$teamSlug/$siteSlug/referrers': {
      id: '/$locale/app/$teamSlug/$siteSlug/referrers'
      path: '/referrers'
      fullPath: '/$locale/app/$teamSlug/$siteSlug/referrers'
      preLoaderRoute: typeof LocaleAppTeamSlugSiteSlugReferrersRouteImport
      parentRoute: typeof LocaleAppTeamSlugSiteSlugRoute
    }
    '/$locale/app/$teamSlug/$siteSlug/realtime': {
      id: '/$locale/app/$teamSlug/$siteSlug/realtime'
      path: '/realtime'
      fullPath: '/$locale/app/$teamSlug/$siteSlug/realtime'
      preLoaderRoute: typeof LocaleAppTeamSlugSiteSlugRealtimeRouteImport
      parentRoute: typeof LocaleAppTeamSlugSiteSlugRoute
    }
    '/$locale/app/$teamSlug/$siteSlug/performance': {
      id: '/$locale/app/$teamSlug/$siteSlug/performance'
      path: '/performance'
      fullPath: '/$locale/app/$teamSlug/$siteSlug/performance'
      preLoaderRoute: typeof LocaleAppTeamSlugSiteSlugPerformanceRouteImport
      parentRoute: typeof LocaleAppTeamSlugSiteSlugRoute
    }
    '/$locale/app/$teamSlug/$siteSlug/pages': {
      id: '/$locale/app/$teamSlug/$siteSlug/pages'
      path: '/pages'
      fullPath: '/$locale/app/$teamSlug/$siteSlug/pages'
      preLoaderRoute: typeof LocaleAppTeamSlugSiteSlugPagesRouteImport
      parentRoute: typeof LocaleAppTeamSlugSiteSlugRoute
    }
    '/$locale/app/$teamSlug/$siteSlug/geo': {
      id: '/$locale/app/$teamSlug/$siteSlug/geo'
      path: '/geo'
      fullPath: '/$locale/app/$teamSlug/$siteSlug/geo'
      preLoaderRoute: typeof LocaleAppTeamSlugSiteSlugGeoRouteImport
      parentRoute: typeof LocaleAppTeamSlugSiteSlugRoute
    }
    '/$locale/app/$teamSlug/$siteSlug/funnels': {
      id: '/$locale/app/$teamSlug/$siteSlug/funnels'
      path: '/funnels'
      fullPath: '/$locale/app/$teamSlug/$siteSlug/funnels'
      preLoaderRoute: typeof LocaleAppTeamSlugSiteSlugFunnelsRouteImport
      parentRoute: typeof LocaleAppTeamSlugSiteSlugRoute
    }
    '/$locale/app/$teamSlug/$siteSlug/events': {
      id: '/$locale/app/$teamSlug/$siteSlug/events'
      path: '/events'
      fullPath: '/$locale/app/$teamSlug/$siteSlug/events'
      preLoaderRoute: typeof LocaleAppTeamSlugSiteSlugEventsRouteImport
      parentRoute: typeof LocaleAppTeamSlugSiteSlugRoute
    }
    '/$locale/app/$teamSlug/$siteSlug/devices': {
      id: '/$locale/app/$teamSlug/$siteSlug/devices'
      path: '/devices'
      fullPath: '/$locale/app/$teamSlug/$siteSlug/devices'
      preLoaderRoute: typeof LocaleAppTeamSlugSiteSlugDevicesRouteImport
      parentRoute: typeof LocaleAppTeamSlugSiteSlugRoute
    }
    '/$locale/app/$teamSlug/$siteSlug/campaigns': {
      id: '/$locale/app/$teamSlug/$siteSlug/campaigns'
      path: '/campaigns'
      fullPath: '/$locale/app/$teamSlug/$siteSlug/campaigns'
      preLoaderRoute: typeof LocaleAppTeamSlugSiteSlugCampaignsRouteImport
      parentRoute: typeof LocaleAppTeamSlugSiteSlugRoute
    }
    '/$locale/app/$teamSlug/$siteSlug/browsers': {
      id: '/$locale/app/$teamSlug/$siteSlug/browsers'
      path: '/browsers'
      fullPath: '/$locale/app/$teamSlug/$siteSlug/browsers'
      preLoaderRoute: typeof LocaleAppTeamSlugSiteSlugBrowsersRouteImport
      parentRoute: typeof LocaleAppTeamSlugSiteSlugRoute
    }
    '/$locale/app/$teamSlug/$siteSlug/visitors_/detail': {
      id: '/$locale/app/$teamSlug/$siteSlug/visitors_/detail'
      path: '/visitors/detail'
      fullPath: '/$locale/app/$teamSlug/$siteSlug/visitors/detail'
      preLoaderRoute: typeof LocaleAppTeamSlugSiteSlugVisitorsDetailRouteImport
      parentRoute: typeof LocaleAppTeamSlugSiteSlugRoute
    }
    '/$locale/app/$teamSlug/$siteSlug/sessions_/detail': {
      id: '/$locale/app/$teamSlug/$siteSlug/sessions_/detail'
      path: '/sessions/detail'
      fullPath: '/$locale/app/$teamSlug/$siteSlug/sessions/detail'
      preLoaderRoute: typeof LocaleAppTeamSlugSiteSlugSessionsDetailRouteImport
      parentRoute: typeof LocaleAppTeamSlugSiteSlugRoute
    }
    '/$locale/app/$teamSlug/$siteSlug/pages_/$pageKey': {
      id: '/$locale/app/$teamSlug/$siteSlug/pages_/$pageKey'
      path: '/pages/$pageKey'
      fullPath: '/$locale/app/$teamSlug/$siteSlug/pages/$pageKey'
      preLoaderRoute: typeof LocaleAppTeamSlugSiteSlugPagesPageKeyRouteImport
      parentRoute: typeof LocaleAppTeamSlugSiteSlugRoute
    }
    '/$locale/app/$teamSlug/$siteSlug/events_/detail': {
      id: '/$locale/app/$teamSlug/$siteSlug/events_/detail'
      path: '/events/detail'
      fullPath: '/$locale/app/$teamSlug/$siteSlug/events/detail'
      preLoaderRoute: typeof LocaleAppTeamSlugSiteSlugEventsDetailRouteImport
      parentRoute: typeof LocaleAppTeamSlugSiteSlugRoute
    }
  }
}

interface LocaleAppTeamSlugSiteSlugRouteChildren {
  LocaleAppTeamSlugSiteSlugBrowsersRoute: typeof LocaleAppTeamSlugSiteSlugBrowsersRoute
  LocaleAppTeamSlugSiteSlugCampaignsRoute: typeof LocaleAppTeamSlugSiteSlugCampaignsRoute
  LocaleAppTeamSlugSiteSlugDevicesRoute: typeof LocaleAppTeamSlugSiteSlugDevicesRoute
  LocaleAppTeamSlugSiteSlugEventsRoute: typeof LocaleAppTeamSlugSiteSlugEventsRoute
  LocaleAppTeamSlugSiteSlugFunnelsRoute: typeof LocaleAppTeamSlugSiteSlugFunnelsRoute
  LocaleAppTeamSlugSiteSlugGeoRoute: typeof LocaleAppTeamSlugSiteSlugGeoRoute
  LocaleAppTeamSlugSiteSlugPagesRoute: typeof LocaleAppTeamSlugSiteSlugPagesRoute
  LocaleAppTeamSlugSiteSlugPerformanceRoute: typeof LocaleAppTeamSlugSiteSlugPerformanceRoute
  LocaleAppTeamSlugSiteSlugRealtimeRoute: typeof LocaleAppTeamSlugSiteSlugRealtimeRoute
  LocaleAppTeamSlugSiteSlugReferrersRoute: typeof LocaleAppTeamSlugSiteSlugReferrersRoute
  LocaleAppTeamSlugSiteSlugRetentionRoute: typeof LocaleAppTeamSlugSiteSlugRetentionRoute
  LocaleAppTeamSlugSiteSlugSessionsRoute: typeof LocaleAppTeamSlugSiteSlugSessionsRoute
  LocaleAppTeamSlugSiteSlugSettingsRoute: typeof LocaleAppTeamSlugSiteSlugSettingsRoute
  LocaleAppTeamSlugSiteSlugVisitorsRoute: typeof LocaleAppTeamSlugSiteSlugVisitorsRoute
  LocaleAppTeamSlugSiteSlugIndexRoute: typeof LocaleAppTeamSlugSiteSlugIndexRoute
  LocaleAppTeamSlugSiteSlugEventsDetailRoute: typeof LocaleAppTeamSlugSiteSlugEventsDetailRoute
  LocaleAppTeamSlugSiteSlugPagesPageKeyRoute: typeof LocaleAppTeamSlugSiteSlugPagesPageKeyRoute
  LocaleAppTeamSlugSiteSlugSessionsDetailRoute: typeof LocaleAppTeamSlugSiteSlugSessionsDetailRoute
  LocaleAppTeamSlugSiteSlugVisitorsDetailRoute: typeof LocaleAppTeamSlugSiteSlugVisitorsDetailRoute
}

const LocaleAppTeamSlugSiteSlugRouteChildren: LocaleAppTeamSlugSiteSlugRouteChildren =
  {
    LocaleAppTeamSlugSiteSlugBrowsersRoute:
      LocaleAppTeamSlugSiteSlugBrowsersRoute,
    LocaleAppTeamSlugSiteSlugCampaignsRoute:
      LocaleAppTeamSlugSiteSlugCampaignsRoute,
    LocaleAppTeamSlugSiteSlugDevicesRoute:
      LocaleAppTeamSlugSiteSlugDevicesRoute,
    LocaleAppTeamSlugSiteSlugEventsRoute: LocaleAppTeamSlugSiteSlugEventsRoute,
    LocaleAppTeamSlugSiteSlugFunnelsRoute:
      LocaleAppTeamSlugSiteSlugFunnelsRoute,
    LocaleAppTeamSlugSiteSlugGeoRoute: LocaleAppTeamSlugSiteSlugGeoRoute,
    LocaleAppTeamSlugSiteSlugPagesRoute: LocaleAppTeamSlugSiteSlugPagesRoute,
    LocaleAppTeamSlugSiteSlugPerformanceRoute:
      LocaleAppTeamSlugSiteSlugPerformanceRoute,
    LocaleAppTeamSlugSiteSlugRealtimeRoute:
      LocaleAppTeamSlugSiteSlugRealtimeRoute,
    LocaleAppTeamSlugSiteSlugReferrersRoute:
      LocaleAppTeamSlugSiteSlugReferrersRoute,
    LocaleAppTeamSlugSiteSlugRetentionRoute:
      LocaleAppTeamSlugSiteSlugRetentionRoute,
    LocaleAppTeamSlugSiteSlugSessionsRoute:
      LocaleAppTeamSlugSiteSlugSessionsRoute,
    LocaleAppTeamSlugSiteSlugSettingsRoute:
      LocaleAppTeamSlugSiteSlugSettingsRoute,
    LocaleAppTeamSlugSiteSlugVisitorsRoute:
      LocaleAppTeamSlugSiteSlugVisitorsRoute,
    LocaleAppTeamSlugSiteSlugIndexRoute: LocaleAppTeamSlugSiteSlugIndexRoute,
    LocaleAppTeamSlugSiteSlugEventsDetailRoute:
      LocaleAppTeamSlugSiteSlugEventsDetailRoute,
    LocaleAppTeamSlugSiteSlugPagesPageKeyRoute:
      LocaleAppTeamSlugSiteSlugPagesPageKeyRoute,
    LocaleAppTeamSlugSiteSlugSessionsDetailRoute:
      LocaleAppTeamSlugSiteSlugSessionsDetailRoute,
    LocaleAppTeamSlugSiteSlugVisitorsDetailRoute:
      LocaleAppTeamSlugSiteSlugVisitorsDetailRoute,
  }

const LocaleAppTeamSlugSiteSlugRouteWithChildren =
  LocaleAppTeamSlugSiteSlugRoute._addFileChildren(
    LocaleAppTeamSlugSiteSlugRouteChildren,
  )

interface LocaleAppTeamSlugRouteChildren {
  LocaleAppTeamSlugSiteSlugRoute: typeof LocaleAppTeamSlugSiteSlugRouteWithChildren
  LocaleAppTeamSlugApiKeysRoute: typeof LocaleAppTeamSlugApiKeysRoute
  LocaleAppTeamSlugMembersRoute: typeof LocaleAppTeamSlugMembersRoute
  LocaleAppTeamSlugNotificationsRoute: typeof LocaleAppTeamSlugNotificationsRoute
  LocaleAppTeamSlugPublicLinksRoute: typeof LocaleAppTeamSlugPublicLinksRoute
  LocaleAppTeamSlugSettingsRoute: typeof LocaleAppTeamSlugSettingsRoute
  LocaleAppTeamSlugWidgetsRoute: typeof LocaleAppTeamSlugWidgetsRoute
  LocaleAppTeamSlugIndexRoute: typeof LocaleAppTeamSlugIndexRoute
  LocaleAppTeamSlugAccountNotificationsRoute: typeof LocaleAppTeamSlugAccountNotificationsRoute
  LocaleAppTeamSlugManageSitesRoute: typeof LocaleAppTeamSlugManageSitesRoute
  LocaleAppTeamSlugNotificationsEmailPreviewRoute: typeof LocaleAppTeamSlugNotificationsEmailPreviewRoute
}

const LocaleAppTeamSlugRouteChildren: LocaleAppTeamSlugRouteChildren = {
  LocaleAppTeamSlugSiteSlugRoute: LocaleAppTeamSlugSiteSlugRouteWithChildren,
  LocaleAppTeamSlugApiKeysRoute: LocaleAppTeamSlugApiKeysRoute,
  LocaleAppTeamSlugMembersRoute: LocaleAppTeamSlugMembersRoute,
  LocaleAppTeamSlugNotificationsRoute: LocaleAppTeamSlugNotificationsRoute,
  LocaleAppTeamSlugPublicLinksRoute: LocaleAppTeamSlugPublicLinksRoute,
  LocaleAppTeamSlugSettingsRoute: LocaleAppTeamSlugSettingsRoute,
  LocaleAppTeamSlugWidgetsRoute: LocaleAppTeamSlugWidgetsRoute,
  LocaleAppTeamSlugIndexRoute: LocaleAppTeamSlugIndexRoute,
  LocaleAppTeamSlugAccountNotificationsRoute:
    LocaleAppTeamSlugAccountNotificationsRoute,
  LocaleAppTeamSlugManageSitesRoute: LocaleAppTeamSlugManageSitesRoute,
  LocaleAppTeamSlugNotificationsEmailPreviewRoute:
    LocaleAppTeamSlugNotificationsEmailPreviewRoute,
}

const LocaleAppTeamSlugRouteWithChildren =
  LocaleAppTeamSlugRoute._addFileChildren(LocaleAppTeamSlugRouteChildren)

interface LocaleAppRouteChildren {
  LocaleAppTeamSlugRoute: typeof LocaleAppTeamSlugRouteWithChildren
  LocaleAppAccountRoute: typeof LocaleAppAccountRoute
  LocaleAppInboxRoute: typeof LocaleAppInboxRoute
  LocaleAppIndexRoute: typeof LocaleAppIndexRoute
  LocaleAppManageRequestObservationRoute: typeof LocaleAppManageRequestObservationRoute
  LocaleAppManageScheduledTasksRoute: typeof LocaleAppManageScheduledTasksRoute
  LocaleAppManageSystemPerformanceRoute: typeof LocaleAppManageSystemPerformanceRoute
  LocaleAppManageSystemSettingsRoute: typeof LocaleAppManageSystemSettingsRoute
  LocaleAppManageTeamsRoute: typeof LocaleAppManageTeamsRoute
  LocaleAppManageUsersRoute: typeof LocaleAppManageUsersRoute
  LocaleAppManageVersionUpdatesRoute: typeof LocaleAppManageVersionUpdatesRoute
}

const LocaleAppRouteChildren: LocaleAppRouteChildren = {
  LocaleAppTeamSlugRoute: LocaleAppTeamSlugRouteWithChildren,
  LocaleAppAccountRoute: LocaleAppAccountRoute,
  LocaleAppInboxRoute: LocaleAppInboxRoute,
  LocaleAppIndexRoute: LocaleAppIndexRoute,
  LocaleAppManageRequestObservationRoute:
    LocaleAppManageRequestObservationRoute,
  LocaleAppManageScheduledTasksRoute: LocaleAppManageScheduledTasksRoute,
  LocaleAppManageSystemPerformanceRoute: LocaleAppManageSystemPerformanceRoute,
  LocaleAppManageSystemSettingsRoute: LocaleAppManageSystemSettingsRoute,
  LocaleAppManageTeamsRoute: LocaleAppManageTeamsRoute,
  LocaleAppManageUsersRoute: LocaleAppManageUsersRoute,
  LocaleAppManageVersionUpdatesRoute: LocaleAppManageVersionUpdatesRoute,
}

const LocaleAppRouteWithChildren = LocaleAppRoute._addFileChildren(
  LocaleAppRouteChildren,
)

interface LocaleShareSlugRouteChildren {
  LocaleShareSlugBrowsersRoute: typeof LocaleShareSlugBrowsersRoute
  LocaleShareSlugCampaignsRoute: typeof LocaleShareSlugCampaignsRoute
  LocaleShareSlugDevicesRoute: typeof LocaleShareSlugDevicesRoute
  LocaleShareSlugGeoRoute: typeof LocaleShareSlugGeoRoute
  LocaleShareSlugPagesRoute: typeof LocaleShareSlugPagesRoute
  LocaleShareSlugPerformanceRoute: typeof LocaleShareSlugPerformanceRoute
  LocaleShareSlugReferrersRoute: typeof LocaleShareSlugReferrersRoute
  LocaleShareSlugRetentionRoute: typeof LocaleShareSlugRetentionRoute
  LocaleShareSlugIndexRoute: typeof LocaleShareSlugIndexRoute
  LocaleShareSlugPagesPageKeyRoute: typeof LocaleShareSlugPagesPageKeyRoute
}

const LocaleShareSlugRouteChildren: LocaleShareSlugRouteChildren = {
  LocaleShareSlugBrowsersRoute: LocaleShareSlugBrowsersRoute,
  LocaleShareSlugCampaignsRoute: LocaleShareSlugCampaignsRoute,
  LocaleShareSlugDevicesRoute: LocaleShareSlugDevicesRoute,
  LocaleShareSlugGeoRoute: LocaleShareSlugGeoRoute,
  LocaleShareSlugPagesRoute: LocaleShareSlugPagesRoute,
  LocaleShareSlugPerformanceRoute: LocaleShareSlugPerformanceRoute,
  LocaleShareSlugReferrersRoute: LocaleShareSlugReferrersRoute,
  LocaleShareSlugRetentionRoute: LocaleShareSlugRetentionRoute,
  LocaleShareSlugIndexRoute: LocaleShareSlugIndexRoute,
  LocaleShareSlugPagesPageKeyRoute: LocaleShareSlugPagesPageKeyRoute,
}

const LocaleShareSlugRouteWithChildren = LocaleShareSlugRoute._addFileChildren(
  LocaleShareSlugRouteChildren,
)

interface LocaleRouteChildren {
  LocaleAppRoute: typeof LocaleAppRouteWithChildren
  LocaleInviteRoute: typeof LocaleInviteRoute
  LocaleLoginRoute: typeof LocaleLoginRoute
  LocaleResetPasswordRoute: typeof LocaleResetPasswordRoute
  LocaleRuntimeConfigErrorRoute: typeof LocaleRuntimeConfigErrorRoute
  LocaleShareSlugRoute: typeof LocaleShareSlugRouteWithChildren
  LocaleEmbedsLandingViewRoute: typeof LocaleEmbedsLandingViewRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAppRoute: LocaleAppRouteWithChildren,
  LocaleInviteRoute: LocaleInviteRoute,
  LocaleLoginRoute: LocaleLoginRoute,
  LocaleResetPasswordRoute: LocaleResetPasswordRoute,
  LocaleRuntimeConfigErrorRoute: LocaleRuntimeConfigErrorRoute,
  LocaleShareSlugRoute: LocaleShareSlugRouteWithChildren,
  LocaleEmbedsLandingViewRoute: LocaleEmbedsLandingViewRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
