name: README i18n switcher

on:
  push:
    branches: [main]
    paths:
      - README.md
      - .github/readme/README.*.md
      - .github/workflows/readme-switcher.yml
  pull_request:
    branches: [main]
    paths:
      - README.md
      - .github/readme/README.*.md
      - .github/workflows/readme-switcher.yml

permissions:
  contents: write

jobs:
  switcher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          fetch-depth: 0

      - id: switcher
        uses: n9gc/auto-readme-i18n-switcher@v2.0.1
        with:
          folders: |
            .github/readme
          repoReadme: ".github/readme/README.en.md"
          switcherBody: "\n| {{lines}} |\n"

      - name: Push README switcher changes
        if: github.event_name == 'push' && steps.switcher.outputs.switcher_changed == 'true'
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          message: "docs: update README i18n switcher"
